Mixed cached shadow maps (Cached static + dynamic rendered every frame)
Unity-Technologies/Graphics pull request #1559
Opened 2020-08-10 11:27 UTC by FrancescoC-unity

**IMPORTANT:** Requires this C++ PR https://ono.unity3d.com/unity/unity/pull-request/110280/_/graphics/concept-of-static-shadow-caster-for-SRP . Whenever that lands I will bump minimum required version of HDRP.

This PR introduces two features. 

The biggest feature is 
**Mixed cached shadow maps**

It is now possible to tag objects as Static Shadow Casters (with the C++ PR above). Selecting the new option Always draw dynamic on the shadows, it is possible to have all static objects cached and dynamic objects rendered on top every frame. 

See the example in the gif, all pillars are marked as static (when moved the shadow is not updated) and the dancing dude is not. You can see how its shadow is updated every frame while the rest of the shadows are not. 

![MixedCached](https://user-images.githubusercontent.com/43168857/89777646-5fb4db00-db0c-11ea-89e0-7a16fefc035e.gif)

This will allow the cached shadows to be used in many more use cases. Lots of games have static environments but few movable characters and objects, so before those couldn't use cached shadows, but now can for significant perf benefits (both CPU and GPU as most of the objects will not be rendered anymore in shadows). 

Shortly, this work rendering first all static in cached atlas when an update is required, then blit from cache to dynamic atlas and subsequently every frame the dynamic objects are rendered on top of the blitted cached shadows.

2020-08-10 11:47 UTC, JordanL8 commented on com.unity.render-pipelines.high-definition/Documentation~/Shadows-in-HDRP.md
> +As a shortcut for a common case, HDRP offers an option to automatically trigger an update when either the position or rotation of a light changes above a certain threshold. This option can be selecte
As a shortcut for a common case, HDRP offers an option to automatically trigger an update when either the position or rotation of a light changes above a certain threshold. To enable this option, select a [Light](Light-Component.md) and, in the **Shadow** section of its Inspector, enable **Update on light movement**.

2020-08-10 11:50 UTC, JordanL8 commented on com.unity.render-pipelines.high-definition/Documentation~/Shadows-in-HDRP.md
> +The threshold that are used to determine how much a light needs to move or rotate to trigger an update can be customized per light with the properties
You can customize the threshold that HDRP uses to determine how much a light needs to move or rotate to trigger an update. To do this, use the:

2020-08-10 11:50 UTC, JordanL8 commented on com.unity.render-pipelines.high-definition/Documentation~/Shadows-in-HDRP.md
> +`cachedShadowTranslationUpdateThreshold` and `cachedShadowAngleUpdateThreshold` on the **HDAdditionalLightData** component. Note that point lights ignore the angle differences when determining if an
`cachedShadowTranslationUpdateThreshold` and `cachedShadowAngleUpdateThreshold` properties on the Light's **HDAdditionalLightData** component. Note that point lights ignore the angle differences when determining if they need to perform an update in this mode.

2020-08-10 12:00 UTC, JordanL8 commented on com.unity.render-pipelines.high-definition/Documentation~/Shadows-in-HDRP.md
> +It is possible to cache only a portion of the shadow map. In order to do so, you must check the **Always draw dynamic** option in the shadow settings of the light and then tick the **Static Shadow Ca
It is possible to cache only a portion of the shadow map. To do this, enable the **Always draw dynamic** option in the [Light's](Light-Component.md) shadow settings and then enable the **Static Shadow Caster** option for all Renderers to cache shadows for.

2020-08-10 12:03 UTC, JordanL8 commented on com.unity.render-pipelines.high-definition/Documentation~/Shadows-in-HDRP.md
> +With such setup, all static shadow casters are rendered in the shadow map only whenever an explicit update is requested (or only on light enable in case of **OnEnable** update mode), while the other
With this setup, HDRP only renders static shadow casters into the shadow map when an explicit update is requested (or, if the Light uses the **OnEnable** update mode, only when the Light enables) whereas, for dynamic shadow casters, HDRP renders them into their respective shadow maps each frame.

2020-08-10 12:04 UTC, JordanL8 commented on com.unity.render-pipelines.high-definition/Documentation~/Shadows-in-HDRP.md
> +This setup is particularly useful if for example your environment is mostly static and the light doesn't move, but there are few dynamic objects that will need shadows to be cast by such lights. In s
This setup is particularly useful if your environment consists of mostly static GameObjects and the lights do not move, but there are few dynamic GameObjects that you want the static lights to cast shadows for. In such scenarios, setting the light to have a mixed cached shadow map greatly improves performance both on CPU and GPU.

2020-08-10 12:06 UTC, JordanL8 commented on com.unity.render-pipelines.high-definition/Documentation~/Shadows-in-HDRP.md
> +Please note that as part of implementation details, if a shadow is set up as mixed cached, every frame a blit from the cached shadow map to the dynamic atlas is performed. This is important to keep i
Note that, due to implementation details, if you set up a shadow to be mixed cached, HDRP performs a blit from the cached shadow map to the dynamic atlas. This is important to keep in mind both for the extra runtime cost of the blit in itself, but also to understand that, in terms of memory, a single shadow map requires space in both atlases.

2020-08-10 12:08 UTC, JordanL8 commented on com.unity.render-pipelines.high-definition/Documentation~/Shadows-in-HDRP.md
> +Another important note, is due to implementation details, if a light with mixed cached shadows moves and the cached counterpart is not updated, the result will look wrong. In such cases either select
Another important note, also due to implementation details, if a Light with mixed cached shadows moves and you do not update the cached counterpart, the result looks wrong. In such cases either enable the Light's **Update on light movement** option or set the Light's update mode to **OnDemand** and make sure to trigger an update when you move the Light.

2020-08-10 13:48 UTC, FrancescoC-unity commented
Fixed up docs as suggested @JordanL8

2020-08-12 14:08 UTC, iM0ve commented
**Review in Progress**


**ISSUES**
1) Tooltip has a space before the text

![image](https://user-images.githubusercontent.com/36502659/90012029-47c78d80-dcab-11ea-94c2-6862e0321c81.png)

2) Setup is a bit confusing. Do we have a restriction that's why it's like that?

From the documentation, it notes that this feature is useful because most of the time MAJORITY of the assets are static but you have a few that you want dynamic shadows for. But the implementation for the user is completely different, by checking **Always draw dynamic** on a light - all of your shadows become realtime, forcing you to go over every object and fix them.

Can the **Always draw dynamic** checbox be removed or we need it?
If by default **Always draw dynamic* is always on(remove parameter) and the **Static shadow caster** is also On by default (dont remove parameter). Then usage would be very simplified, all you have to do is uncheck **Static shadow caster** for objects you want realtime shadows for and thats it. Again Im just looking at this from usage convenience, maybe there is a technical reason we can not implement it like this.

**Test coverage**
* Tooltips
* Documentation

2020-08-13 07:41 UTC, FrancescoC-unity commented
1- Will fix, though it is on C++ side so it will be a bit of a mess :-) Will see for next release. 

2- Several points to make here: 

 The checkbox we absolutely need otherwise all cached shadows will be mixed and it is not what we want. We need to have a discrimination of the two types. Sometimes you are fine with dynamic stuff being rendered for one light and not for another and to differentiate you need a checkbox on the light. 

  The checkbox on the renderer is engine side and it is going to be used by all SRPs, we cannot make it default (changing default behaviour) for HDRP usages. So while I agree, if it was hdrp only I would've made that on by default, we cannot really do that. 

 3- The static checkbox up there is lost at runtime, so it is unusable sadly. Again, the reason for the naming is due to it being a generic engine side thing and its implementation is generic to any Shadow map draw call that is done via SRP, so cannot really  make it reference cached shadow maps. The tooltip is there to show a potential usage linking to what HDRP does.

2020-08-13 11:16 UTC, iM0ve commented
Thanks, added 4 and 5.

2020-08-13 11:19 UTC, FrancescoC-unity commented
4- I agree that it is a bit bad, but unfortunately we can't fix this case as we don't have a list of game objects that are in each state on C# nor easily in C++. If we ever will have scriptable culling then this could change at some point; as of now sadly not. 

5- I think i know what's the issue! I am in vacation, but will check and fix when back.

2020-08-24 14:52 UTC, JulienIgnace-Unity approved these changes

2020-08-25 12:11 UTC, FrancescoC-unity commented
I disabled the directional light case, to make it work we need even more memory. Waiting for the RG to be main case to do that. 
It is the least useful case anyway (since directional light shadows need frequent re-updates). 

Ping @iM0ve re the bug above on the directional light.

2020-08-25 14:56 UTC, iM0ve requested changes
The issue #5 still reproduces for me. 
I have:
* Pulled the disable/fix 
* Deleted the Library folder
* Tried turning Directional light on/off

![asdgewg](https://user-images.githubusercontent.com/36502659/91190468-490da700-e6fc-11ea-8b2d-1d6939d83894.gif)

2020-08-27 08:27 UTC, iM0ve approved these changes
All issues fixed or addressed

2020-10-06 09:47 UTC, sebastienlagarde approved these changes

2020-10-07 22:34 UTC, merged