Universal/shadow mask support
Unity-Technologies/Graphics pull request #1594
Opened 2020-08-13 10:21 UTC by lukaschod

# **Please read;**
## **PR Workflow for the Graphics repository:**
* **All PRs must be opened as draft initially**
* Reviewers can be added while the PR is still in draft
* The PR can be marked as “Ready for Review” once the reviewers have confirmed that **no more changes are needed**
* Tests will start automatically after the PR is marked as “Ready for Review”
* **Do not use [skip ci]** - this can break some of our tooling
* Read the [Graphics repository & Yamato FAQ](http://go/graphics-yamato-faq).

### Checklist for PR maker
- [ ] Have you added a backport label (if needed)? For example, the `need-backport-*` label. After you backport the PR, the label changes to `backported-*`.
- [ ] Have you updated the changelog? Each package has a `CHANGELOG.md` file.
- [ ]  Have you updated or added the documentation for your PR? When you add a new feature, change a property name, or change the behavior of a feature, it's best practice to include related documentation changes in the same PR. If you do add documentation, make sure to add the relevant Graphics Docs team member as a reviewer of the PR. If you are not sure which person to add, see the [Docs team contacts sheet](https://docs.google.com/spreadsheets/d/1rgUWWgwLFEHIQ3Rz-LnK6PAKmbM49DZZ9al4hvnztOo/edit#gid=1058860420).
- [ ] Have you added a graphic test for your PR (if needed)? When you add a new feature, or discover a bug that tests don't cover, please add a graphic test.

---
### Purpose of this PR
Why is this PR needed, what hard problem is it solving/fixing?

---
### Testing status

**Manual Tests**: What did you do?
- [ ] Opened test project + Run graphic tests locally
- [ ] Built a player
- [ ] Checked new UI names with UX convention
- [ ] Tested UI multi-edition + Undo/Redo + Prefab overrides + Alignment in Preset
- [ ] C# and shader warnings (supress shader cache to see them)
- [ ] Checked new resources path for the reloader (in developer mode, you have a button at end of resources that check the paths)
- Other: 

**Automated Tests**: What did you setup? (Add a screenshot or the reference image of the test please)

**Yamato**: (Select your branch):
https://yamato.prd.cds.internal.unity3d.com/jobs/902-Graphics

Any test projects to go with this to help reviewers?

---
### Comments to reviewers
Notes for the reviewers you have assigned.

2020-08-13 13:37 UTC, stramit requested changes

2020-08-17 09:04 UTC, lukaschod commented on com.unity.render-pipelines.universal/Shaders/Lit.shader
> +			#pragma multi_compile_fragment _ _SCREEN_SPACE_OCCLUSION
Fixed

2020-08-17 09:04 UTC, lukaschod commented on com.unity.render-pipelines.universal/ShaderLibrary/Lighting.hlsl
> +void MixRealtimeAndBakedGI(inout Light light, float3 positionWS, half3 normalWS, inout half3 bakedGI, half4 shadowMask)
Fixed

2020-08-17 09:04 UTC, lukaschod commented on com.unity.render-pipelines.universal/ShaderLibrary/Shadows.hlsl
> -float ApplyShadowFade(float shadowAttenuation, float3 positionWS)
Fixed

2020-08-25 11:16 UTC, lukaschod commented on com.unity.render-pipelines.universal/ShaderLibrary/Lighting.hlsl
> +void MixRealtimeAndBakedGI(inout Light light, float3 positionWS, half3 normalWS, inout half3 bakedGI, half4 shadowMask)
Maybe we need better name for this?

2020-08-25 11:33 UTC, stramit approved these changes

2020-08-25 13:20 UTC, ellioman commented on com.unity.render-pipelines.universal/ShaderLibrary/Lighting.hlsl
> +void MixRealtimeAndBakedGI(inout Light light, float3 positionWS, half3 normalWS, inout half3 bakedGI, half4 shadowMask)
Now's the chance to do it if we should.

2020-08-25 13:25 UTC, ellioman approved these changes

2020-08-28 09:00 UTC, Nzollner approved these changes

2020-08-28 10:15 UTC, Jonasmortensen approved these changes

2020-08-28 14:19 UTC, thefranke approved these changes
Nice job, looks good to me!

2020-08-28 14:57 UTC, ellioman approved these changes

2020-09-08 14:32 UTC, w1shmast3r requested changes
QA pass has revealed the following issue: **No baked shadowmask is rendered after switching the shadowmask mode to Distance shadowmask, rebaking and setting shadow distance to 0.** 
For more details regarding the repro (project, steps, repro video, and images) please refer to the following [link](https://confluence.unity3d.com/display/teamgi/Shadowmask+support+for+URP#ShadowmasksupportforURP-bug3). 
This bug needs to be fixed prior to merging this PR.

2020-09-09 11:44 UTC, thefranke approved these changes

2020-09-10 08:57 UTC, lukaschod commented
> QA pass has revealed the following issue: **No baked shadowmask is rendered after switching the shadowmask mode to Distance shadowmask, rebaking and setting shadow distance to 0.**
> For more details regarding the repro (project, steps, repro video, and images) please refer to the following [link](https://confluence.unity3d.com/display/teamgi/Shadowmask+support+for+URP#ShadowmasksupportforURP-bug3).
> This bug needs to be fixed prior to merging this PR.

Fixed in latest commit

2020-09-11 10:59 UTC, w1shmast3r commented
Added @Unity-Technologies/mobile-qa for test pass on mobiles and Linux. More information regarding platform testing could be found here: https://docs.google.com/spreadsheets/d/1OAmFn25Y4OyhQqGeZF-ZSPQPzhfWK_ZXw9-6MmgwtU8/edit#gid=868713657

2020-09-16 17:00 UTC, LandonTownsendUnity commented
Automated test 049_Lighting_Mixed_Subtractive seems to fail right out of the gate when run manually on this branch... any idea why?

2020-09-16 17:30 UTC, LandonTownsendUnity approved these changes
Switched the PBR materials in the automated tests to shadergraph materials and ensured that the results were still identical visually after baking.

2020-09-22 08:42 UTC, phi-lira commented
What's status on this PR?

2020-09-22 09:14 UTC, vaidasma commented
finishing manual shadowmask today

2020-09-22 09:48 UTC, w1shmast3r reviewed
Still waiting for the clarification for this recently found bug: [https://confluence.unity3d.com/display/teamgi/%5BURP%5D+-+Shadowmask+Support#id-[URP]-ShadowmaskSupport-bug7](https://confluence.unity3d.com/display/teamgi/%5BURP%5D+-+Shadowmask+Support#id-[URP]-ShadowmaskSupport-bug7) other than that the Lighting QA test pass is done.

2020-09-22 19:58 UTC, w1shmast3r approved these changes
Lighting QA test pass has been completed on Windows and macOS (both using Editor and Standalone Player.
Link to the feature test doc: [https://confluence.unity3d.com/display/teamgi/%5BURP%5D+-+Shadowmask+Support](https://confluence.unity3d.com/display/teamgi/%5BURP%5D+-+Shadowmask+Support)

Tested with using Unity Version 2020.2.0b3 (ef376aff2859)
Branch: trunk

Tested on the following projects:
- URP Sample scene
- CornellBox URP;
- Sponza URP.

Testing included:
- Checking that the shadowmask gets generated for all aforementioned projects;
- Testing both Shadowmask and Distance Shadowmask modes and ensuring that the behaviour is consistent with the built-in RP;
- Testing some complicated scenarios with baked shadowmask (overlapping lights, toggling shadow distance, switching between lighting modes at runtime, etc)
- Integration with different lightmap backends (CPU/GPU PLM, Enlighten), different shaders and geometry (terrains).

Test outcomes:
- Several UI and functional bugs found, addressed and verified;
- **1 known UI issue:** [https://fogbugz.unity3d.com/f/cases/1279615/](No Light Overlap mode scene view visualization filter in URP). Discussed that with Lukas and decided that due to the complexity of the potential fix, we need to fix this bug separately
- Several unrelated issues related to URP integration with certain shaders and mixed lighting modes found. All of them have been logged to FogBugz;
- No other new regressions or ship-stoppers introduced by this PR have been found.

Approving as or revision 3f7f2fc60bb4c7d6848d458b084a8141953d6b38. Great job!

2020-09-22 23:03 UTC, vaidasma approved these changes
Feature looks good on Android and iOS, no artifacts or unexpected behaviours detected. Testing document: https://docs.google.com/document/d/1pshQpUoKHpe7bMmiWVCYzPrUGt44o6whiFMycNDWHIY/edit?usp=sharing

Additional project were not covered in order not to bottleneck the feature time-wise. If additional coverage needed, please contact me.

2020-09-23 07:21 UTC, phi-lira commented
Cancelled yamato. Previous commit was green and new one just fixed a conflict in editor build settings.

2020-09-23 07:21 UTC, merged