Shader Graph: Added Matrix Swizzle Node
Unity-Technologies/Graphics pull request #1615
Opened 2020-08-14 18:42 UTC by tracychen1234

---
### Purpose of this PR
Why is this PR needed, what hard problem is it solving/fixing?
Added the Matrix Swzzile node, updated AddSlot() in AbstractMaterialNode.cs. 
![image](https://user-images.githubusercontent.com/67800322/90279618-67cb8e00-de1e-11ea-817d-b9e05acaeb80.png)
When users change the dropdown, the input boxes will be grayed out according to the selected output size. The node will only allow matrix as input but can output both matrix and vector. 

---
### Testing status

**Manual Tests**: What did you do?
- [ ] Opened test project + Run graphic tests locally
- [ ] Built a player
- [ ] Checked new UI names with UX convention
- [ ] Tested UI multi-edition + Undo/Redo + Prefab overrides + Alignment in Preset
- [ ] C# and shader warnings (supress shader cache to see them)
- [ ] Checked new resources path for the reloader (in developer mode, you have a button at end of resources that check the paths)
- Other: 
Put node in the graph and made sure it's output the correct size according to the selected enum list. Tested out different matrix output nodes as its input. 

**Automated Tests**: What did you setup? (Add a screenshot or the reference image of the test please)
In progress.

**Yamato**: (Select your branch):
https://yamato.prd.cds.internal.unity3d.com/jobs/902-Graphics

Any test projects to go with this to help reviewers?

---
### Comments to reviewers
Notes for the reviewers you have assigned.

2020-08-14 19:02 UTC, alindmanUnity commented
working with tracy to add tests to automated suite

2020-08-14 19:02 UTC, LandonTownsendUnity commented
Can you add some code reviewers? I'm curious about the halo effect of some of the changed files.

2020-08-14 19:19 UTC, LandonTownsendUnity commented
I thought the plan was to have 1 to 1 conversion values be the "default"... but it looks like it's all 0s?
![image](https://user-images.githubusercontent.com/52939698/90285205-4bccea00-de28-11ea-8b33-f2f008f410a2.png)
I thought that it was going to be 00 01 02 03, 10 11 12 13, etc. Was that plan changed?

2020-08-14 19:22 UTC, ghost requested changes
Shouldn't 04 be an invalid index?
![image](https://user-images.githubusercontent.com/52939698/90285448-cd247c80-de28-11ea-96ab-3623448821da.png)

2020-08-14 19:35 UTC, ghost requested changes
![image](https://user-images.githubusercontent.com/52939698/90286324-7a4bc480-de2a-11ea-8eb1-46e1d647cfd9.png)
Deleting the contents of a text box and typing anything that isn't a number (such as a letter or a space) permanently corrupts the box, making it impossible to type anything in it but xx

2020-08-14 19:35 UTC, tracychen1234 commented
Fixing it now!
On Fri, Aug 14, 2020 at 12:22 PM LandonTownsendUnity <
notifications@github.com> wrote:

>
>
> *@LandonTownsendUnity* requested changes on this pull request.
>
>
>
>
> Shouldn't 04 be an invalid index?
>
>
> [image: image]
> <https://user-images.githubusercontent.com/52939698/90285448-cd247c80-de28-11ea-96ab-3623448821da.png>
>
>
>
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Unity-Technologies/Graphics/pull/1615#pullrequestreview-467822965>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQFI2ARQULISDRYSHAFPHVLSAWFH3ANCNFSM4P7YLIFQ>
> .
>
>
>

2020-08-14 20:13 UTC, LandonTownsendUnity commented
I also think that the default input should be a 4 x 4 identity matrix, not a 2x2, so that the user can start filling it out before plugging the matrix in (or have it filled in by default) without getting an out of range error

2020-08-25 20:54 UTC, LandonTownsendUnity commented
The default input is still a 2x2 matrix, meaning you get a "Validation: invalid index!" right out of the gate when you create one.

2020-08-25 21:06 UTC, ghost requested changes
Something is wrong with the row column order here.

![image](https://user-images.githubusercontent.com/52939698/91227850-1489f300-e6dc-11ea-88c2-ddf6f74980cc.png)
I'm using this shadergraph to test.
![image](https://user-images.githubusercontent.com/52939698/91227874-1f448800-e6dc-11ea-9a24-43b992efb1e7.png)
![image](https://user-images.githubusercontent.com/52939698/91227900-29668680-e6dc-11ea-8b11-6e0e65af4586.png)
For some reason, the starting values, which are supposed to give me the matrix that I started with, aren't working correctly.

2020-08-25 21:12 UTC, LandonTownsendUnity commented on com.unity.shadergraph/Editor/Data/Nodes/Math/Matrix/MatrixSwizzleNode.cs
> +                Vector4 indecies = inputIndices.GetRow(r);
You may want to correct the spelling on this variable

2020-08-25 21:18 UTC, LandonTownsendUnity commented on com.unity.shadergraph/Editor/Data/Nodes/Math/Matrix/MatrixSwizzleNode.cs
> +        private bool AreIndiciesValid = true;
You shouldn't put member variables in between functions like this, this should be at the top with the other member variables. Also, the spelling needs to be fixed.

2020-09-07 19:51 UTC, cdxntchou requested changes
I think the big thing to address here is that you've got too many ways to represent the swizzle values, which is complicating the code a lot.  You've got the combined 8-character string, the exploded 8-character array, the individual strings per field, and the floating point combined row.col value.  I think it would simplify things a lot if we just had a "SwizzleRow" class that contained four separate strings, one for each column, and used that as your base data structure in place of the combined 8-character string.

2020-09-07 19:51 UTC, cdxntchou commented on com.unity.shadergraph/Editor/Data/Nodes/Math/Matrix/MatrixSwizzleNode.cs
> +                    if (cell_lst[0] > concreteRowCount-1 || cell_lst[1] > concreteRowCount - 1)
x > y-1
better to use:
x >= y
when they are both expected to be integers

2021-01-08 08:18 UTC, ValGrimm-U3D requested changes
Pasting over revised text for Matrix-Swizzle-Node.md (which was fixed in the Internal repo)

Reorders the elements of the input vector as you specify in the input mask. The length of the input mask determines the dimensions of the output vector.
The error "Invalid Mask" indicates an input mask value which includes one or more channels that do not exist in the input vector.

2021-02-02 16:21 UTC, closed without merging

2021-02-02 16:27 UTC, tracychen1234 commented
Closed the PR because it's not on our 21.2 plan.