Supporting SSGI in the render graph mode.
Unity-Technologies/Graphics pull request #1697
Opened 2020-08-28 12:13 UTC by anisunity

The issue here is that we have no tests for ssgi due the current limitation of the test framework. I tested manually, but I ain't compltely sure. Plus, there is some improvements i'd like to merge that change compltely the output of the effect.

### Testing status
None

2020-08-28 14:29 UTC, JulienIgnace-Unity commented on com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/SSGIDenoiser.cs
> +            if (resources.historyDepthBuffer == null)
Can we do this test outside the funciton? If it fails it means we still need to run a render graph pass through the system and we'll also get an empty profiling marker.

2020-08-28 14:46 UTC, JulienIgnace-Unity requested changes
- Move StartXRSinglePass before SSGI as in regular code path
- Remove obsolete commented code

2020-09-02 11:41 UTC, JulienIgnace-Unity approved these changes

2020-09-03 08:48 UTC, merged

2020-09-08 13:33 UTC, TomasKiniulis commented
Testing manually on Amelienborg palace. Checked Raytracing enabled/disabled with render graph mode on/off. Works as expected 

![raytrace](https://user-images.githubusercontent.com/50582134/92482847-c5ba7e00-f1f0-11ea-84df-43f016a84940.gif)