HDRP - Better handling of supported platform build and better message
Unity-Technologies/Graphics pull request #1809
Opened 2020-09-10 07:23 UTC by sebastienlagarde

# **Please read;**
## **PR Workflow for the Graphics repository:**
* **All PRs must be opened as draft initially**
* Reviewers can be added while the PR is still in draft
* The PR can be marked as “Ready for Review” once the reviewers have confirmed that **no more changes are needed**
* Tests will start automatically after the PR is marked as “Ready for Review”
* **Do not use [skip ci]** - this can break some of our tooling
* Read the [Graphics repository & Yamato FAQ](http://go/graphics-yamato-faq).

### Checklist for PR maker
- [ ] Have you added a backport label (if needed)? For example, the `need-backport-*` label. After you backport the PR, the label changes to `backported-*`.
- [ ] Have you updated the changelog? Each package has a `CHANGELOG.md` file.
- [ ]  Have you updated or added the documentation for your PR? When you add a new feature, change a property name, or change the behavior of a feature, it's best practice to include related documentation changes in the same PR. If you do add documentation, make sure to add the relevant Graphics Docs team member as a reviewer of the PR. If you are not sure which person to add, see the [Docs team contacts sheet](https://docs.google.com/spreadsheets/d/1rgUWWgwLFEHIQ3Rz-LnK6PAKmbM49DZZ9al4hvnztOo/edit#gid=1058860420).
- [ ] Have you added a graphic test for your PR (if needed)? When you add a new feature, or discover a bug that tests don't cover, please add a graphic test.

---
### Purpose of this PR
Why is this PR needed, what hard problem is it solving/fixing?

---
### Testing status

**Manual Tests**: What did you do?
- [ ] Opened test project + Run graphic tests locally
- [ ] Built a player
- [ ] Checked new UI names with UX convention
- [ ] Tested UI multi-edition + Undo/Redo + Prefab overrides + Alignment in Preset
- [ ] C# and shader warnings (supress shader cache to see them)
- [ ] Checked new resources path for the reloader (in developer mode, you have a button at end of resources that check the paths)
- Other: 

**Automated Tests**: What did you setup? (Add a screenshot or the reference image of the test please)

**Yamato**: (Select your branch):
https://yamato.prd.cds.internal.unity3d.com/jobs/902-Graphics

Any test projects to go with this to help reviewers?

---
### Comments to reviewers
Notes for the reviewers you have assigned.

2020-10-27 13:56 UTC, JordanL8 commented on com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Utility/HDUtils.cs
> +                    msg += ", use the Metal graphic API instead";
graphic -> graphics 
For this and the Vulkan one below

2020-10-27 13:58 UTC, JordanL8 commented on com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Utility/HDUtils.cs
> +            msg += ".\nPlease change the platform/device to a compatible one or remove incompatible graphics APIs in Project Settings > Player > Other Settings.";
.\nChange the platform/device to a compatible one or remove incompatible graphics APIs. To do this, go to Project Settings > Player > Other Settings and modify the respective Graphics APIs for <platform> list.

2020-10-27 13:59 UTC, JordanL8 requested changes
Rewrote some bits

2020-10-28 11:05 UTC, JordanL8 approved these changes

2020-10-28 14:01 UTC, adrien-de-tocqueville approved these changes

2020-10-29 20:30 UTC, sebastienlagarde commented
Merging for 10.2

2020-10-29 20:30 UTC, merged

2020-11-03 09:13 UTC, JMargevics reviewed
![image](https://user-images.githubusercontent.com/50581102/97967113-709c8200-1dc5-11eb-91e4-20148b01f537.png)
I've verified iOS error message, and message about vulcan on windows. All good ✔

 Will install Linux and check it there too soon.