Prevent assetPostprocessors from running if the current render pipeli…
Unity-Technologies/Graphics pull request #1826
Opened 2020-09-10 15:17 UTC by Thomasch-unity3d

…ne does not match.

# **Please read;**
## **PR Workflow for the Graphics repository:**
* **All PRs must be opened as draft initially**
* Reviewers can be added while the PR is still in draft
* The PR can be marked as “Ready for Review” once the reviewers have confirmed that **no more changes are needed**
* Tests will start automatically after the PR is marked as “Ready for Review”
* **Do not use [skip ci]** - this can break some of our tooling
* Read the [Graphics repository & Yamato FAQ](http://go/graphics-yamato-faq).

### Checklist for PR maker
- [ ] Have you added a backport label (if needed)? For example, the `need-backport-*` label. After you backport the PR, the label changes to `backported-*`.
- [ ] Have you updated the changelog? Each package has a `CHANGELOG.md` file.
- [ ]  Have you updated or added the documentation for your PR? When you add a new feature, change a property name, or change the behavior of a feature, it's best practice to include related documentation changes in the same PR. If you do add documentation, make sure to add the relevant Graphics Docs team member as a reviewer of the PR. If you are not sure which person to add, see the [Docs team contacts sheet](https://docs.google.com/spreadsheets/d/1rgUWWgwLFEHIQ3Rz-LnK6PAKmbM49DZZ9al4hvnztOo/edit#gid=1058860420).
- [ ] Have you added a graphic test for your PR (if needed)? When you add a new feature, or discover a bug that tests don't cover, please add a graphic test.

---
### Purpose of this PR
Fixes cases 1266644 and 1275341 where materials imported from FBX, sketchup or 3ds files get the HDRP or URP shader assigned even when the active render pipeline asset does not match.

---
### Testing status

**Manual Tests**: What did you do?
- [ ] Opened test project + Run graphic tests locally
- [ ] Built a player
- [ ] Checked new UI names with UX convention
- [ ] Tested UI multi-edition + Undo/Redo + Prefab overrides + Alignment in Preset
- [ ] C# and shader warnings (supress shader cache to see them)
- [ ] Checked new resources path for the reloader (in developer mode, you have a button at end of resources that check the paths)
- Other: 

**Automated Tests**: What did you setup? (Add a screenshot or the reference image of the test please)

**Yamato**: (Select your branch):
https://yamato.prd.cds.internal.unity3d.com/jobs/902-Graphics

Any test projects to go with this to help reviewers?

---
### Comments to reviewers
Notes for the reviewers you have assigned.

2020-09-10 17:00 UTC, sebastienlagarde approved these changes

2020-09-10 17:01 UTC, sebastienlagarde commented
@Thomasch-unity3d I expect it need to be backport up to 19.4 ?

2020-09-11 14:44 UTC, Thomasch-unity3d commented
Yes, I just added the labels.

2020-09-14 12:02 UTC, hybridherbst requested changes
The purpose of this PR is that the importers still work when either a different or no RP is assigned. All these are missing a nullref check for when no RP is assigned.

2020-09-14 12:02 UTC, hybridherbst commented on com.unity.render-pipelines.high-definition/Editor/AssetProcessors/AutodeskInteractiveMaterialImport.cs
> +            if (GraphicsSettings.currentRenderPipeline.GetType() != typeof(HDRenderPipelineAsset))
This is a null reference when no render pipeline is assigned, defeating the purpose of the PR.

2020-09-14 12:02 UTC, hybridherbst commented on com.unity.render-pipelines.high-definition/Editor/AssetProcessors/FBXArnoldSurfaceMaterialDescriptionPreprocessor.cs
> +            if (GraphicsSettings.currentRenderPipeline.GetType() != typeof(HDRenderPipelineAsset))
same here

2020-09-14 12:02 UTC, hybridherbst commented on com.unity.render-pipelines.high-definition/Editor/AssetProcessors/FBXMaterialDescriptionPostprocessor.cs
> +            if (GraphicsSettings.currentRenderPipeline.GetType() != typeof(HDRenderPipelineAsset))
same here

2020-09-14 12:02 UTC, hybridherbst commented on com.unity.render-pipelines.high-definition/Editor/AssetProcessors/SketchupMaterialDescriptionPostprocessor.cs
> +            if (GraphicsSettings.currentRenderPipeline.GetType() != typeof(HDRenderPipelineAsset))
same here

2020-09-14 13:16 UTC, Thomasch-unity3d commented
@hybridherbst thanks, that's fixed in the latest commit.

2020-09-15 07:44 UTC, hybridherbst commented
Unfortunately it's still incorrect:
RenderPipelineAsset is a ScriptableObject so you shouldn't be using 
`if(pipelineAsset == null)`
since that can fail in cases where the object isn't properly instantiated (yet) or already destroyed.
You should use `if(!pipelineAsset)`.

2020-09-15 17:07 UTC, etienne-unity requested changes
This seems to be coming from somewhere else - not related to this PR

> Opening the mesh Preview as a separate window will spam this error (2x):
> ```
> NullReferenceException: Object reference not set to an instance of an object
> UnityEditor.InspectorWindow.get_isLocked () (at <fd96ad39e7754b5bbfcd73fda94a3dc6>:0)
> UnityEditor.EditorTools.EditorToolManager.RebuildAvailableCustomEditorTools () (at <fd96ad39e7754b5bbfcd73fda94a3dc6>:0)
> UnityEditor.EditorTools.EditorToolManager.TrackerRebuilt () (at <fd96ad39e7754b5bbfcd73fda94a3dc6>:0)
> UnityEditor.ActiveEditorTracker.Internal_OnTrackerRebuild () (at <fd96ad39e7754b5bbfcd73fda94a3dc6>:0)

```

2020-09-15 17:55 UTC, Thomasch-unity3d commented
@hybridherbst I added another commit fixing that, thanks!

2020-09-15 19:27 UTC, etienne-unity approved these changes
Not having a render set now has the model re-imported with Standard instead of URP or HDRP
Works with deleted Library, Reimport All and individual reimports

RP all packages @ 10.1.0-preview.22
Version: 2020.2.0b3.3180
Revision: trunk ef376aff2859

2020-09-16 08:26 UTC, sebastienlagarde approved these changes

2020-09-16 11:33 UTC, ellioman approved these changes
Really wish we'd have nice function for these kind of checks instead of the Copy/Paste code all over the place. But that work can be done in a followup PR.

2020-09-16 11:42 UTC, merged