Fix blend modes and separate preserve specular
Unity-Technologies/Graphics pull request #1848
Opened 2020-09-11 15:54 UTC by eh-unity

### Checklist for PR maker
- [ ] Have you added a backport label (if needed)? For example, the `need-backport-*` label. After you backport the PR, the label changes to `backported-*`.
- [ ] Have you updated the changelog? Each package has a `CHANGELOG.md` file.
- [ ]  Have you updated or added the documentation for your PR? When you add a new feature, change a property name, or change the behavior of a feature, it's best practice to include related documentation changes in the same PR. If you do add documentation, make sure to add the relevant Graphics Docs team member as a reviewer of the PR. If you are not sure which person to add, see the [Docs team contacts sheet](https://docs.google.com/spreadsheets/d/1rgUWWgwLFEHIQ3Rz-LnK6PAKmbM49DZZ9al4hvnztOo/edit#gid=1058860420).
- [ ] Have you added a graphic test for your PR (if needed)? When you add a new feature, or discover a bug that tests don't cover, please add a graphic test.

---
### Purpose of this PR
Fix bug case 1260085 (use straight premultiply blend mode)
Separate preserve specular feature from premultiplied blend. Preserve specular is default.
Define URP blends more explicitly (match HDRP) by setting alpha channel blend too and allow pure blend modes.
Added a blend test case.
Added alpha effect to multiply by lerping to white.
Refactored BakedLit and Unlit implementation shader into their own .hlsl files.
Moved universal shader graph template to universal side.

---
### Testing status

**Manual Tests**: What did you do?
- [x] Opened test project + Run graphic tests locally
- [ ] Built a player
- [ ] Checked new UI names with UX convention
- [ ] Tested UI multi-edition + Undo/Redo + Prefab overrides + Alignment in Preset
- [ ] C# and shader warnings (supress shader cache to see them)
- [ ] Checked new resources path for the reloader (in developer mode, you have a button at end of resources that check the paths)
- Other: 

**Automated Tests**: What did you setup? (Add a screenshot or the reference image of the test please)

**Yamato**: (Select your branch):
https://yamato.prd.cds.internal.unity3d.com/jobs/902-Graphics

Any test projects to go with this to help reviewers?

---
### Comments to reviewers

- Did not account/fix blend modes in fog
- Did not update particle or 2D shaders
- Did not handle accumulate alpha (alpha channel blend with Src == Zero)
- No tests for blend modes & transparencies in fog
- No tests for blending modes with multiple overlapping transparent objects

2020-09-22 08:33 UTC, phi-lira commented
Assigning @ellioman instead of me as reviewer as I have too many PRs under review atm.

2020-10-05 09:31 UTC, Verasl requested changes
Seeing keyword changes but no material upgrader is worrying, a material upgrader will be nessesay here, to also add and set values for the new blend properties for alpha.

A material upgrader is a must.

2020-10-06 12:04 UTC, ellioman commented on com.unity.render-pipelines.universal/Editor/ShaderGUI/BaseShaderGUI.cs
> +            preserveSpecProp = FindProperty("_PreserveSpecular", properties, false);    // TODO: should be mandatory?
Create a discussion about this so we're not leaving a TODO for something that can be decided before this PR lands. :)

2020-10-06 12:11 UTC, ellioman commented on com.unity.render-pipelines.universal/Shaders/BakedLit.shader
> +            }*/
Delete.

2020-10-06 12:12 UTC, ellioman commented on com.unity.render-pipelines.universal/Shaders/BakedLit.shader
> +            }*/
Delete

2020-10-06 12:13 UTC, ellioman commented on com.unity.render-pipelines.universal/Shaders/BakedLitForwardPass.hlsl
> +}
I like moving this into a separate file like we do with the other shaders. 👍

2020-10-06 12:15 UTC, ellioman commented on com.unity.render-pipelines.universal/Shaders/Unlit.shader
> +            #include "Packages/com.unity.render-pipelines.universal/Shaders/UnlitForwardPass.hlsl"
👍

2020-10-09 10:25 UTC, fra-frassineti-unity requested changes
**NOT APPROVED**:
_"URP/Unlit"_ Shader does not compile on my machine after upgrading materials. For more info see the attached test doc

Version: 2021.1.0a1.495
Revision: trunk eff81b68729d
Built: Wed, 07 Oct 2020 11:32:35 GMT

**Test Doc**:
https://docs.google.com/document/d/1tBreRBnfM6R4cNIWqZS-ixZbO_u_FKHo29nFuNO-Dlw/edit?usp=sharing

2020-10-29 12:47 UTC, fra-frassineti-unity commented
Since tomorrow will be my last day at Unity, I re-added @Unity-Technologies/gfx-qa-foundation

2020-11-10 10:22 UTC, cinight commented
Talked to Erik. PR is not ready yet. Please add "gfx-qa-foundation" tag as reviewer again when this is ready for testing again.

2021-09-22 14:30 UTC, eh-unity commented
Stale. Ended up redoing the change. Link to PR in desc. Closing.

2021-09-22 14:30 UTC, closed without merging