Added Simple mode to Earth Preset for PBR Sky
Unity-Technologies/Graphics pull request #1866
Opened 2020-09-14 13:14 UTC by adrien-de-tocqueville

### Purpose of this PR
Why is this PR needed, what hard problem is it solving/fixing?

Simplifies the PBR Sky UI by adding a simple mode to the earth preset, that hides parameters not frequently used by artists.

![image](https://user-images.githubusercontent.com/61282776/93087565-09056880-f699-11ea-8c07-4705f5e12413.png)

Also fixed baking that used the 'Air Maximum Altitude' parameter in earth mode instead of the default value (as this parameter is hidden).

---
### Testing status

**Manual Tests**: What did you do?
- [ ] Opened test project + Run graphic tests locally
- [ ] Built a player
- [ ] Checked new UI names with UX convention
- [ ] Tested UI multi-edition + Undo/Redo + Prefab overrides + Alignment in Preset
- [ ] C# and shader warnings (supress shader cache to see them)
- [ ] Checked new resources path for the reloader (in developer mode, you have a button at end of resources that check the paths)
- Other: 

Tested that disabled parameters are not used by the computations.
Tested migration of profiles with the added parameter.

**Yamato**: (Select your branch):
https://yamato.prd.cds.internal.unity3d.com/jobs/902-Graphics/tree/HDRP%252Fpbr-sky-ui

---
### Comments to reviewers
Notes for the reviewers you have assigned.

2020-09-15 22:22 UTC, EvgeniiG commented
I am not convinced this is a good idea since it adds yet another not particularly obvious option.
All parameters have sensible defaults. Artists don't need to touch them if they don't want to.

2020-09-15 22:31 UTC, EvgeniiG commented
To make this section visible, set **Type** to **Earth (Advanced)** or **Custom Planet**.

| **Property**                  | **Description**                                              |
| ----------------------------- | ------------------------------------------------------------ |
| **Space Rotation**            | The orientation of space.                                    |
| **Space Emission Texture**    | Specifies a Texture that represents the emissive areas of space. |
| **Space Emission Multiplier** | A multiplier that HDRP applies to the **Space Emission Texture**. |


So you can't even create a starry sky in the Basic mode?

2020-09-15 23:14 UTC, sebastienlagarde commented
> I am not convinced this is a good idea since it adds yet another not particularly obvious option.
> All parameters have sensible defaults. Artists don't need to touch them if they don't want to.

The request come from our artist currently when we have done quick meeting about what should be improve in HDRP; 
they wanted to have simplify UX to avoid to touch parameter that shouldn't be touch :)

2020-09-16 07:42 UTC, adrien-de-tocqueville commented
After discussion with artist, i hidden the settings they never used, because even if they have good default values, the UI is just overwhelming.

> So you can't even create a starry sky in the Basic mode?

That's one of the things they don't use, partly because it needs a cubemap with a pretty high resolution to look good. Procedural  stars would be appreciated there.

2020-09-16 10:09 UTC, JordanL8 commented on com.unity.render-pipelines.high-definition/Documentation~/Override-Physically-Based-Sky.md
> +| **Type**                       | Indicates a preset HDRP uses to simplify the Inspector. Selecting Earth will only show properties suitable to simulate Earth. |
Indicates a preset HDRP uses to simplify the Inspector. If you select **Earth (Simple)** or **Earth (Advanced)**, the Inspector only shows properties suitable to simulate Earth.

2020-09-16 10:10 UTC, JordanL8 requested changes
Looks good, just one suggestion though.

2020-09-16 20:18 UTC, EvgeniiG commented
> After discussion with artist, i hidden the settings they never used, because even if they have good default values, the UI is just overwhelming.
> 
> > So you can't even create a starry sky in the Basic mode?
> 
> That's one of the things they don't use, partly because it needs a cubemap with a pretty high resolution to look good. Procedural stars would be appreciated there.

That's no different from any (HDRI) sky cubemap.

You can render to texture with a custom shader, but it is obviously going to be more expensive.

I will not do anything that is built-in.

2020-09-16 20:23 UTC, EvgeniiG commented
> > I am not convinced this is a good idea since it adds yet another not particularly obvious option.
> > All parameters have sensible defaults. Artists don't need to touch them if they don't want to.
> 
> The request come from our artists currently when we have done quick meeting about what should be improve in HDRP;
> they wanted to have simplify UX to avoid to touch parameter that shouldn't be touch :)

???

Just... Don't touch them? Where's the logic here? It's not like they don't fit on the screen.

The "Advanced Settings" concept we have in Unity is not helpful since it impedes discoverability, and I saw many people (including myself) struggle to find the parameters or hidden buttons while I was still at the office.

2020-09-17 12:12 UTC, sebastienlagarde commented
> Just... Don't touch them? Where's the logic here? It's not like they don't fit on the screen.

We have a UX team now, and our artists participate actively in discussion. It is not a personal opinion.

2020-09-17 12:17 UTC, sebastienlagarde commented
> > After discussion with artist, i hidden the settings they never used, because even if they have good default values, the UI is just overwhelming.
> > > So you can't even create a starry sky in the Basic mode?
> > 
> > 
> > That's one of the things they don't use, partly because it needs a cubemap with a pretty high resolution to look good. Procedural stars would be appreciated there.
> 
> That's no different from any (HDRI) sky cubemap.
> 
> You can render to texture with a custom shader, but it is obviously going to be more expensive.
> 
> I will not add anything that is built-in.

> That's no different from any (HDRI) sky cubemap.
yes, and we don't see start in night sky either.

> You can render to texture with a custom shader, but it is obviously going to be more expensive.
doesn't solve the resolution issue.

> I will not add anything that is built-in.
We will discuss with the artists. There seems to be a need to be able to get night sky with stars. We will evaluate the priority and put it or not in the roadmap if required. The team will handle the roadmap.

2020-09-17 18:39 UTC, EvgeniiG approved these changes

2020-09-25 11:08 UTC, sebastienlagarde approved these changes

2020-09-25 13:10 UTC, TomasKiniulis approved these changes
What I've tested:
- Updating 7.4.1 HDRP project with PBR sky ticket - PBR sky gets correctly updated to "Earth(Advanced)"
- Updating 7.4.1 HDRP project with PBR sky unticked- PBR sky gets correctly updated to "Custom Preset"
- Checked if variables are shared between presets

Nice change! Sea Level kind of stands out not taking the value from "Planet Center Position", but I guess making it shared would create even more confusion since X and Z values would not be shared between presets anyway

2020-09-25 16:48 UTC, merged