Hdrp/reflection probe baking api
Unity-Technologies/Graphics pull request #1894
Opened 2020-09-16 08:29 UTC by fredericv-unity3d

### Purpose of this PR
Fixing [case 1276360](https://fogbugz.unity3d.com/f/cases/1276360/).

`Lightmapping.BakeReflectionProbe` does not use the reflection system for rendering.

The appropriate fix is to update the C++ so it uses the reflection system for rendering and probe update, but it is a very expensive development.

A workaround is to create a similar function in C#.

I have implemented a similar function in `UnityEditor.Rendering.HighDefinition.LightmappingHDRP.BakeProbe` which render, write to a file the render and assign the probe.

Unfortunately, if the Editor is in PlayMode, the assignment will occur, but it will be lost when the Editor goes back into EditMode.

---
### Testing status

**Manual Tests**: What did you do?
- [ ] Opened test project + Run graphic tests locally
- [ ] Built a player
- [ ] Checked new UI names with UX convention
- [ ] Tested UI multi-edition + Undo/Redo + Prefab overrides + Alignment in Preset
- [ ] C# and shader warnings (supress shader cache to see them)
- [ ] Checked new resources path for the reloader (in developer mode, you have a button at end of resources that check the paths)
- Other: 

**Automated Tests**: What did you setup? (Add a screenshot or the reference image of the test please)

**Yamato**: (Select your branch):
https://yamato.prd.cds.internal.unity3d.com/jobs/902-Graphics

Any test projects to go with this to help reviewers?

---
### Comments to reviewers
Notes for the reviewers you have assigned.

2020-11-04 11:02 UTC, JordanL8 commented on com.unity.render-pipelines.high-definition/Editor/Lighting/LightmappingHDRP.cs
> +    ///     Lightmapping utilities for HDRP
Provides methods to help you with lightmapping in the High Definition Render Pipeline.

2020-11-04 11:03 UTC, JordanL8 commented on com.unity.render-pipelines.high-definition/Editor/Lighting/LightmappingHDRP.cs
> +        ///     Bake the <paramref name="probe" /> and updated its baked texture.
Bakes the <paramref name="probe" /> and updates its baked texture.

2020-11-04 11:06 UTC, JordanL8 commented on com.unity.render-pipelines.high-definition/Editor/Lighting/LightmappingHDRP.cs
> +        ///     <c>null</c> on success or the error that occured.
Returns <c>null</c> if successful. Otherwise, returns the error that occured.

2020-11-04 11:07 UTC, JordanL8 commented on com.unity.render-pipelines.high-definition/Editor/Lighting/LightmappingHDRP.cs
> +        ///     <see cref="HDAdditionalReflectionData" /> probes are currently supported.
This functional currently only supports <see cref="HDAdditionalReflectionData" /> probes.

2020-11-04 11:08 UTC, JordanL8 commented on com.unity.render-pipelines.high-definition/Editor/Lighting/LightmappingHDRP.cs
> +        ///     Options of <see cref="LightmappingHDRP.BakeProbe" /> function.
Represents options to use with the <see cref="LightmappingHDRP.BakeProbe" /> function.

2020-11-04 11:23 UTC, JordanL8 commented on com.unity.render-pipelines.high-definition/Editor/Lighting/LightmappingHDRP.cs
> +            ///     Determines the size of the baked texture.
Represents the size of a probe's baked texture.

2020-11-04 11:24 UTC, JordanL8 commented on com.unity.render-pipelines.high-definition/Editor/Lighting/LightmappingHDRP.cs
> +                ///     Which methods to use to evaluate the value.
Options for which method to use to determine the size of the baked texture.

2020-11-04 11:25 UTC, JordanL8 commented on com.unity.render-pipelines.high-definition/Editor/Lighting/LightmappingHDRP.cs
> +                    ///     Use the probe resolution as texture size.
Uses the probe's resolution as the size of the baked texture.

2020-11-04 11:28 UTC, JordanL8 commented on com.unity.render-pipelines.high-definition/Editor/Lighting/LightmappingHDRP.cs
> +                    ///     Use the value of <see cref="TextureSize.customValue" />.
Uses the value of \<see cref="TextureSize.customValue" /> as the size of the baked texture.

2020-11-04 11:28 UTC, JordanL8 commented on com.unity.render-pipelines.high-definition/Editor/Lighting/LightmappingHDRP.cs
> +                /// <returns>A <see cref="TextureSize" /> with default values.</returns>
A -> Returns a

2020-11-04 11:32 UTC, JordanL8 commented on com.unity.render-pipelines.high-definition/Editor/Lighting/LightmappingHDRP.cs
> +                ///     The mode to use.
The method to use to determine the size of the baked texture.

2020-11-04 11:32 UTC, JordanL8 commented on com.unity.render-pipelines.high-definition/Editor/Lighting/LightmappingHDRP.cs
> +                ///     Evaluate the texture size to use for baking.
Evaluates a probe and gets the texture size to use for baking.

2020-11-04 11:33 UTC, JordanL8 commented on com.unity.render-pipelines.high-definition/Editor/Lighting/LightmappingHDRP.cs
> +                /// <param name="probe">The probe that will be baked.</param>
The probe to get the texture size of.

2020-11-04 11:39 UTC, JordanL8 commented on com.unity.render-pipelines.high-definition/Editor/Lighting/LightmappingHDRP.cs
> +                /// <returns>The value of the texture size to use for the bake.</returns>
Returns the value of the texture size to use for the bake.

2020-11-04 12:12 UTC, JordanL8 commented on com.unity.render-pipelines.high-definition/Editor/Lighting/LightmappingHDRP.cs
> +            ///     Return a <see cref="BakeProbeOptions" /> with default values.
Creates and returns a \<see cref="BakeProbeOptions" /> with default values.

2020-11-04 12:12 UTC, JordanL8 requested changes
Rewrote a fair few bits

2020-11-05 07:57 UTC, fredericv-unity3d commented
@JordanL8 I updated the documentation according to your feedback, thanks for the review!

2020-11-05 10:28 UTC, JordanL8 approved these changes

2020-11-12 08:03 UTC, TomasKiniulis approved these changes
Went through API calls in editor and playmode. Works as expected.

Playmode:
- Mode.UseProbeResolution - cubemap is created, exiting out of playmode clears the bake
- Mode.CustomValue - cubemap is is created with and attached with custom provided resolution, exiting out of playmode clears the bake

Editor:
- Mode.UseProbeResolution - cubemap is created with probe resolution
- Mode.CustomValue - cubemap is is created with and attached with custom provided resolution

2020-11-24 13:54 UTC, sebastienlagarde approved these changes

2020-11-24 14:36 UTC, sebastienlagarde approved these changes

2020-11-24 14:36 UTC, merged