Restore node selection state after undoRedo.
Unity-Technologies/Graphics pull request #2064
Opened 2020-09-30 19:18 UTC by esmelusina

---
### Purpose of this PR
https://fogbugz.unity3d.com/f/cases/1280179/
Restore node selection state after undoRedo.

---
### Testing status
Manual Testing: Undo/Redo restores selection state for nodes.

2020-09-30 19:25 UTC, esmelusina commented on com.unity.shadergraph/Editor/Drawing/MaterialGraphEditWindow.cs
> +                }
Basic cache/restore selection step. The selection state gets manipulated in quite a few places as many of the 'changes' procedures are called in duplicity. This solution should probable live in MaterialGraphView instead, but it's execution flow for undo/redo needs a bit more work to support that.

2020-09-30 21:07 UTC, cdxntchou approved these changes

2020-10-07 20:54 UTC, LandonTownsendUnity requested changes
This test causes the following testrail manual test to fail
http://qatestrail.hq.unity3d.com/index.php?/cases/view/403570&group_by=cases:section_id&group_order=asc&group_id=76475
It's a pretty big failure (redo starts failing at a certain step) so definitely look into it.

2020-10-07 21:48 UTC, esmelusina commented
Based on testrails, this change would impact the undo/redo stack in unexpected ways. The issue is not resolvable without refactoring how either SG or GV currently handle Undo/Redo.

I am closing this PR and Resolved Postponing the FogBugz entry for this issue. It can be redressed for the GTF migration.

2020-10-07 21:48 UTC, closed without merging