Fix "ToSubgraph" with multiple outputs and allow passthrough
Unity-Technologies/Graphics pull request #2074
Opened 2020-10-01 21:31 UTC by elizabeth-legros

Had to fix how we create the subgraph when using the contextual "ToSubgraph" option in the MaterialGraphEditWindow. Depends on fixes to property copying from https://github.com/Unity-Technologies/Graphics/pull/1932/

for https://fogbugz.unity3d.com/f/cases/1256975/

redid repro steps and could not get bug to occur

2020-10-06 16:47 UTC, cdxntchou approved these changes

2020-10-21 20:53 UTC, LandonTownsendUnity approved these changes
Ran the following mindmap on subgraphs
![Subgraph smoke test](https://user-images.githubusercontent.com/52939698/96786173-bc523300-13a4-11eb-85d7-47c389c06741.png)
Only found 1 bug and that bug also reproduced on Master.
Approving.

2020-10-21 20:57 UTC, LandonTownsendUnity requested changes
Actually, "convert to subgraph" no longer detecting recursions is a regression, now that I checked. This should be fixed.

2020-10-21 21:01 UTC, LandonTownsendUnity approved these changes
Tested again to make sure I'm not wasting your time, and it does detect recursion with convert to subgraph. Must have made a mistake. Reapproving

2020-10-21 22:11 UTC, marctem approved these changes

2020-12-15 21:47 UTC, merged