Clone tree modifs
Unity-Technologies/Graphics pull request #2084
Opened 2020-10-02 20:45 UTC by simonduf

# **Please read;**
## **PR Workflow for the Graphics repository:**
* **All PRs must be opened as draft initially**
* Reviewers can be added while the PR is still in draft
* The PR can be marked as “Ready for Review” once the reviewers have confirmed that **no more changes are needed**
* Tests will start automatically after the PR is marked as “Ready for Review”
* **Do not use [skip ci]** - this can break some of our tooling
* Read the [Graphics repository & Yamato FAQ](http://go/graphics-yamato-faq).

### Checklist for PR maker
- [ ] Have you added a backport label (if needed)? For example, the `need-backport-*` label. After you backport the PR, the label changes to `backported-*`.
- [ ] Have you updated the changelog? Each package has a `CHANGELOG.md` file.
- [ ] Have you updated or added the documentation for your PR? When you add a new feature, change a property name, or change the behavior of a feature, it's best practice to include related documentation changes in the same PR. If you do add documentation, make sure to add the relevant Graphics Docs team member as a reviewer of the PR. If you are not sure which person to add, see the [Docs team contacts sheet](https://docs.google.com/spreadsheets/d/1rgUWWgwLFEHIQ3Rz-LnK6PAKmbM49DZZ9al4hvnztOo/edit#gid=1058860420).
- [ ] Have you added a graphic test for your PR (if needed)? When you add a new feature, or discover a bug that tests don't cover, please add a graphic test.

---
### Purpose of this PR
Why is this PR needed, what hard problem is it solving/fixing?
This PR prepare the repo for a change in trunk:
https://ono.unity3d.com/unity/unity/pull-request/113509/_/editor/DeprecateCloneTree#

---
### Testing status
I currently opened the shadergraph project and ran the tests

I'm looking for feedback on what to actually test. 

---
### Comments to reviewers

Don't hesitate to reach for any questions.

2020-10-05 08:29 UTC, iTris666 requested changes

2020-10-05 08:29 UTC, iTris666 commented on com.unity.visualeffectgraph/Editor/GraphView/VFXComponentBoard.cs
> +                            this.hierarchy.Add(ve.hierarchy[0]);
should not be this but m_EventsContainer.

2020-10-05 08:29 UTC, iTris666 commented on com.unity.visualeffectgraph/Editor/GraphView/VFXComponentBoard.cs
> +            }
should not be this but contentContainer

2020-10-08 14:16 UTC, iTris666 approved these changes

2020-11-18 17:32 UTC, Nightmask3 reviewed
Just pinging this review thread again to check in, how's the testing going?

2022-07-04 14:36 UTC, closed without merging