[10.x.x] Added clamp logic to XR MSAA setter
Unity-Technologies/Graphics pull request #2135
Opened 2020-10-08 17:37 UTC by thomas-zeng

### Checklist for PR maker
- [ ] Have you added a backport label (if needed)? For example, the `need-backport-*` label. After you backport the PR, the label changes to `backported-*`.
- [ ] Have you updated the changelog? Each package has a `CHANGELOG.md` file.
- [ ] Have you updated or added the documentation for your PR? When you add a new feature, change a property name, or change the behavior of a feature, it's best practice to include related documentation changes in the same PR. If you do add documentation, make sure to add the relevant Graphics Docs team member as a reviewer of the PR. If you are not sure which person to add, see the [Docs team contacts sheet](https://docs.google.com/spreadsheets/d/1rgUWWgwLFEHIQ3Rz-LnK6PAKmbM49DZZ9al4hvnztOo/edit#gid=1058860420).
- [ ] Have you added a graphic test for your PR (if needed)? When you add a new feature, or discover a bug that tests don't cover, please add a graphic test.

---
### Purpose of this PR
Added code to handle the case where user sets invalid MSAA value such as 0.
- Fogbugz case https://fogbugz.unity3d.com/f/cases/1283182/

---
### Testing status
Describe what manual/automated tests were performed for this PR

---
### Comments to reviewers
- None

2020-10-08 18:39 UTC, fabien-unity approved these changes

2020-10-13 12:32 UTC, pbbastian requested changes
Code looks good, please add a change log entry :)

2020-10-23 23:45 UTC, amaestas13 approved these changes
Tested on 

Version: 2020.2.0b9.3339
Revision: 2020.2/staging b461f3fccdfa
Built: Thu, 15 Oct 2020 21:36:12 GMT

Tested quest and quest 2 standalone and link.

2020-10-27 07:48 UTC, pbbastian approved these changes

2020-10-27 13:31 UTC, phi-lira commented
Closing, merged in : #2390

2020-10-27 13:31 UTC, closed without merging