Fixes to the renderer list
Unity-Technologies/Graphics pull request #2147
Opened 2020-10-09 11:48 UTC by martint-unity

---
### Purpose of this PR
Fixes for this Bug
https://fogbugz.unity3d.com/f/cases/1281007/

made it reordereable,
Update the default renderer index properly when reordering
Able to delete entries and update indexes properly

![renderer_list_fixes](https://user-images.githubusercontent.com/35328557/95579536-20d0d200-0a36-11eb-90dc-03d449a5bfbf.gif)

2020-10-21 13:40 UTC, ellioman approved these changes

2020-11-03 09:22 UTC, Verasl requested changes
Fix the default button overlap and you get my vote 👍 
![image](https://user-images.githubusercontent.com/9811576/97968062-704cb880-1dbe-11eb-9d94-8d0486b432a4.png)

2020-11-04 14:59 UTC, Verasl approved these changes
LGTM

2020-11-16 09:44 UTC, erikabar approved these changes
no issues found, tested OSX and Windows.

2020-11-19 09:22 UTC, ellioman approved these changes

2020-11-26 11:01 UTC, phi-lira approved these changes
LGTM for fixing the issue. However we should discuss possibility of referencing renderers in GUIds in the camera instead of indices as there are multiple problems with this (what happens if you switch a pipeline asset that has different default renderers / indices?)

2020-11-26 11:17 UTC, martint-unity commented on com.unity.render-pipelines.universal/Runtime/UniversalAdditionalCameraData.cs
> +        internal new Camera camera
In the log
Debug.LogWarning(
                        $"Renderer at <b>index {m_RendererIndex.ToString()}</b> is missing for camera <b>**{camera.name}**</b>

2020-11-26 11:17 UTC, martint-unity commented on com.unity.render-pipelines.universal/Runtime/Data/UniversalRenderPipelineAsset.cs
> +        const int k_MaxAssetVersion = 6;
Yes true, that is my other PR. Can remove this.

2020-11-26 12:09 UTC, martint-unity commented on com.unity.render-pipelines.universal/Runtime/UniversalAdditionalCameraData.cs
> +            get => gameObject.GetComponent<Camera>();
Done.

2020-11-26 12:09 UTC, martint-unity commented on com.unity.render-pipelines.universal/Runtime/UniversalAdditionalCameraData.cs
> +                if (!UniversalRenderPipeline.asset.ValidateRendererData(m_RendererIndex))
Done

2020-11-27 08:06 UTC, Verasl approved these changes
LGTM

2020-11-27 10:27 UTC, erikabar approved these changes
Tested with URP template (reordering renderers, removing, undo, redo, setting default) and UniversalRenderingExamples project

2020-11-27 10:44 UTC, ellioman commented
Yamato issues on HDRP unrelated to this PR.

2020-11-27 10:45 UTC, merged