Clarified LayeredLit UI & doc
Unity-Technologies/Graphics pull request #2244
Opened 2020-10-15 15:54 UTC by adrien-de-tocqueville

### Purpose of this PR

Fix for https://fogbugz.unity3d.com/f/cases/1284403/

Added an message box when the selected material is not a Lit or LitTessellation material
![image](https://user-images.githubusercontent.com/61282776/96154332-f6d44f80-0f0e-11eb-96f0-60ff6a2411d5.png)

Updated the [Material To Copy ](https://docs.unity3d.com/Packages/com.unity.render-pipelines.high-definition@10.0/manual/Layered-Lit-Shader.html#material-to-copy) section of the doc
Updates the screenshot and adds a section about shader graph materials

![new doc](https://user-images.githubusercontent.com/61282776/96154227-df956200-0f0e-11eb-9024-507e33f51044.png)

2020-10-15 15:56 UTC, adrien-de-tocqueville commented
Also I think this section of the doc about vertex animation is outdated. Should I remove it ?
https://docs.unity3d.com/Packages/com.unity.render-pipelines.high-definition@10.0/manual/Layered-Lit-Shader.html#vertex-animation

2020-10-15 16:00 UTC, JordanL8 commented on com.unity.render-pipelines.high-definition/Documentation~/Layered-Lit-Shader.md
> +If the referenced Material gets modified, you can synchronize the properties by pressing the **Reset** button. This copies all of the properties from the referenced Material into the relevant Layered
If you modify the referenced Material in any way, you can synchronize the properties by pressing the **Reset** button. This copies all of the properties from the referenced Material into the relevant Layered Material layer.

2020-10-15 16:00 UTC, JordanL8 commented on com.unity.render-pipelines.high-definition/Documentation~/Layered-Lit-Shader.md
> +If you choose to use a Material made from a Shader Graph as a **Layer Material**, make sure the Reference of the properties match the name of the corresponding properties in the LayeredLit Material.
If you assign a Material made from a Shader Graph as a **Layer Material**, make sure the **Reference** of the properties matches the name of the corresponding properties in the LayeredLit Material.

2020-10-15 16:00 UTC, JordanL8 commented on com.unity.render-pipelines.high-definition/Documentation~/Layered-Lit-Shader.md
> +You can see an example with the **Base Map** in the screenshot below.
For an example of what this means, see **_BaseColorMap** in the screenshot below:

2020-10-15 16:02 UTC, JordanL8 requested changes
Added a few comments for the docs

2020-10-15 16:07 UTC, adrien-de-tocqueville commented
Addressed the requested changes

2020-10-22 10:42 UTC, sebastienlagarde approved these changes

2020-10-22 10:44 UTC, merged