Improvements to the DXR Wizard
Unity-Technologies/Graphics pull request #2295
Opened 2020-10-21 08:55 UTC by anisunity

On user request, we decided to add new checks and additional informaiton in the DXR wizard. Now the DXR wizard displays a warning message for unchecked feature in the HDRP asset and and an info message for the corresponding an unchecked default frame setting. The wizard also displays the name of the target asset that may require modification.

![image](https://user-images.githubusercontent.com/42026998/96697098-cd427a80-138b-11eb-9af6-03acc0313882.png)

Testing status
Clicked on all the asset features and default camera frame settings and made sure the right messages popped when they are checked/unchecked.

2020-10-21 09:33 UTC, JordanL8 commented on com.unity.render-pipelines.high-definition/Editor/Wizard/HDWizard.Window.cs
> +                error: "Screen Space Shadows are disabled in the current HDRP asset. You will not be able to toggle ray traced shadows on the lights in your scene. You can enable the feature in the H
Screen Space Shadows are disabled in the current HDRP Asset which means you cannot enable ray-traced shadows for lights in your scene. To enable this feature, open your HDRP Asset, go to **Lighting > Shadows**, and enable **Screen Space Shadows**.

2020-10-21 09:35 UTC, JordanL8 commented on com.unity.render-pipelines.high-definition/Editor/Wizard/HDWizard.Window.cs
> +                error: "Screen Space Reflection is disabled in the current HDRP asset. You will not be able to toggle ray traced reflections though your volume components. You can enable the feature
Screen Space Reflection is disabled in the current HDRP Asset which means you cannot enable ray-traced reflections in Volume components. To enable this feature, open your HDRP Asset, go to **Lighting > Reflections**, and enable **Screen Space Reflections**.

2020-10-21 09:36 UTC, JordanL8 commented on com.unity.render-pipelines.high-definition/Editor/Wizard/HDWizard.Window.cs
> +                error: "Transparent Screen Space Reflection is disabled in the current HDRP asset. You will not be able to toggle ray traced reflections on transparent objects though your volume comp
Transparent Screen Space Reflection is disabled in the current HDRP Asset which means you cannot enable ray-traced reflections for transparent GameObjects from Volume components. To enable this feature, open your HDRP Asset, go to **Lighting > Reflections**, and enable **Transparent Screen Space Reflections**.

2020-10-21 09:38 UTC, JordanL8 commented on com.unity.render-pipelines.high-definition/Editor/Wizard/HDWizard.Window.cs
> +                error: "Screen Space Global Illumination is disabled in the current HDRP asset. You will not be able to toggle ray global illumination though your volume components. You can enable th
**Screen Space Global Illumination** is disabled in the current HDRP asset which means you cannot enable ray-traced global illumination in Volume components. To enable this feature, open your HDRP Asset, go to **Lighting** and enable **Screen Space Global Illumination**.

2020-10-21 09:50 UTC, JordanL8 commented on com.unity.render-pipelines.high-definition/Editor/Wizard/HDWizard.Window.cs
> +                error: "Screen Space Shadows are disabled in the default Camera Frame setting. You can enable the feature in Project Settings > HDRP Default Settings > Frame Settings > Default Frame
Screen Space Shadows are disabled in the default Camera Frame Settings. This means Cameras that use these Frame Settings do not render ray-traced shadows. To enable this feature, go to **Project Settings > HDRP Default Settings > Frame Settings > Default Frame Settings For Camera > Lighting** and enable **Screen Space Shadows**.

2020-10-21 09:51 UTC, JordanL8 commented on com.unity.render-pipelines.high-definition/Editor/Wizard/HDWizard.Window.cs
> +                error: "Screen Space Reflection is disabled in the default Camera Frame setting. You can enable the feature in Project Settings > HDRP Default Settings > Frame Settings > Default Fram
Screen Space Reflection is disabled in the default Camera Frame Settings. This means Cameras that use these Frame Settings do not render ray-traced reflections. To enable this feature, go to **Project Settings > HDRP Default Settings > Frame Settings > Default Frame Settings For Camera > Lighting** and enable **Screen Space Reflections**.

2020-10-21 09:52 UTC, JordanL8 commented on com.unity.render-pipelines.high-definition/Editor/Wizard/HDWizard.Window.cs
> +                error: "Transparent Screen Space Reflection is disabled in the default Camera Frame setting. You can enable the feature in Project Settings > HDRP Default Settings > Frame Settings >
Transparent Screen Space Reflection is disabled in the default Camera Frame Settings. This means Cameras that use these Frame Settings do not render ray-traced reflections for transparent GameObjects. To enable this feature, go to Project Settings > HDRP Default Settings > Frame Settings > Default Frame Settings For Camera > Lighting and enable On Transparent.

2020-10-21 09:55 UTC, JordanL8 commented on com.unity.render-pipelines.high-definition/Editor/Wizard/HDWizard.Window.cs
> +                error: "Screen Space Global Illumination is disabledin the default Camera Frame setting. You can enable the feature in Project Settings > HDRP Default Settings > Frame Settings > Defa
Screen Space Global Illumination is disabled in the default Camera Frame Settings. This means Cameras that use these Frame Settings do not render ray-traced global illumination. To enable this feature, go to **Project Settings > HDRP Default Settings > Frame Settings > Default Frame Settings For Camera > Lighting** and enable **Screen Space Global Illumination**.

2020-10-21 09:55 UTC, JordanL8 requested changes
Reworded a few bits.

2020-10-21 14:06 UTC, anisunity commented
corrections done

2020-10-23 09:22 UTC, RSlysz approved these changes
lgtm

2020-10-23 09:54 UTC, JordanL8 approved these changes

2020-10-23 09:56 UTC, merged