Fix SSR warning & Transparent discrepancy with Non-RenderGraph
Unity-Technologies/Graphics pull request #2410
Opened 2020-10-28 00:31 UTC by skhiat

# **Please read;**
## **PR Workflow for the Graphics repository:**
* **All PRs must be opened as draft initially**
* Reviewers can be added while the PR is still in draft
* The PR can be marked as “Ready for Review” once the reviewers have confirmed that **no more changes are needed**
* Tests will start automatically after the PR is marked as “Ready for Review”
* **Do not use [skip ci]** - this can break some of our tooling
* Read the [Graphics repository & Yamato FAQ](http://go/graphics-yamato-faq).

### Checklist for PR maker
- [ ] Have you added a backport label (if needed)? For example, the `need-backport-*` label. After you backport the PR, the label changes to `backported-*`.
- [ ] Have you updated the changelog? Each package has a `CHANGELOG.md` file.
- [ ] Have you updated or added the documentation for your PR? When you add a new feature, change a property name, or change the behavior of a feature, it's best practice to include related documentation changes in the same PR. If you do add documentation, make sure to add the relevant Graphics Docs team member as a reviewer of the PR. If you are not sure which person to add, see the [Docs team contacts sheet](https://docs.google.com/spreadsheets/d/1rgUWWgwLFEHIQ3Rz-LnK6PAKmbM49DZZ9al4hvnztOo/edit#gid=1058860420).
- [ ] Have you added a graphic test for your PR (if needed)? When you add a new feature, or discover a bug that tests don't cover, please add a graphic test.

---
### Purpose of this PR
Why is this PR needed, what hard problem is it solving/fixing?

---
### Testing status
Describe what manual/automated tests were performed for this PR

---
### Comments to reviewers
Notes for the reviewers you have assigned.

2020-10-28 00:46 UTC, sebastienlagarde approved these changes

2020-10-28 11:27 UTC, JMargevics requested changes
Please fix the description: 

- Remove default text
- Add what PR is about (even if the title is descriptive enough)
- Add what's tested and if needed a section "For reviewers" with any specifics

Also, please don't forget about changelog. 

Many thanks!

2020-10-28 21:12 UTC, sebastienlagarde approved these changes

2020-10-28 21:13 UTC, sebastienlagarde commented
For QA: I need to merge this PR as it fix Yamato. Our Yamato is currently red for non render graph and we need to fix it. Please do a follow up with Soufiane about it.

2020-10-28 21:14 UTC, merged

2020-11-06 13:18 UTC, JMargevics reviewed
Okay tried deleting cache and local library folder, disabling Render Graph from Debug menu and opening 2701_TransparentSSR scene on both Win Vulkan and Metal. In both cases no warnings or other visual regressions.