[10.3] [ShaderGraph] [bugfix 1283902] Pull textures into Export Package even if not sampled by shader
Unity-Technologies/Graphics pull request #2466
Opened 2020-10-29 20:10 UTC by cdxntchou

# **Please read;**
## **PR Workflow for the Graphics repository:**
* **All PRs must be opened as draft initially**
* Reviewers can be added while the PR is still in draft
* The PR can be marked as “Ready for Review” once the reviewers have confirmed that **no more changes are needed**
* Tests will start automatically after the PR is marked as “Ready for Review”
* **Do not use [skip ci]** - this can break some of our tooling
* Read the [Graphics repository & Yamato FAQ](http://go/graphics-yamato-faq).

### Checklist for PR maker
- [ ] Have you added a backport label (if needed)? For example, the `need-backport-*` label. After you backport the PR, the label changes to `backported-*`.
- [ ] Have you updated the changelog? Each package has a `CHANGELOG.md` file.
- [ ] Have you updated or added the documentation for your PR? When you add a new feature, change a property name, or change the behavior of a feature, it's best practice to include related documentation changes in the same PR. If you do add documentation, make sure to add the relevant Graphics Docs team member as a reviewer of the PR. If you are not sure which person to add, see the [Docs team contacts sheet](https://docs.google.com/spreadsheets/d/1rgUWWgwLFEHIQ3Rz-LnK6PAKmbM49DZZ9al4hvnztOo/edit#gid=1058860420).
- [ ] Have you added a graphic test for your PR (if needed)? When you add a new feature, or discover a bug that tests don't cover, please add a graphic test.

---
### Purpose of this PR
Why is this PR needed, what hard problem is it solving/fixing?

---
### Testing status
Describe what manual/automated tests were performed for this PR

---
### Comments to reviewers
Notes for the reviewers you have assigned.

2020-11-02 20:37 UTC, LandonTownsendUnity commented
Could you test the following and take images showing they result in the texture being part of the exported package:
Texture2D, Texture2DArray, Texture3D, Cubemap, and Virtual Texture properties
Texture2D, Texture2DArray, Texture3D and Cubemap inline nodes
Inline texture inputs of Sample Texture 2D, Sample Texture3D, Sample Cubemap, Sample Texture 2D Array (not connected to the master stack)

2020-11-03 22:10 UTC, LandonTownsendUnity approved these changes
I had some free time so I ran the manual tests for you.
![image](https://user-images.githubusercontent.com/52939698/98045944-270c6100-1dde-11eb-990f-d128965de564.png)
![image](https://user-images.githubusercontent.com/52939698/98045971-34295000-1dde-11eb-9753-0f1a317fcf21.png)
![image](https://user-images.githubusercontent.com/52939698/98046065-58852c80-1dde-11eb-99d9-9542c4041052.png)
Approved.

2020-11-04 23:03 UTC, marctem requested changes
All good except for changelog.

2020-11-04 23:03 UTC, marctem commented on com.unity.shadergraph/CHANGELOG.md
> +- All textures in a ShaderGraph, even those not used, will now be pulled into an Exported Package [1283902]
Changelog will need to move to new 10.3 section once 10.2 package is complete and we can merge this.

2020-11-06 00:07 UTC, marctem approved these changes

2020-11-09 06:51 UTC, ellioman commented
Remember to include the warning fixes you made in #2549 in this PR

2020-11-19 01:31 UTC, merged