[ShaderGraph] [Backport 10.3] Fix texture associated state (samplerstate, texellsize) for subgraphs, CFNs
Unity-Technologies/Graphics pull request #2577
Opened 2020-11-10 02:59 UTC by cdxntchou

# **Please read;**
## **PR Workflow for the Graphics repository:**
* **All PRs must be opened as draft initially**
* Reviewers can be added while the PR is still in draft
* The PR can be marked as “Ready for Review” once the reviewers have confirmed that **no more changes are needed**
* Tests will start automatically after the PR is marked as “Ready for Review”
* **Do not use [skip ci]** - this can break some of our tooling
* Read the [Graphics repository & Yamato FAQ](http://go/graphics-yamato-faq).

### Checklist for PR maker
- [ ] Have you added a backport label (if needed)? For example, the `need-backport-*` label. After you backport the PR, the label changes to `backported-*`.
- [ ] Have you updated the changelog? Each package has a `CHANGELOG.md` file.
- [ ] Have you updated or added the documentation for your PR? When you add a new feature, change a property name, or change the behavior of a feature, it's best practice to include related documentation changes in the same PR. If you do add documentation, make sure to add the relevant Graphics Docs team member as a reviewer of the PR. If you are not sure which person to add, see the [Docs team contacts sheet](https://docs.google.com/spreadsheets/d/1rgUWWgwLFEHIQ3Rz-LnK6PAKmbM49DZZ9al4hvnztOo/edit#gid=1058860420).
- [ ] Have you added a graphic test for your PR (if needed)? When you add a new feature, or discover a bug that tests don't cover, please add a graphic test.

---
### Purpose of this PR
Why is this PR needed, what hard problem is it solving/fixing?

---
### Testing status
Describe what manual/automated tests were performed for this PR

---
### Comments to reviewers
Notes for the reviewers you have assigned.

2020-11-14 01:17 UTC, zeroyao approved these changes
Thank you Chris!

2020-11-16 20:32 UTC, LandonTownsendUnity approved these changes
Things tested:
Inline on subgraph input 
![image](https://user-images.githubusercontent.com/52939698/99303325-93875700-2805-11eb-807d-f099f0f985d0.png)
subgraph property passthrough
![image](https://user-images.githubusercontent.com/52939698/99303354-a26e0980-2805-11eb-84a0-ac18315c23ee.png)
Inline to subgraph output
![image](https://user-images.githubusercontent.com/52939698/99303396-b154bc00-2805-11eb-9384-1d7ac3dabbe4.png)
inline node to subgraph output
![image](https://user-images.githubusercontent.com/52939698/99303445-c3cef580-2805-11eb-9a76-7ca2b45ceeb7.png)
"none" texture output from subgraph (make sure there's no errors)

All of the above for:
Texture2D
Texture2DArray
Texture3D
Cubemap

2020-11-20 10:53 UTC, pbbastian approved these changes
Lovely change! 👍 Only 1 minor change request

2020-11-20 11:05 UTC, pbbastian requested changes
missed some minor things :)

2020-11-20 11:05 UTC, pbbastian commented on com.unity.shadergraph/Editor/Data/Nodes/Utility/CustomFunctionNode.cs
> +                            sb.Append(".tex");
I really think this should have braces

2020-11-23 20:02 UTC, cdxntchou commented on com.unity.shadergraph/Editor/Data/Graphs/CubemapMaterialSlot.cs
> +        internal bool m_BareResource = false;
Fixed in new changeset

2020-11-23 20:13 UTC, cdxntchou commented on com.unity.shadergraph/Editor/Data/Nodes/Utility/CustomFunctionNode.cs
> +                }
Yes, fixed in the new changeset -- For bare outputs I initialize the default output state above in the loop that declares the output variables.

2020-11-23 20:13 UTC, cdxntchou commented on com.unity.shadergraph/Editor/Data/Nodes/Utility/CustomFunctionNode.cs
> +                            sb.Append(".tex");
Fixed in new changeset

2020-11-24 08:17 UTC, pbbastian approved these changes

2020-11-24 10:08 UTC, alelievr approved these changes
LGTM (for HDRP)

2020-11-24 17:17 UTC, sebastienlagarde approved these changes

2020-11-25 16:59 UTC, elizabeth-legros approved these changes

2020-11-25 20:10 UTC, elizabeth-legros approved these changes

2020-11-25 22:01 UTC, merged

2020-11-26 14:56 UTC, VladNeykov reviewed
A bit late to the party, but it's all good on the VFX side.
Ran FTP project, checked a VFX sample (Magic book) using shadergraph, and did a few manual tests.