Added the possibility to disable distance based roughness for reflection probes.
Unity-Technologies/Graphics pull request #2641
Opened 2020-11-16 12:57 UTC by anisunity

Recently we changed the behavior of the reflection probes to have an approximation for the distance based BRDF integration (that we call distance based roughness). While the feature increases the image quality, it requires the user to be able to set up a proxy that matches roughly the geometry. That is not always possible (exteriors, oddly shapes rooms, etc.). So we added a toggle on the reflection probe itself to be able to disable the feature.
The checkbox is on by default.

Testing status
Ran the HDRP tests locally they were all green.
Compared with and without the checkbox and the behavior is the same as before the feature was added.

2020-11-16 13:03 UTC, TomasKiniulis commented
Hey @anisunity! Anything in particular that QA should pay attention to testing this?

2020-11-16 13:15 UTC, anisunity commented
I don't think so @TomasKiniulis, it is a quite simple PR (only couple lines)

2020-11-16 17:08 UTC, iM0ve requested changes
The feature is working but I have a few UX suggestions.

1) Since it only works when Proxies are used. Gray the Distance Based Roughness when Proxy is set to None and Use Influence Volume As Proxy Volume is unchecked.
2) Move the feature into Projection Settings if it makes sense.
3) Adjust the tooltip so it clearly states that will only have a positive result if Proxy closely matches the environment 
@JordanL8 tooltip suggestion:
"When enabled, HDRP uses the assigned Proxy Volume to calculate distance based roughness for reflections. This produces more physically-accurate results if the Proxy Volume closely matches the environment"

![image](https://user-images.githubusercontent.com/36502659/99284564-14167980-283f-11eb-936b-a3ceff34e510.png)

2020-11-17 11:00 UTC, JordanL8 commented on com.unity.render-pipelines.high-definition/Runtime/Utilities/ProbeSettings.cs
> +        /// <summary>Defines if the reflection probe should support the distance based roughness.</summary>
Indicates whether the ReflectionProbe supports distance-based roughness.

2020-11-17 11:04 UTC, JordanL8 requested changes
Can you add the small API summary change as well as the tooltip change Motiejus mentioned

2020-11-20 15:23 UTC, anisunity commented
Did the review corrections and merged master and relaunching the tests

2020-11-23 13:34 UTC, iM0ve approved these changes
Issue 1 - will be solved later since its a more complicated UX matter. Tracked in fogbugz
Issue 2 - Fixed
Issue 3 - Fixed

![3Nk4sR4YLX](https://user-images.githubusercontent.com/36502659/99967950-2f363b80-2da1-11eb-9e39-6eee64bfccfd.gif)

2020-11-30 21:34 UTC, sebastienlagarde approved these changes

2020-11-30 21:34 UTC, sebastienlagarde commented
Doc correction is done. Merging

2020-11-30 21:34 UTC, merged