[HDRP][Compositor] Fix edge cases when cameras are missing or deleted
Unity-Technologies/Graphics pull request #2700
Opened 2020-11-20 15:31 UTC by pmavridis

### Purpose of this PR
https://fogbugz.unity3d.com/f/cases/1292548/
https://fogbugz.unity3d.com/f/cases/1292549/
There were some issues (reported by @TomasKiniulis) when enabling the compositor in a scene without cameras, or adding image layers when all cameras where deleted. I have also fixed some issues/warnings when deleting the output camera of the compositor.

---
### Testing status
- Compositor test is green.
- The issues described in the fogbugz cases do not repro anymore
- Deleting the existing output camera of the compositor and adding a new one works as expected

2020-11-20 16:54 UTC, TomasKiniulis requested changes
After running through the first bugfix(1292548) repro steps I seem to be getting the following:
`NullReferenceException
UnityEngine.Component.GetComponent[T] () (at <58d066ab37904d8b86bee6c7e7765a94>:0)
UnityEngine.Rendering.HighDefinition.Compositor.CompositorLayer.SetupClearColor ()`

![k5THqGuA06](https://user-images.githubusercontent.com/50582134/99826761-77671b00-2b61-11eb-8243-b6d26dd47547.gif)

2020-11-20 18:18 UTC, pmavridis commented
Good catch, I did not try to disable the layer in my tests... it should be fine now. If you find anything else let me know.

2020-11-23 08:22 UTC, TomasKiniulis commented
> Good catch, I did not try to disable the layer in my tests... it should be fine now. If you find anything else let me know.

Thanks! Seems to be good now

2020-11-23 08:22 UTC, TomasKiniulis approved these changes

2020-11-23 12:29 UTC, sebastienlagarde approved these changes

2020-11-23 12:30 UTC, merged