Fixed an issue where Universal Render Pipeline with disabled antiAlia…
Unity-Technologies/Graphics pull request #2744
Opened 2020-11-25 08:13 UTC by lukaschod

### Purpose of this PR
Backport #2526.

### Testing status
 Tested that issue no longer reproduces in case.
 Checked the code if XR needs fixing. Apperently they are handling it in native side
void XRDisplaySubsystem::SetMSAALevel(int level)
{
    level = (level > 0) ? level : 1;
    m_TextureManager.SetMSAALevel(level);
}
 Test if QualitySettings.antiAliasing is correctly update with URP.

---
### Comments to reviewers
Notes for the reviewers you have assigned.

2020-11-25 09:03 UTC, martint-unity approved these changes

2021-01-19 08:31 UTC, phi-lira requested changes

2021-01-19 08:31 UTC, phi-lira commented on com.unity.render-pipelines.universal/CHANGELOG.md
> +- Fixed an issue where Universal Render Pipeline with disabled antiAliasing was overwriting QualitySettings.asset on frequent cases. [case 1219159](https://issuetracker.unity3d.com/issues/urp-quality
Merge error? This seems duplicate from above and why removing the other entries?

2021-01-19 09:02 UTC, phi-lira approved these changes

2021-01-19 09:53 UTC, phi-lira approved these changes

2021-01-19 09:53 UTC, merged