[Yamato] Refactor ABV
Unity-Technologies/Graphics pull request #2843
Opened 2020-12-04 13:12 UTC by sophiaaar

# **Please read;**
## **PR Workflow for the Graphics repository:**
* **All PRs must be opened as draft initially**
* Reviewers can be added while the PR is still in draft
* The PR can be marked as “Ready for Review” once the reviewers have confirmed that **no more changes are needed**
* Tests will start automatically after the PR is marked as “Ready for Review”
* **Do not use [skip ci]** - this can break some of our tooling
* Read the [Graphics repository & Yamato FAQ](http://go/graphics-yamato-faq).

### Checklist for PR maker
- [ ] Have you added a backport label (if needed)? For example, the `need-backport-*` label. After you backport the PR, the label changes to `backported-*`.
- [ ] Have you updated the changelog? Each package has a `CHANGELOG.md` file.
- [ ] Have you updated or added the documentation for your PR? When you add a new feature, change a property name, or change the behavior of a feature, it's best practice to include related documentation changes in the same PR. If you do add documentation, make sure to add the relevant Graphics Docs team member as a reviewer of the PR. If you are not sure which person to add, see the [Docs team contacts sheet](https://docs.google.com/spreadsheets/d/1rgUWWgwLFEHIQ3Rz-LnK6PAKmbM49DZZ9al4hvnztOo/edit#gid=1058860420).
- [ ] Have you added a graphic test for your PR (if needed)? When you add a new feature, or discover a bug that tests don't cover, please add a graphic test.

---
### Purpose of this PR
Why is this PR needed, what hard problem is it solving/fixing?

---
### Testing status
Describe what manual/automated tests were performed for this PR

---
### Comments to reviewers
Notes for the reviewers you have assigned.

2020-12-08 15:56 UTC, kivistikliis commented on .yamato/ruamel/jobs/projects/yml_project.py
> +        if metafile["expression_trigger"]["expression"] != "":
This is a small thing so no worries if stays as is, but could 16-18 also be skipped, because would it evaluate to whatever the value is anyways?

2020-12-08 15:57 UTC, kivistikliis commented on .yamato/ruamel/jobs/shared/namer.py
> +def project_filepath_nightly(project_name):
This may be not needed anymore?

2020-12-08 15:58 UTC, kivistikliis approved these changes

2020-12-08 15:58 UTC, sophiaaar commented on .yamato/ruamel/jobs/shared/namer.py
> +def project_filepath_nightly(project_name):
good spot, thanks

2020-12-08 17:02 UTC, theo-pnv requested changes
Really impressive work, this will help so much, thanks! 👏

Last question, should [this file](https://github.com/Unity-Technologies/Graphics/blob/yamato/refactor-abv/CONTRIBUTING) be removed now that we have an updated contributing guide?

2020-12-08 17:11 UTC, sophiaaar commented on .yamato/all-hdrp_dxr.yml
> +      -  path: .yamato/hdrp_dxr-win-dx12.yml#HDRP_DXR_Win_DX12_playmode_NonRenderGraph_mono_Linear_trunk
probably, i'll fix

2020-12-08 17:13 UTC, sophiaaar commented on .yamato/all-hdrp_dxr.yml
> +Nightly_HDRP_DXR_trunk:
checking

2020-12-08 17:14 UTC, sophiaaar commented on .yamato/config/hdrp_dxr.metafile
> +  - type: playmode
thank you!

2020-12-08 17:15 UTC, sophiaaar commented on .yamato/all-hdrp_dxr.yml
> +Nightly_HDRP_DXR_trunk:
it was being referenced via a single job, so i changed it to reference the whole pipeline

2020-12-08 17:31 UTC, theo-pnv commented on .yamato/all-hdrp_dxr.yml
> +Nightly_HDRP_DXR_trunk:
Oh I didn't see. Thanks.
I still don't understand where this job is being called. The `PR_HDRP_DXR_trunk` line 10 is called by `PR_HDRP_trunk` in all-hdrp.yml, and the `PR_HDRP_trunk` job is called by `Nightly_HDRP_trunk`; but this means that all the "extra" jobs we add in `Nightly_HDRP_DXR_trunk` will never be called by the main nightly. Here for example, `HDRP_DXR_Win_DX12_playmode_XR_mono_Linear_trunk` and `HDRP_DXR_Win_DX12_Standalone_mono_Linear_trunk` will never be called. 
Same goes for all the "sub-nightlies", shadergraph_stereo, universal_hybrid, etc
Or am I missing something?

2020-12-09 09:08 UTC, sophiaaar commented on .yamato/all-hdrp_dxr.yml
> +Nightly_HDRP_DXR_trunk:
fixed in latest push, thank you!

2020-12-09 09:22 UTC, theo-pnv approved these changes

2020-12-10 10:57 UTC, theo-pnv approved these changes

2020-12-10 11:46 UTC, merged