Universal/preview camera background color
Unity-Technologies/Graphics pull request #2900
Opened 2020-12-15 09:16 UTC by martint-unity

---
### Purpose of this PR
Fixing the issues people are experiencing with a darker background for the previews.

---
### Testing status
Opened up both URP and HDRP and created Prefabs and checking previews that the color is the default gray.

---
### Comments to reviewers
Notes for the reviewers you have assigned.

2020-12-15 09:59 UTC, madsnyholm requested changes
Please remove the Preview background color from Preferences and the Settings Provider. It needs to be a const color, since there are no decencies setup that will ensure all assets are reimported if the background color changes. 
See discussion https://unity.slack.com/archives/C0A9NNY9W/p1608024382240300?thread_ts=1607848679.236200&cid=C0A9NNY9W

2020-12-15 09:59 UTC, madsnyholm commented on com.unity.render-pipelines.core/Runtime/Utilities/CoreRenderPipelinePreferences.cs
> +        public static Color previewBackgroundColor
This Preview background color cannot be a User Preference.
See discussion https://unity.slack.com/archives/C0A9NNY9W/p1608024382240300?thread_ts=1607848679.236200&cid=C0A9NNY9W

2020-12-15 11:07 UTC, madsnyholm approved these changes
Looks good.

2020-12-15 12:37 UTC, JulienIgnace-Unity approved these changes

2020-12-15 15:11 UTC, sebastienlagarde approved these changes

2020-12-16 09:40 UTC, RSlysz approved these changes
lgtm

2020-12-16 11:36 UTC, TomasKiniulis reviewed
Taking a look on HDRP side. If I update an older project where preview was black then prefab still holds black background even after doing a reimport, same goes to Fbx and material has to be clicked to change background. Would it be possible to have this fixed in the same PR? 

![upgradedProjectConvert](https://user-images.githubusercontent.com/50582134/102343470-45e84080-3fa3-11eb-8a1d-5f70c5a204ea.gif)

2020-12-16 12:33 UTC, martint-unity commented
@TomasKiniulis You will have to do a Re-import all for this to take affect on old projects.

2020-12-16 13:14 UTC, erikabar approved these changes
Tested Material, Mesh, Prefab, Model Project preview and Inspector preview backgrounds, the issue is fixed.

2020-12-16 13:20 UTC, TomasKiniulis approved these changes
Approving this, although I see a potential issue where users might be confused why background colors vary between old assets and newly created ones on project upgrade without "Reimport All", but there doesn't seem to be other way to resolve this

2020-12-16 13:49 UTC, phi-lira approved these changes

2020-12-16 13:49 UTC, merged