Sg/vertexid color
Unity-Technologies/Graphics pull request #2937
Opened 2020-12-17 17:59 UTC by esmelusina

---
### Purpose of this PR
Some minor feature work to expose vertex color as an interpolator target for Universal and HDRP. Vertex ID and Instance ID are also exposed through nodes.

---
### Testing status
Tests added to ShaderGraph test for Color Interpolator and Vertex ID, this uses the Universal pipeline for testing.

2020-12-21 21:15 UTC, LandonTownsendUnity commented
I would like for HDRP team to add automated tests for this if possible, since it has unique code paths in HDRP material types. Other than that I think this is good. Instance ID doesn't always work correctly for me (on my computer it didn't work in play mode in my project, but it worked in the automated test.)

2020-12-22 17:42 UTC, ValGrimm-U3D approved these changes
Discussed two sentences to change with Esme, but didn't go deep into it as I don't have a lot of context. Don't see any major issues here. No need to hold this PR for the docs questionnaire, we'll do it after in https://unity3d.atlassian.net/browse/DOC-2690

2021-01-13 11:34 UTC, ValGrimm-U3D commented
I'm not sure if your recent changes have involved doc but I can look at this next week.

2021-01-13 18:51 UTC, LandonTownsendUnity approved these changes
HDRP tests made it in so I think the PR is good now

2021-01-14 10:37 UTC, pbbastian requested changes
Looks good, only have one minor request

2021-01-18 13:37 UTC, ValGrimm-U3D commented on com.unity.shadergraph/Documentation~/Input-Nodes.md
> +|Provides access to parameters of the screen.|Provides access to the Eye Index during stereo rendering.|
"Provides access to screen parameters."

2021-01-18 13:42 UTC, ValGrimm-U3D commented on com.unity.shadergraph/Documentation~/Instance-ID-Node.md
> +Provides access to the **Instance ID** assigned when rendering with GPU instancing.
"Provides access to the Instance ID that the GPU assigns when you render with GPU instancing."
(assigned is passive voice, so I am trying to fix it here)

2021-01-18 13:43 UTC, ValGrimm-U3D approved these changes
Suggested two minor docs changes @esmelusina . Accidentally started a review by clicking the wrong thing, so approving.

2021-01-25 07:45 UTC, pbbastian approved these changes

2021-02-17 18:33 UTC, esmelusina commented
PR no longer necessary, color interpolator use-cases will be addressed by the Custom Interpolators feature here: https://github.com/Unity-Technologies/Graphics/pull/3281. The other utility nodes in this PR have already merged under a different PR.

2021-02-17 18:33 UTC, closed without merging