Fixed various Look Dev issues after exiting Playmode
Unity-Technologies/Graphics pull request #2956
Opened 2020-12-18 13:36 UTC by JulienIgnace-Unity

### Purpose of this PR
This PR fixes a number of issues with the Look Dev tool after exiting playmode.
Original issue can be found here: https://fogbugz.unity3d.com/f/cases/1293262/

The root of the problem is that the Look Dev stores its state in serialized field in order to be able to have a persistent layout on domain reload etc.
The issue is that the reference to this state was stored in many different places and after exiting playmode it would become invalid but still accessible (because Unity does weird things like this). Basically resetting the Look Dev in whatever last correct serialized state it was in before entering playmode. This is why for example the layout could reset to single view after exiting playmode.

After fixing this issue, there were many consequences like HDRI not updating, comparison gizmo not working etc. I tracked and fixed all the issues like this I found.

---
### Testing status
After finding out that most issues were after exiting playmode I tested all this after doing so:
- Tested the original issue
- Tested changing HDRI in view 1 or 2 / side by side etc
- Moving the camera
- Changing current objet
- Comparison gizmo

---
### Comments to reviewers
@Unity-Technologies/gfx-qa-hdrp  as I had to change quite a bit of internal code I think it would be good to have a thorough pass on the Look Dev to make sure everything is still ok.
We especially need to test everything AFTER exiting playmode in particular as this is where most issues occured.

2020-12-18 14:14 UTC, RSlysz approved these changes
Looks good to me

2020-12-18 14:14 UTC, RSlysz commented on com.unity.render-pipelines.core/Editor/LookDev/CameraController.cs
> +            m_CameraState = null;
This is optional as the default value should be null

2020-12-18 14:14 UTC, RSlysz commented on com.unity.render-pipelines.core/Editor/LookDev/CameraController.cs
> +            m_SecondView = null;
same

2020-12-18 14:14 UTC, RSlysz commented on com.unity.render-pipelines.core/Editor/LookDev/Compositor.cs
> +            m_Contexts = null;
same

2020-12-18 14:14 UTC, RSlysz commented on com.unity.render-pipelines.core/Editor/LookDev/LookDev.cs
> +            //get => s_CurrentContext ?? (s_CurrentContext = LoadConfigInternal() ?? defaultContext);
Should be removed

2020-12-18 16:30 UTC, sebastienlagarde approved these changes

2020-12-21 14:39 UTC, JMargevics requested changes
Hey, so I've tried this branch and I can't assign any Env. Libraries on it. Same works fine on Master. 

❌ This branch:
https://user-images.githubusercontent.com/50581102/102788155-de6b3000-43aa-11eb-9e24-91a4675489cb.mp4

✔ Master:
https://user-images.githubusercontent.com/50581102/102788160-e0cd8a00-43aa-11eb-8a21-76524993e0df.mp4

2021-01-11 09:40 UTC, merged