bugfix for view direction node in tangent space being not using the c…
Unity-Technologies/Graphics pull request #3044
Opened 2021-01-08 23:22 UTC by joshua-davis

…orrect calculation.

# **Please read the [Contributing guide](CONTRIBUTING.md) before making a PR.**

* Read the [Graphics repository & Yamato FAQ](http://go/graphics-yamato-faq).

### Checklist for PR maker
- [ ] Have you added a backport label (if needed)? For example, the `need-backport-*` label. After you backport the PR, the label changes to `backported-*`.
- [ ] Have you updated the changelog? Each package has a `CHANGELOG.md` file.
- [ ] Have you updated or added the documentation for your PR? When you add a new feature, change a property name, or change the behavior of a feature, it's best practice to include related documentation changes in the same PR. If you do add documentation, make sure to add the relevant Graphics Docs team member as a reviewer of the PR. If you are not sure which person to add, see the [Docs team contacts sheet](https://docs.google.com/spreadsheets/d/1rgUWWgwLFEHIQ3Rz-LnK6PAKmbM49DZZ9al4hvnztOo/edit#gid=1058860420).
- [ ] Have you added a graphic test for your PR (if needed)? When you add a new feature, or discover a bug that tests don't cover, please add a graphic test.

---
### Purpose of this PR
Why is this PR needed, what hard problem is it solving/fixing?

---
### Testing status
Tested the attached shader graph in the bug: https://fogbugz.unity3d.com/f/cases/1296788/

---
### Comments to reviewers
Notes for the reviewers you have assigned.

2021-01-11 17:49 UTC, cdxntchou approved these changes

2021-01-11 18:46 UTC, LandonTownsendUnity requested changes
TransformWorldToTangent contains a normalization step, whereas the previous algorithm doesn't normalize. Can you remove the normalization step and see if the algorithm still works? This will allow us to backport it to versions where we don't plan on normalizing the view direction coming in from URP

2021-01-13 18:54 UTC, LandonTownsendUnity requested changes
Testing has confirmed that in some cases (speedtrees for example) tangent space is not orthogonal at the vertices, so the vertex templates need to be updates as well

2021-01-13 20:20 UTC, joshua-davis commented
> Testing has confirmed that in some cases (speedtrees for example) tangent space is not orthogonal at the vertices, so the vertex templates need to be updates as well

Updated

2021-01-14 21:32 UTC, LandonTownsendUnity approved these changes
Before and after fix to vertex templates (using the following shadergraph, which offsets position if the tangent space view dir code isn't fixed)
![image](https://user-images.githubusercontent.com/52939698/104651653-cbc3de00-566c-11eb-9c82-69e61eadb16f.png)
Before:
![image](https://user-images.githubusercontent.com/52939698/104651670-d2525580-566c-11eb-8ebe-9e7ae662e2f4.png)
After
![image](https://user-images.githubusercontent.com/52939698/104651758-f150e780-566c-11eb-8cf4-5caf0a7ac346.png)

That should be everything.

2021-01-14 21:35 UTC, LandonTownsendUnity requested changes

2021-01-14 21:35 UTC, LandonTownsendUnity commented on com.unity.shadergraph/CHANGELOG.md
> +- Fixed the ViewDirection Node in Tanget space's calculation to match how the transform node works.
"Tanget" should be "Tangent"

2021-01-14 21:50 UTC, joshua-davis commented on com.unity.shadergraph/CHANGELOG.md
> +- Fixed the ViewDirection Node in Tanget space's calculation to match how the transform node works.
Nice catch. Fixed

2021-01-14 21:56 UTC, LandonTownsendUnity approved these changes
Typo fixed, reapproving

2021-01-15 21:52 UTC, cdxntchou approved these changes

2021-02-04 16:05 UTC, joshua-davis commented
Failures on HDRP match current state of master

2021-02-04 21:08 UTC, merged