Sg doc 2695 21.1 backport
Unity-Technologies/Graphics pull request #3241
Opened 2021-01-22 12:34 UTC by ValGrimm-U3D

# **Please read the [Contributing guide](CONTRIBUTING.md) before making a PR.**

* Read the [Graphics repository & Yamato FAQ](http://go/graphics-yamato-faq).

### Checklist for PR maker
- [Y] Have you added a backport label (if needed)? For example, the `need-backport-*` label. After you backport the PR, the label changes to `backported-*`.
- [Y] Have you updated the changelog? Each package has a `CHANGELOG.md` file.
- [Y] Have you updated or added the documentation for your PR? When you add a new feature, change a property name, or change the behavior of a feature, it's best practice to include related documentation changes in the same PR. If you do add documentation, make sure to add the relevant Graphics Docs team member as a reviewer of the PR. If you are not sure which person to add, see the [Docs team contacts sheet](https://docs.google.com/spreadsheets/d/1rgUWWgwLFEHIQ3Rz-LnK6PAKmbM49DZZ9al4hvnztOo/edit#gid=1058860420).
- [N/A] Have you added a graphic test for your PR (if needed)? When you add a new feature, or discover a bug that tests don't cover, please add a graphic test.

---
### Purpose of this PR
Why is this PR needed, what hard problem is it solving/fixing?
Apply changes to resolve DOC-2695

---
### Testing status
Describe what manual/automated tests were performed for this PR
N/A

---
### Comments to reviewers
Merge this AFTER #3240 Sg-doc-2568-21.1-backport to avoid a changelog merge conflict. (Filing this PR later to the same base, so that may be obvious (: ) Recreating the changes in the order they were merged to master. Consciously separating work on multiple tickets for future traceability. 

Given how soon the release is, assigned both of these to Sebastien as reviewer, normally I would not do so. Will ask what procedure to follow next time this happens so I don't have to bother Sebastien every time (:

2021-02-03 00:14 UTC, marctem commented on com.unity.shadergraph/CHANGELOG.md
> +- Adjusted docs for SampleTexture2D, SampleTexture2DLOD, SampleTexture2DArray, SampleTexture3D, SampleCubemap, SampleReflectedCubemap, TexelSize, NormalFromTexture, ParallaxMapping, ParallaxOcclusion
This line should not be part of this PR.

2021-02-03 00:14 UTC, marctem requested changes
Changelog has 2 entries, should only have 1.

2021-05-27 13:00 UTC, ValGrimm-U3D commented
@cdxntchou I made the changes, can you help me override the block?

2021-06-03 21:07 UTC, esmelusina approved these changes

2021-06-04 16:51 UTC, ValGrimm-U3D commented
It seems I need @marctem to approve because of the changes requested (which I did address)?

2021-06-07 17:12 UTC, marctem approved these changes

2021-06-07 17:12 UTC, merged