Cleanup of AO code.
Unity-Technologies/Graphics pull request #3278
Opened 2021-01-27 17:41 UTC by JulienIgnace-Unity

### Purpose of this PR
Continuation of https://github.com/Unity-Technologies/Graphics/pull/3150
This PR focuses on Ambient occlusion code. It follows the same pattern as previous PRs.
- Remove AmbientOcclusionSystem class in favor of partial HDRenderPipeline class for both RT and regular AO.
- Moved relevant code to two specific files for regular and ray traced AO.

---
### Testing status
Ran automated test locally.

---
### Comments to reviewers
It could be useful to test a bit more in depth both types of AO and play with various parameters (fullscreen, temporal etc...)

2021-01-29 09:47 UTC, anisunity approved these changes
LGTM

2021-02-02 11:17 UTC, iM0ve requested changes
**Whats tested**
* All properties in SSAO
* All properties in Raytraced SSAO
* Dx12
* Real use case scenario: HDRP template. Compared 10.3 vs PR ssao/rtssao
* SSAO debug mode
* Undo

**Issues:**
1) **[No longer reproduces]** Found an issue where the editor would crash. Only happens on this branch and not on master. Also was only able to reproduce in the template and not in a simple project. 
Repro:
Turn on Full resolution
Toggle the Temporal Accumulation

https://user-images.githubusercontent.com/36502659/106593069-01b3fe00-6559-11eb-9d30-9467131daffa.mp4

2021-02-11 10:19 UTC, iM0ve approved these changes
Updating the review.

I quickly rechecked all parameters of AO and RTX AO. No longer experience any crashes. Looks good.

![image](https://user-images.githubusercontent.com/36502659/107624326-5e9f6a80-6c63-11eb-90f6-d56f9416a2b7.png)

2021-02-11 17:59 UTC, sebastienlagarde approved these changes

2021-02-11 18:55 UTC, merged