[2021.2] Fixed error with multisampled sampler in XR
Unity-Technologies/Graphics pull request #3357
Opened 2021-02-02 23:19 UTC by thomas-zeng

---
### Purpose of this PR
Fixed fogbugz case https://fogbugz.unity3d.com/f/cases/1297013/

---
### Testing status
- QA
- ABV

---
### Comments to reviewers
- URP non XR pass does not run copyDepth msaa code pass due to [CanCopyDepth ](https://github.com/Unity-Technologies/Graphics/blob/f5c82ce283b5b92ad0bebfcd0a0827c3b6404562/com.unity.render-pipelines.universal/Runtime/ForwardRenderer.cs#L821) check. In XR, we use copyDepth to support depth sharing in non-direct-to-eye case. Added check to configure samples to 1 when auto resolve is enabled or multisampled texture is not supported.

2021-02-04 15:55 UTC, fabien-unity commented on com.unity.render-pipelines.universal/Runtime/Passes/CopyDepthPass.cs
> +                // When auto resolve is supoorted or multisampled texture is not supported, set camera samples to 1
small typo : supoorted

2021-02-05 18:21 UTC, thomas-zeng commented on com.unity.render-pipelines.universal/Runtime/Passes/CopyDepthPass.cs
> +                // When auto resolve is supoorted or multisampled texture is not supported, set camera samples to 1
fixed in 0e6831a

2021-02-05 18:26 UTC, fabien-unity approved these changes

2021-02-12 22:57 UTC, ryanhy-unity commented
Fix looks good.  Tested on my Quest and no black screen or errors.

2021-02-12 22:58 UTC, ryanhy-unity approved these changes

2021-02-26 20:51 UTC, ellioman commented on com.unity.render-pipelines.universal/Runtime/Passes/CopyDepthPass.cs
> +                    cameraSamples = 1;
Can we maybe update the comment above for default case in the switch statement below?

2021-02-26 20:51 UTC, ellioman approved these changes

2021-03-04 11:15 UTC, erikabar requested changes
Android devices are still rendering black screen: 

tested and reproduced with:
- VLNQA00144, Samsung Galaxy S9 USA, 10.0.0, Snapdragon 845 SDM845, Adreno 630
- VLNQA00314, LGE Nexus 5X, 8.0.0, Snapdragon 808, Adreno 418
- VLNQA00320, Xiaomi Redmi Note 8 Pro, 9.0.0, MediaTek Helios G90T MT6785T, Mali-G76 MC4
- VLNQA00041, Samsung Galaxy S8, 8.0.0, Exynos 9 Octa 8895, Mali-G71
- VLNQA00175, Samsung Galaxy Note9, 10.0.0, Exynos 9 Series 9810, Mali-G72

2021-03-08 09:07 UTC, erikabar approved these changes
After discussing with Thomas, running mockHMD on Android shows black screen is actually expected. I am not getting errors as described in the bug report.

2021-03-15 12:59 UTC, phi-lira approved these changes

2021-03-15 12:59 UTC, merged