Updated documentation of RequestRenderNextUpdate
Unity-Technologies/Graphics pull request #3368
Opened 2021-02-03 13:55 UTC by fredericv-unity3d

### Purpose of this PR
Added information to a method documentation for better understanding. (See https://fogbugz.unity3d.com/f/cases/1290521).

---
### Testing status
No code was changed, only the documentation.

---
### Comments to reviewers
Doc: please review the modified documentation.

2021-02-03 16:53 UTC, JordanL8 requested changes
Reworded to use active voice. Can you replace the other one with this too? Thanks

2021-02-03 16:53 UTC, JordanL8 commented on com.unity.render-pipelines.high-definition/Runtime/Lighting/Reflection/HDAdditionalReflectionData.cs
> +        /// Note: A camera is influenced by a probe if the camera's frustum intersects the probe's influence volume.
Note: If any part of a Camera's frustum intersects a Reflection Probe's influence volume, the Reflection Probe influences the Camera.

2021-02-05 18:14 UTC, sebastienlagarde commented
@fredericv-unity3d  any update?

2021-02-12 20:12 UTC, sebastienlagarde commented
@fredericv-unity3d can you update this PR? thanks

2021-02-17 08:15 UTC, fredericv-unity3d commented
Sorry for the delay, the github notification was lost somehow

2021-02-17 11:33 UTC, JordanL8 approved these changes
Moved the extra information into remarks and reworded some bits. Looks good to me :)

2021-02-17 20:10 UTC, merged