Add explicit control for double sided GI
Unity-Technologies/Graphics pull request #3371
Opened 2021-02-03 15:17 UTC by FrancescoC-unity

Added option to control if a material is considered double sided for GI or not to be on par with what Builtin has. 

![image](https://user-images.githubusercontent.com/43168857/106767169-e15c7000-663a-11eb-858b-dba343596349.png)

This allows for independent control. 

What did I test. 

I used this scene setup, where if double sided for GI is **not used**  will look like

![image](https://user-images.githubusercontent.com/43168857/106767314-03ee8900-663b-11eb-99aa-99407457e08e.png)

If it is used it looks like 

![image](https://user-images.githubusercontent.com/43168857/106767369-15379580-663b-11eb-840f-9c144e762b0d.png)

Given that, I tried both with a Lit material and a Lit from shadergraph to try all the new options with the material double sided option ON and OFF (all combinations).

2021-02-03 15:44 UTC, TomasKiniulis commented
@FrancescoC-unity I think surface options doc page should be updated https://docs.unity3d.com/Packages/com.unity.render-pipelines.high-definition@10.3/manual/Surface-Type.html and the PR could benefit from a dedicated automated test scene, also maybe it would be possible to have spaces in input field options? For example "Forces On" instead of "ForcesOn".

2021-02-03 15:46 UTC, FrancescoC-unity commented
I'll update the doc! I will also try to add a test, will have to remember in a bit :D 

Regarding the space, unfortunately I don't think we can.

2021-02-03 18:58 UTC, sebastienlagarde reviewed
Sanity check. QA you should test migration. I expect we don't need any migratoin code because the default value (0) of the enum is matchmaterial so the same than the old behavior. But better to QA it.

Also for QA be sure to test with both ShaderGraph and non shader graph shader.

2021-02-04 08:20 UTC, radishface commented
Thanks for implementing this! I would suggest renaming the enums in the UI to:

- `MatchMaterial` to `Auto`
- `ForcesOn` to `On`
- `ForcesOff` to `Off`

2021-02-04 08:33 UTC, radishface requested changes
Changes look good! Only had a couple of UI-related suggestions to add.

2021-02-04 08:33 UTC, radishface commented on com.unity.render-pipelines.high-definition/Editor/Material/ShaderGraph/HDSubShaderUtilities.cs
> +                enumNames = { "MatchMaterial", "ForcesOn", "ForcesOff" }, // values will be 0, 1 and 2
Please rename enum values in the UI to:
`MatchMaterial` to `Auto`
`ForcesOn` to `On`
`ForcesOff` to `Off`

2021-02-04 08:33 UTC, radishface commented on com.unity.render-pipelines.high-definition/Editor/Material/UIBlocks/SurfaceOptionUIBlock.cs
> +            public static GUIContent doubleSidedGIText = new GUIContent("Double-Sided GI", "Determines how double-sided GI is handled.");
Please make sure that the tooltip matches our [documentation page](https://docs.unity3d.com/ScriptReference/Material-doubleSidedGI.html):

> When enabled, the lightmapper accounts for both sides of the geometry when calculating Global Illumination. Backfaces are not rendered or added to lightmaps, but get treated as valid when seen from other objects. When using the Progressive Lightmapper backfaces bounce light using the same emission and albedo as frontfaces. (Currently this setting is only available when baking with the Progressive Lightmapper backend.)

2021-02-04 09:54 UTC, radishface approved these changes
Thank you for implementing changes so quickly. Approved!

2021-02-04 09:59 UTC, sebastienlagarde commented
Note for me: must be retarget to master once hd/bugfix is merge

2021-02-05 11:55 UTC, iM0ve requested changes
**Whats tested:**
* Upgrading + shadergraph
* Lit, LayeredLitTesselation, Unlit, 
* Raytraced SSGI
* Path tracing

**Concerns**

1) **[Fixed]** The option does not exist for Unlit? Expected?

![Unlit](https://user-images.githubusercontent.com/36502659/107030268-0c6cce00-67b9-11eb-9164-720c9ca481fd.png)


2) **[Expected]** Has no effect on Raytraced SSGI or Path tracing. I assume this is expected because the tooltip says its only lightmapping. But want to clarify if we want parity for raytracing

![Path](https://user-images.githubusercontent.com/36502659/107030521-74231900-67b9-11eb-8399-21bbeca32439.jpg)

**Conclusion:**
I found no major issues and upgrading works. Just want to clarify the concerns and will approve.
Update: issues addressed/fixed

2021-02-08 10:01 UTC, FrancescoC-unity commented
> **Whats tested:**
> 
> * Upgrading + shadergraph
> * Lit, LayeredLitTesselation, Unlit,
> * Raytraced SSGI
> * Path tracing
> 
> **Concerns**
> 
> 1. The option does not exist for Unlit? Expected?
> 
> ![Unlit](https://user-images.githubusercontent.com/36502659/107030268-0c6cce00-67b9-11eb-9164-720c9ca481fd.png)
> 
> 1. Has no effect on Raytraced SSGI or Path tracing. I assume this is expected because the tooltip says its only lightmapping. But want to clarify if we want parity for raytracing
> 
> ![Path](https://user-images.githubusercontent.com/36502659/107030521-74231900-67b9-11eb-8399-21bbeca32439.jpg)
> 
> **Conclusion:**
> I found no major issues and upgrading works. Just want to clarify the concerns and will approve.

Indeed this is just for baked GI, I'd personally keep Ray tracing "proper". The reason why you want this separate is mostly tied to how the baking process works. 

I guess Unlit should be there, I'll fix it up

2021-02-11 09:49 UTC, iM0ve approved these changes
Updated the review

2021-02-14 23:22 UTC, sebastienlagarde commented
screenshots have been updated

2021-02-14 23:22 UTC, merged