HDRP/Enlighten Realtime GI support
Unity-Technologies/Graphics pull request #3385
Opened 2021-02-04 12:06 UTC by KEngelstoft

### Purpose of this PR
Reactivate Enlighten Realtime GI support for HDRP. Makes it easier to upgrade from builtin render pipeline or HDRP 7 and older.

### Testing status
Manual testing by the developer using Windows10 and a Threadripper 3990X engineering sample, using the template scene with lights and emissive objects tweaked to generate realtime bounce lighting. SRP batcher has been tested.
![rtgi-hdrp-emission](https://user-images.githubusercontent.com/6929868/106889867-e2e47180-66e8-11eb-975c-8619aa1a06ee.png)

Material inspector has been streamlined to work like the build in one (user can now choose between baked and realtime GI emission).

Tech art validation pass done here https://jira.unity3d.com/browse/GFXGI-400

Automated test coverage has been added in the following scenes:
2101_GI_Metapass
2102_GI_Emission
2106_GI_EmissionSG
Realtime GI has been disabled in all other scenes.

Documentation has been updated.

Screenshots, native PRs and more info here https://docs.google.com/document/d/1K6uE2AtJ2lVW2JbM_xO5dFvbR8o2TdXNARJAlzbzYa8/edit#

### Comments to reviewers
Jira task https://jira.unity3d.com/browse/GFXGI-395

2021-02-08 14:39 UTC, iM0ve requested changes
Review: **In Progress**

**Concerns:**
1) After Realtime GI was enabled and Baked was disabled in the Lighting settings. Existing mixed lights show a warning that "Realtime" mode is being used instead of Mixed. However, GI bounce is not visible until you manually switch the mode to Realtime. Is this an issue? Should we update the behavior or the warning text?

https://user-images.githubusercontent.com/36502659/107234252-2530ea00-6a2c-11eb-88b4-5bd78b2e686d.mp4


2) Is it expected that the property is labeled as Deprecated?

![image](https://user-images.githubusercontent.com/36502659/107348073-3b43b680-6acf-11eb-9258-f272281421a7.png)


3) Adding Area light doesnt work like it used to. First part of the video shows expected behaviour, after adding area light you can instantly adjust the indirect intensity. Pont and Spot lights work as expected however.

https://user-images.githubusercontent.com/36502659/107362611-a5655700-6ae1-11eb-8a14-f0bf14d9362c.mp4



**What's tested:**
* Upgrading an old HDRP(4.1) project with Enligten to see if after an upgrade it's still possible to achieve the same result
* Scene debug modes (Albedo, Emissive, Indirect, Directionality)
* Testing with different light types (Point, Spot, Area)
* Day and Night cycle covered by  David Llewelyn [here](https://jira.unity3d.com/browse/GFXGI-400)

**Upgrade result**
Note it is expected that the image is slightly different because in the original, the old Procedural sky was used + old post processing stack. In the upgraded version physically-based sky was used.

Original {HDRP 4.1}

![Original](https://user-images.githubusercontent.com/36502659/107492400-11ed5e00-6b95-11eb-8b46-aa42bad68c76.png)

Upgraded {PR branch}

![ReEnlighten](https://user-images.githubusercontent.com/36502659/107492449-203b7a00-6b95-11eb-8154-0f466c810488.png)

2021-02-10 14:14 UTC, KEngelstoft commented
> Review: **In Progress**
> 
> **Concerns:**
> 
> 1. After Realtime GI was enabled and Baked was disabled in the Lighting settings. Existing mixed lights show a warning that "Realtime" mode is being used instead of Mixed. However, GI bounce is not visible until you manually switch the mode to Realtime. Is this an issue? Should we update the behavior or the warning text?
> 
>  Cq8CtX4mSJ.mp4 
> 
> 1. Is it expected that the property is labeled as Deprecated?
> 
> ![image](https://user-images.githubusercontent.com/36502659/107348073-3b43b680-6acf-11eb-9258-f272281421a7.png)
> 
> 1. Adding Area light doesn't work like it used to. First part of the video shows expected behavior, after adding area light you can instantly adjust the indirect intensity. Point and Spotlights work as expected however.
> 
>  G4J5ccaTmD.mp4 
> 
> 1. New light types such as Pyramid, Box, etc. Also do not work with Enlighten. Not sure if we should add a warning or address this in any way
> 
>  dxOrsjBoxT.mp4 
> 
> **What's tested:**
> 
> * Upgrading an old HDRP(4.1) project with Enlighten to see if after an upgrade it's still possible to achieve the same result
> * Enlighten scene debug modes (Albedo, Emissive, Indirect, Directionality)
> * Different light types (Point, Spot, Area)
> * Checked that real-time emissives work by changing intensity and observing indirect light changes in the Tunnel scene.
> * Day and Night cycle covered by  David Llewelyn [here](https://jira.unity3d.com/browse/GFXGI-400)
> 
> **Upgrade result**
> Note it is expected that the image is slightly different because in the original, the old Procedural sky was used + old post processing stack. In the upgraded version physically-based sky was used.
> 
> Original {HDRP 4.1}
> 
> ![Original](https://user-images.githubusercontent.com/36502659/107492400-11ed5e00-6b95-11eb-8b46-aa42bad68c76.png)
> 
> Upgraded {PR branch}
> 
> ![ReEnlighten](https://user-images.githubusercontent.com/36502659/107492449-203b7a00-6b95-11eb-8154-0f466c810488.png)

1) This behaviour is also present in the built-in render pipeline. I will consult with @w1shmast3r if this should be reported or by design. In any case, it is unrelated to the changes in this PR and will likely have to be addressed in native code if we decide to fix it.

2) Yes, if you are using an older version of the Editor. The label was removed here https://ono.unity3d.com/unity/unity/pull-request/119636/_/lighting/remove-enlighten-rtgi-deprecation (landed in trunk already).

3) It is hard to tell from the video but is the area light intensity so low that it isn't visible?

4) This is by design. Yes, there should be a warning or they should be greyed out in the inspector. I have added a note here so it is not forgotten https://jira.unity3d.com/browse/GFXGI-395

2021-02-11 07:53 UTC, iM0ve commented
Updated my review.
To clarify the 3rd concern, Area light GI bounce was working in 4.1 and no longer works in the PR version. In the video I try to highlight this by adjusting the indirect slider

2021-02-11 12:13 UTC, KEngelstoft commented
> Updated my review.
> To clarify the 3rd concern, Area light GI bounce was working in 4.1 and no longer works in the PR version. In the video I try to highlight this by adjusting the indirect slider

In HDRP 4.1 Rectangle lights were represented by point lights, this is why you are seeing bounce from the area light.

com.unity.render-pipelines.high-definition\Editor\Lighting\HDLightEditor.cs line 539:
case LightShape.Rectangle:
                    // TODO: Currently if we use Area type as it is offline light in legacy, the light will not exist at runtime
                    //m_BaseData.type.enumValueIndex = (int)LightType.Rectangle;
                    // In case of change, think to update InitDefaultHDAdditionalLightData()
                    settings.lightType.enumValueIndex = (int)LightType.Point;

2021-02-11 14:05 UTC, sebastienlagarde commented on com.unity.render-pipelines.high-definition/Runtime/Material/BuiltinGIUtilities.hlsl
> +    float3 illuminance = SampleSingleLightmap(TEXTURE2D_ARGS(unity_DynamicLightmap, samplerunity_DynamicLightmap), uvDynamicLightmap, unity_DynamicLightmapST, false, decodeInstructions);
I will do a separate PR for this fix as it need to be backported, thanks for finding it

2021-02-11 14:20 UTC, sebastienlagarde commented
Hey, from the latest comment I don't understand if Area light are working or not, could you confirm?

>Area light GI bounce was working in 4.1
Do you mean HDRP 4.1? Don't think we can do any comparison with that anymore. 

If I get the issue, it is about rectangle light not working correctly with real time enlighten?  And it is because at runtime we approximate with a point light right? . I will expect that it is expected to not works as builtin wasn't supporting rect area light at runtime, so the support have never been added for Real time Enlighten right?

2021-02-11 14:20 UTC, sebastienlagarde commented
Otherwise the PR is good for me

2021-02-11 14:21 UTC, sebastienlagarde commented
Note: could you merge latest master? the PR is really far behing the mainline. Thanks

2021-02-11 14:22 UTC, sebastienlagarde commented
Also not sure if we will conflict with this PR: https://github.com/Unity-Technologies/Graphics/pull/3371/files or if the test of this PR will need to be update to not used realtime GI?

2021-02-11 16:44 UTC, KEngelstoft commented
> Hey, from the latest comment I don't understand if Area light are working or not, could you confirm?
> 
> > Area light GI bounce was working in 4.1
> > Do you mean HDRP 4.1? Don't think we can do any comparison with that anymore.
> 
> If I get the issue, it is about rectangle light not working correctly with real time enlighten? And it is because at runtime we approximate with a point light right? . I will expect that it is expected to not works as builtin wasn't supporting rect area light at runtime, so the support have never been added for Real time Enlighten right?

Rectangular area lights are not passed as inputs to Enlighten in the native code at this point, but could probably be added later if desired.

2021-02-12 12:21 UTC, KEngelstoft commented
@iM0ve I have added warnings in the inspector for HDRP specific light types Pyramid, Box and Tube because they do not work with Enlighten.
![inspector](https://user-images.githubusercontent.com/6929868/107767389-29fbe380-6d35-11eb-8fed-fffa50e24aca.png)

2021-02-12 12:44 UTC, iM0ve commented
Will do one last check after the PR is updated with master. 
Also to clarify, I 4th issue was addressed here and also 3rd?

Regarding 3rd, curious why the if editor check was necessary before and is no longer required. Should I do some additional halo testing for this bit?

![image](https://user-images.githubusercontent.com/36502659/107769440-af38c580-6d40-11eb-9b1e-1c4293499759.png)

2021-02-12 13:00 UTC, KEngelstoft commented
> Will do one last check after the PR is updated with master.
> Also to clarify, I 4th issue was addressed here and also 3rd?
> 
> Regarding 3rd, curious why the if editor check was necessary before and is no longer required. Should I do some additional halo testing for this bit?
> 
> ![image](https://user-images.githubusercontent.com/36502659/107769440-af38c580-6d40-11eb-9b1e-1c4293499759.png)

The 3rd issue (rect area light not working after upgrade) will be addressed with native code changes here https://ono.unity3d.com/unity/unity/pull-request/120752/_/lighting/enlighten-rect-light

The 4th issue is addressed by the newly pushed changes (https://github.com/Unity-Technologies/Graphics/pull/3385/commits/3696f0ceba14d71729493929e527eed01c8e8fa2) on this branch

2021-02-12 13:03 UTC, KEngelstoft commented
You could do additional checks for baked area lights as it looks like they were never using the value from the width / height in HDAdditionalLightData (they used the value from the builtin light data, so often 0.5x0.5). Here is a comparison of before and after for baked lights. This is also fixing it for mixed and realtime area lights with Enlighten.
![after](https://user-images.githubusercontent.com/6929868/107771454-12275e00-6d3b-11eb-98f8-0631cf1659df.png)
![before](https://user-images.githubusercontent.com/6929868/107771456-12bff480-6d3b-11eb-851a-12dfab52e504.png)

2021-02-12 13:39 UTC, sebastienlagarde approved these changes
Thanks for the update! All good for me

2021-02-12 14:35 UTC, iM0ve approved these changes
I upgraded the review and had a last look. All issues were addressed or fixed. Good to go from my side.

2021-02-12 20:55 UTC, jessebarker approved these changes
Approving the Shader Graph change.

2021-02-15 18:56 UTC, merged