Bugfix 1287335: Enum keywords would fail when an entry was given a du…
Unity-Technologies/Graphics pull request #3472
Opened 2021-02-11 17:38 UTC by joshua-davis

…plicate name that differed only by case. In addition there were various symbols that could be used that would break enum keywords due to how the material enum property editor sanitized display names.

https://fogbugz.unity3d.com/f/cases/1287335/

# **Please read the [Contributing guide](CONTRIBUTING.md) before making a PR.**

* Read the [Graphics repository & Yamato FAQ](http://go/graphics-yamato-faq).

### Checklist for PR maker
- [x] Have you added a backport label (if needed)? For example, the `need-backport-*` label. After you backport the PR, the label changes to `backported-*`.
- [x] Have you updated the changelog? Each package has a `CHANGELOG.md` file.
- [ ] Have you updated or added the documentation for your PR? When you add a new feature, change a property name, or change the behavior of a feature, it's best practice to include related documentation changes in the same PR. If you do add documentation, make sure to add the relevant Graphics Docs team member as a reviewer of the PR. If you are not sure which person to add, see the [Docs team contacts sheet](https://docs.google.com/spreadsheets/d/1rgUWWgwLFEHIQ3Rz-LnK6PAKmbM49DZZ9al4hvnztOo/edit#gid=1058860420).
- [ ] Have you added a graphic test for your PR (if needed)? When you add a new feature, or discover a bug that tests don't cover, please add a graphic test.

---
### Purpose of this PR
Originally the bug was that giving two enum keywords the same display name with different cases would make the keyword not function properly.

After digging deeper, the bigger problem is that the material property editor uses the display name to enable the keyword, since the names didn't match (e.g. `A(1)` vs. `A_1_`) the keyword would never get set. This was the root cause with the duplicate names as one would have a display name of `a` but a reference name of `A_1`.

To fix this, enum keyword display names are now sanitized to match the same rules that the material editor expects, this way the same reference name is looked up. That is only allowing alpha numeric, spaces, and underscores.

---
### Testing status
- [x] Tested enums with duplicate display names: [`A`, `a`]
- [x] Partially invalid display names: `A(1)`
- [x] Empty display names: `""`
- [x] Whitespace display names: `" "`

---
### Comments to reviewers
While changing the rules for names could have the potential to break things, the rules are only changed for things that were already invalid hlsl identifiers. Anything that was valid before will have the same reference name and anything else didn't work.

Also, during investigation, I determined that display names that were empty or completely white space would break things. In this case, one entry would be missing (e.g. if you make: ["A", "", "C"] then what's displayed is ["A", "C"]).

2021-02-17 20:39 UTC, LandonTownsendUnity requested changes

2021-02-17 20:39 UTC, LandonTownsendUnity commented on com.unity.shadergraph/Editor/Drawing/Inspector/PropertyDrawers/ShaderInputPropertyDrawer.cs
> +                        Debug.LogWarning($"Display name '{displayName}' will create the reference name '{referenceName}' which conflicts with the existing display name '{duplicateEntry.displayName}'
This wording is a little big confusing, can you change it to something like
"Display name '{displayName}' will create the same reference name '{referenceName}' as the existing display name '{duplicateEntry.displayName}' at index {duplicateIndex}."

2021-02-17 21:19 UTC, jessebarker approved these changes
LGTM.

2021-02-23 20:09 UTC, LandonTownsendUnity approved these changes

2021-02-26 19:32 UTC, cdxntchou approved these changes

2021-02-26 19:32 UTC, cdxntchou commented
Little bit non-ideal that it only shows the error in the console.   But it's such a low-occurrence thing, most users are unlikely to ever run into it, so I think it's ok.

2021-02-26 19:37 UTC, merged