[VFX] Add support
Unity-Technologies/Graphics pull request #3598
Opened 2021-02-22 17:20 UTC by PaulDemeulenaere

### Purpose of this PR
Related to this [JIRA](https://jira.unity3d.com/secure/RapidBoard.jspa?rapidView=2762&projectKey=GVFXG&view=detail&selectedIssue=GVFXG-107)

![_material_offset](https://user-images.githubusercontent.com/22494706/108744721-90091780-753a-11eb-81fc-2081889d07cc.gif)

---
### Testing status
Yamato & Manual

---
### Comments to reviewers
N/A

2021-03-01 09:51 UTC, PaulDemeulenaere commented
Moved the JIRA to blocked awaiting for C++ (see [here](https://jira.unity3d.com/browse/GVFXG-107?focusedCommentId=1980831&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1980831))
⏳

2021-03-18 13:35 UTC, JordanL8 commented on com.unity.visualeffectgraph/Documentation~/Context-OutputSharedSettings.md
> +| **Material Offset**         | Int      | **(Inspector)** Apply an offset the render ordering. This setting corresponds to the Material [Sorting Priority](https://docs.unity3d.com/Packages/com.unity
``` **(Inspector)** An offset Unity applies to the rendering order. This setting corresponds to the Material [Sorting Priority](https://docs.unity3d.com/Packages/com.unity.render-pipelines.high-definition@latest?subfolder=/manual/Renderer-And-Material-Priority.html) in HDRP and Material [Priority](https://docs.unity3d.com/Packages/com.unity.render-pipelines.universal@latest?subfolder=/manual/simple-lit-shader.html) in URP. It is equivalent to modifying the [Material.renderQueue](https://docs.unity3d.com/ScriptReference/Material-renderQueue.html) property. This value can be negative or positive. URP clamps this value between -50 and 50, and HDRP clamps this value between -100 and 100. ```

2021-03-18 13:40 UTC, JordanL8 requested changes

2021-03-18 13:40 UTC, JordanL8 commented on com.unity.visualeffectgraph/Documentation~/Context-OutputSharedSettings.md
> +| **Material Offset**         | Int      | **(Inspector)** Apply an offset the render ordering. This setting corresponds to the Material [Sorting Priority](https://docs.unity3d.com/Packages/com.unity
``` **(Inspector)** An offset Unity applies to the rendering order. This setting corresponds to the Material [Sorting Priority](https://docs.unity3d.com/Packages/com.unity.render-pipelines.high-definition@latest?subfolder=/manual/Renderer-And-Material-Priority.html) in HDRP and Material [Priority](https://docs.unity3d.com/Packages/com.unity.render-pipelines.universal@latest?subfolder=/manual/simple-lit-shader.html) in URP. It is equivalent to modifying the [Material.renderQueue](https://docs.unity3d.com/ScriptReference/Material-renderQueue.html) property. This value can be negative or positive. URP clamps this value between -50 and 50, and HDRP clamps this value between -100 and 100. ```

2021-03-26 11:49 UTC, sebastienlagarde commented
@PaulDemeulenaere  hey, what is the status on this one?

2021-03-26 13:00 UTC, PaulDemeulenaere commented
> @PaulDemeulenaere hey, what is the status on this one?

I'm waiting for trunk fix about build to double check the status of newly introduced screenshot before mark it as "ready to review".
@vlad-unity is going to tackle this verification.
I will have to apply documentation update as well.

2021-03-26 19:01 UTC, VladNeykov reviewed
Hi, it's looking good, FTP passes, no issues found.
I've jotted down a couple of UX questions on the [test doc](https://docs.google.com/document/d/12ZRCTFbeWNWGbJEbHpixNGqf9VDeLJvpwuqx8R8IHtU/edit#).

2021-03-30 08:17 UTC, PaulDemeulenaere commented on com.unity.visualeffectgraph/Documentation~/Context-OutputSharedSettings.md
> +| **Material Offset**         | Int      | **(Inspector)** Apply an offset the render ordering. This setting corresponds to the Material [Sorting Priority](https://docs.unity3d.com/Packages/com.unity
Fixed at https://github.com/Unity-Technologies/Graphics/pull/3598/commits/217bfbf6d82ce287cc997929e24fb8e20cec513d

2021-03-30 08:27 UTC, PaulDemeulenaere commented
@vlad-unity 

1) Add delayed on material offset at https://github.com/Unity-Technologies/Graphics/pull/3598/commits/70597fac82a211c6f3dea7b928835371a58a034d
![_delayed_field](https://user-images.githubusercontent.com/22494706/112957541-ce00e900-9141-11eb-9aea-8da03668b411.gif)

2) About `Material Offset for Additive`, HDRP doesn't filter the sorting priority in case of additive :
![_additive_sorting](https://user-images.githubusercontent.com/22494706/112958012-4ebfe500-9142-11eb-874b-ae4f3a0dda7f.gif)

2021-03-30 13:08 UTC, JordanL8 approved these changes

2021-03-30 13:58 UTC, VladNeykov approved these changes
LGTM

2021-04-07 09:45 UTC, julienf-unity approved these changes

2021-04-07 10:56 UTC, PaulDemeulenaere commented
Thanks for the review, I'm updating internal screenshot with this [yamato job](https://yamato.cds.internal.unity3d.com/jobs/339-ScriptableRenderPipelinePrivate/tree/vfx%252Ffeature%252Fmaterial-sorting-support) with this [PR](https://github.cds.internal.unity3d.com/unity/ScriptableRenderPipelinePrivate/pull/153)
Re-running public VFX verification before merge ⏳

2021-04-07 15:30 UTC, PaulDemeulenaere commented
The failure about `HDRP_Hybrid on Win_DX11_playmode_mono_Linear` doesn't seem related to this change.
Ready to be merge, the internal PR has been merged [here](https://github.cds.internal.unity3d.com/unity/ScriptableRenderPipelinePrivate/commit/d2d5704209921506ab4df9c9a121cb4f145d9a34)

2021-04-07 15:30 UTC, merged