Fixed warnings for Universal2D.hlsl
Unity-Technologies/Graphics pull request #3778
Opened 2021-03-05 06:45 UTC by unity-cchu

### Purpose of this PR
To fix warnings in Universal2D.hlsl

---
### Testing status
Ran graphics tests

2021-03-05 09:40 UTC, phi-lira commented on com.unity.render-pipelines.universal/Shaders/Utils/Universal2D.hlsl
> +    half2  uv        : TEXCOORD0;
Careful with this, depending on your texture resolution you won't have enough precision to store uv coord in half precision.

2021-03-08 07:07 UTC, ellioman requested changes

2021-03-08 07:07 UTC, ellioman commented on com.unity.render-pipelines.universal/Shaders/Utils/Universal2D.hlsl
> +    half4 texColor = SAMPLE_TEXTURE2D(_BaseMap, sampler_BaseMap, input.uv);
This code still gives us a warning as SAMPLE_TEXTURE2D returns a float4.
So you either need to have texColor as float4 or do a cast.

2021-04-15 10:58 UTC, simon-engelbrecht-soerensen approved these changes

2021-05-07 23:39 UTC, closed without merging