Added a fallback for the ray traced directional shadow in case of a transmission (case 1307870).
Unity-Technologies/Graphics pull request #3882
Opened 2021-03-15 21:03 UTC by anisunity

https://fogbugz.unity3d.com/f/cases/1307870/
Currently the screen space shadow was overriding the whole on screen shadow, which was an issue in the case of transmitted shadows (sun light).  

This fixes the behavior and falls back on the rasterized shadow (only in the case of ray traced, the behavior was already correct for screen space shadow.

Testing status
Added a test to cover the new behavior. 
Made sure the issue doesn't happen anymore on the original dataset

2021-03-16 12:09 UTC, anisunity commented
Did the changes requested by @sebastienlagarde

2021-03-16 18:21 UTC, sebastienlagarde approved these changes

2021-03-16 18:32 UTC, sebastienlagarde commented on com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.hlsl
> +            bool visibleLight = dot(bsdfData.normalWS, -light.forward) > 0.0;
can you factor all those conditions in a single function so we can share the code between both call?  thanks

2021-03-22 10:15 UTC, remi-chapelain requested changes
Forgot to take a look last week sorry !

Quickly took a look at the test scene, thanks for adding it ! ✔️ 
Tested double sided quad / alpha clipped transmission and multi mat to be sure ✔️ 

I have some small concerns : 
- Is it expected that punctual lights don't have this behavior at all meaning we can't see the shadows through the translucent object ? 
- Can we add this info to the documentation about the new fallback behavior for dir light ? Maybe @JordanL8 can take care of it ? 
- I also don't think this is mentioned in doc too for Area light (that have the same behavior as the dir light in that case)

2021-03-22 23:42 UTC, anisunity commented
@sebastienlagarde merged hd/bugfix into this PR and did the changes you requested

2021-03-23 19:50 UTC, sebastienlagarde commented
@remi-chapelain if you can recheck, thanks

2021-03-24 10:27 UTC, remi-chapelain requested changes
Did a quick re-check as requested and everything is still working as expected. ✔️ 

I'm just waiting on the quick changes to the doc to be sure theses behavior are noted somewhere : 
- Punctual lights don't have this behavior, not implemented yet
- Area light and directional will fallback to raster shadow in the case of transmission.

2021-03-24 14:59 UTC, Vic-Cooper commented
Documented this fix in the Light Types guide section of Light-Components.

2021-03-24 15:28 UTC, remi-chapelain reviewed
Thanks for adding it to the doc, but not to be THAT guy, but does that makes more sense to have that on the [ray traced shadows side]( https://docs.unity3d.com/Packages/com.unity.render-pipelines.high-definition@10.4/manual/Ray-Traced-Shadows.html) of the doc ?
To me, people struggling to understand this will look on the raytracing side first, and people who read it on the "light" side will never remember it and/or wonder why we talk about this really specific edge case here ?

2021-03-24 16:08 UTC, Vic-Cooper commented
You're totally right, this information should be there! I'll make that change now :)

2021-03-24 16:25 UTC, remi-chapelain approved these changes
Thanks ! Looks good to me 💚

2021-03-24 19:01 UTC, merged