Add an LTC fitting tool and supporting all the BRDFs available in HDRP.
Unity-Technologies/Graphics pull request #3957
Opened 2021-03-22 21:39 UTC by anisunity

This PR adds a tool to generate the LTC tables for various lighting models (including the possibility for users to generate theirs). The code is greatly inspired by this https://github.com/selfshadow/ltc_code

The tool can be found in Window - > Rendering -> HDRP LTC Fitting Tool

Most of the LTC tests do not fail as a managed to generate tables that are extremely close to the previous ones

Here is the list of the current set of brdfs that are "supported"
        GGX,
        DisneyDiffuse,
        Charlie,
        FabricLambert,
        KajiyaKaySpecular,
        KajiyaKayDiffuse,
        CookTorrance,
        Ward,
        OrenNayar,

Testing Status
All DXR tests are green locally.
All HDRP tests are green except for the following:
- The two new tests that were added in this PR
- AxF_SVBRDF that fails for me on master aswell.
- Enlighten Area light that fails for epsilon changes.

@remi-chapelain A new tests for area lights and AxF needs to be added.

2021-03-22 21:41 UTC, anisunity commented
@JordanL8 i guess we need docs for this somewhere

2021-03-23 10:22 UTC, sebastienlagarde commented on com.unity.render-pipelines.high-definition/Editor/Material/LTCAreaLight/LTCTableGeneratorEditor.cs
> +        [MenuItem("Window/Rendering/HDRP LTC Tables Generator")]
check with Alex for naming

2021-03-25 12:09 UTC, sebastienlagarde approved these changes

2021-03-25 14:44 UTC, remi-chapelain commented
Note for @Vic-Cooper to remove those limitations from theses 5 pages in the doc : 
- [Cotton/Wool Shader](https://docs.unity3d.com/Packages/com.unity.render-pipelines.high-definition@10.4/manual/cotton-wool-shader.html#limitations)
- [Silk Shader](https://docs.unity3d.com/Packages/com.unity.render-pipelines.high-definition@10.4/manual/silk-shader.html#limitations)
- [Hair Shader](https://docs.unity3d.com/Packages/com.unity.render-pipelines.high-definition@10.4/manual/hair-shader.html#limitations)
- [Fabric Master Stack](https://docs.unity3d.com/Packages/com.unity.render-pipelines.high-definition@10.4/manual/master-stack-fabric.html#limitations)
- [Hair Master Stack](https://docs.unity3d.com/Packages/com.unity.render-pipelines.high-definition@10.4/manual/master-stack-hair.html#limitations)

2021-03-25 17:09 UTC, remi-chapelain reviewed
Haven't finished testing but I'm not sure it's expected to be able to put negative value in the sample count field
![image](https://user-images.githubusercontent.com/57442369/112514082-3c862580-8d95-11eb-975d-a9404c37fa3d.png)

2021-03-25 17:37 UTC, sebastienlagarde commented
> Haven't finished testing but I'm not sure it's expected to be able to put negative value in the sample count field
> ![image](https://user-images.githubusercontent.com/57442369/112514082-3c862580-8d95-11eb-975d-a9404c37fa3d.png)

Not expected, but not a good deal either. I will fix it

2021-03-25 18:14 UTC, sebastienlagarde commented
I have updated the doc, the screenshots and disable the access to the tool, we are not ready yet to expose it (it is useless for users to regenerate table in state, we are using it internally only for now). PR is ready

2021-03-26 10:16 UTC, remi-chapelain approved these changes
Tested multiple projects with area lights, found nothing unexpected. 
Tested that Hair / Fabric are now properly supported with area light
Tested area light rectangle shadow. 

Duplicated the 1451_AxF test to add area lights for coverage
![1451_AxF_SVBRDF_AreaLights](https://user-images.githubusercontent.com/57442369/112616852-84a05900-8e24-11eb-8e41-377fdcf8ce25.png)

Modified the 2402_Area_Rect_Shadows to add materials (fabric, hair, eye, axf) to test that they are properly receiving shadows

![2402_Area_Rect_Shadow](https://user-images.githubusercontent.com/57442369/112616964-a4d01800-8e24-11eb-92df-f2268526eb6c.png)

[Relaunched yamato](https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/HDRP%252Fltc-fitting-brdf/.yamato%252Fall-hdrp.yml%2523PR_HDRP_trunk/6004213/job) to regenerate those screenshots.

2021-03-26 11:33 UTC, Vic-Cooper requested changes
Minor adjustments to the whats new and changelog pages. Thanks for removing the limitations :)

2021-03-26 11:33 UTC, Vic-Cooper commented on com.unity.render-pipelines.high-definition/Documentation~/whats-new-12.md
> +Area lights are now correctly supported for Fabric and Hair master node as well as for AxF shader.
The AxF shader and Fabric and Hair master nodes now correctly support Area lights.

2021-03-26 11:33 UTC, Vic-Cooper commented on com.unity.render-pipelines.high-definition/CHANGELOG.md
- Added LTC Fitting tools for all BRDFs that HDRP supports.
- Added Area Light support for Hair and Fabric master nodes.
- Improved lighting models for AxF shader area lights.

2021-03-26 11:41 UTC, sebastienlagarde commented
doc feedback adressed

2021-03-29 08:42 UTC, Vic-Cooper approved these changes
Docs changes addressed - approved!

2021-03-29 08:45 UTC, merged