X pipeline/sorting priority
Unity-Technologies/Graphics pull request #3966
Opened 2021-03-23 11:37 UTC by alex-vazquez

### Purpose of this PR

[JIRA](https://jira.unity3d.com/browse/XPIPELINE-89)

Unification of the sorting priority property for both pipelines

![image](https://user-images.githubusercontent.com/76204843/112129571-d5674600-8bc7-11eb-8571-4fb675e5281d.png)

---
### Testing status
HDRP:
- Check that the UI clamps the values between the new ranges
- Check old material with value outside the range
- Check that the property is only shown with the surface type is advanced
- Check the new location on shadergraph

URP:
- Check the field name

---
### Comments to reviewers
The RenderQueues mantain the same ranges, we are only limiting on UI. This makes us avoid remapping materials render queues if the sorting priority was higher than 50 or lower than -50

2021-03-26 08:28 UTC, jenniferd-unity approved these changes

2021-03-26 14:21 UTC, alex-vazquez commented
@sebastienlagarde . I've double check with @TheoWong-pixel  and we decided to leave the sorting priority where it is.

I've checked the sorting priorty saved with the old ranges, and even the inspector is opened, the value is not changed until the user modifies it. Do I still need to update the Upgrade Guide?

2021-03-29 17:56 UTC, sebastienlagarde commented
> @sebastienlagarde . I've double check with @TheoWong-pixel and we decided to leave the sorting priority where it was. Under the surface options and no in Advanced.
> 
> I've checked the sorting priorty saved with the old ranges, and even the inspector is opened, the value is not changed until the user modifies it. Do I still need to update the Upgrade Guide?

Ah good to heard. So yes, please add information in the upgrade guide to explain this behavior. But good to heard it will not break anything.

2021-03-29 17:56 UTC, sebastienlagarde approved these changes
Wiating for upgrade guide

2021-04-06 15:26 UTC, phi-lira commented
Btw since you are looking at this I think we should consolidate the tooltip as well. I recently found that the tooltip for URP contained wrong information. Elements with lower priority are renderer first (priority is somewhat confusing term imo)
 
<img width="488" alt="Screenshot 2021-03-18 at 16 00 34" src="https://user-images.githubusercontent.com/7453395/113736153-27968400-96fd-11eb-8d3f-8ea5d722969b.png">

2021-04-06 15:29 UTC, phi-lira commented on com.unity.render-pipelines.universal/Editor/ShaderGUI/BaseShaderGUI.cs
>                  "Determines the chronological rendering order for a Material. High values are rendered first.");
While you are looking at it we should fix this tooltip. Materials with lower value are rendered first.

2021-04-07 08:41 UTC, alex-vazquez commented
@JordanL8 could you check the upgrade guide please? Thank you :)

2021-04-07 09:00 UTC, alex-vazquez commented
@Unity-Technologies/gfx-qa-hdrp team, could you do a quick check over a material with a transparent sorting priority saved with higher values and see that the values are not modified until you edit the property on the inspector?

@Unity-Technologies/gfx-qa-urp team, could you have a look at the name and the new tooltip?

Thank you awesome QA teams!

2021-04-07 10:52 UTC, RemyUnity commented
As well as consolidating the tooltip, wouldn't it be a good idea to consolidate the setting position in both pipelines ? It is in surface options for HDRP, but advanced for URP.

2021-04-07 10:57 UTC, alex-vazquez commented
> n surface options for HDRP, but advanced for URP.

On HDRP is really tight to the Transparent Surface Type, on URP is for all the materials, we thought to put it on advanced, as it is an advanced property but as the whole HDRP pipeline is advanced It make sense to leave it there with the change of the surface. 

Besides that, on URP we leave it on Advanced as I said it is an advanced option, that not every user will modify.

If you want more information, @TheoWong-pixel, can give you a UX point of view. Thank you for your heads up :)

2021-04-08 08:01 UTC, iM0ve approved these changes
I think the testing is sufficient for the change. Especially when RenderQueues ranges are the same and this is mostly a limitation on UI

2021-04-15 08:41 UTC, JordanL8 requested changes

2021-04-15 08:41 UTC, JordanL8 commented on com.unity.render-pipelines.high-definition/Documentation~/Upgrading-from-2021.1-to-2021.2.md
> +If you had materials with **Transparent Surface Type**, with a sorting priority that is excceding the new range of -50/50, you will need to remap them to the new range values. This will not affect yo
`From 2021.2, the range for **Sorting Priority** values has decreased from between -100 and 100 to between -50 and 50. If you used transparent materials (**Surface Type** set to **Transparent**) with a sorting priority lower than -50 or greater than 50, you must remap them to within the new range. HDRP does not clamp the Sorting Priority to the new range until you edit the Sorting Priority property.`

2021-04-15 08:43 UTC, JordanL8 approved these changes

2021-04-16 09:36 UTC, phi-lira approved these changes

2021-04-16 09:58 UTC, sebastienlagarde approved these changes

2021-04-16 10:32 UTC, simon-engelbrecht-soerensen approved these changes
LGTM on URP

2021-04-19 08:36 UTC, merged