Hd/update wizard to handle quality asset
Unity-Technologies/Graphics pull request #4015
Opened 2021-03-26 14:42 UTC by RSlysz

### Purpose of this PR
Update of Wizard to better handle assets in Quality Settings
Fixed issue due to missing resource folder.
Fixed issue where DefaultVolumeProfile was checked against currentAsset instead of defaultAsset
Added checks on Global Settings
Remove the useless Populate/Reset (not really usefull since we don't have the custom scenes and duplicate with fixes under)
Updated documentation and added missing DXR update on documentation.
Added localization on each fields.
![RenderPipelineWizard1](https://user-images.githubusercontent.com/40034005/112647301-a4e20f00-8e48-11eb-960c-66ffaa56d9db.png)

---
### Testing status
Most of the tests have been done in prior 10.5 and 2021.1 branch for this update.

---
### Comments to reviewers
Separate PR will also target:
- 10.5: https://github.com/Unity-Technologies/Graphics/pull/3932 
- 2021.1/staging: https://github.com/Unity-Technologies/Graphics/pull/3974

@JordanL8 be cautious, most of the change in the doc is the same than other 2 PR but there is an additional check on **Assigned - HDRP Settings**

@jenniferd-unity please thorougly check at the change I had to do in the ched/fix methods regarding global settings and GraphicSettings to see if i had not do some strange stuff.

2021-03-29 10:19 UTC, remi-chapelain approved these changes
Did a quick smoke test (Fixing wizard on HDRP, HDRP + DXR), changed quality settings before and after fixing to make sure it retrieve the proper asset. ✔️ 

The rest has already been checked on [this backport PR ](https://github.com/Unity-Technologies/Graphics/pull/3932)

2021-03-29 11:32 UTC, jenniferd-unity approved these changes
Small suggestion for the doc

2021-03-29 11:32 UTC, jenniferd-unity commented on com.unity.render-pipelines.high-definition/Documentation~/Render-Pipeline-Wizard.md
> +- **Global:** settings in Unity Editor or in the [HDRP Asset](HDRP-Asset.md) set in Graphics Settings.
Could be changed to say
`settings in Unity Editor, [HDRP Global Settings](Default-Settings-Window.md), or Graphics Settings'  [HDRP Asset](HDRP-Asset.md)`

2021-03-29 17:06 UTC, sebastienlagarde approved these changes

2021-03-30 16:06 UTC, Vic-Cooper requested changes
Made some suggestions, please check them for technical accuracy.

2021-03-30 16:06 UTC, Vic-Cooper commented on com.unity.render-pipelines.high-definition/Documentation~/Render-Pipeline-Wizard.md
> +| **Assigned - HDRP Settings** | Checks to make sure you have assigned an **HDRenderPipelineGlobalSettings** to the **HDRP Settings** field (menu: **Edit** > **Project Settings** > **HDRP Graphics**)
Recommended change:

| **Assigned - Graphics** | Checks to make sure you have assigned an **HDRenderPipelineGlobalSettings** asset to the **HDRP Settings** field (menu: **Edit** > **Project Settings** > **HDRP Graphics**).<br />Press the **Fix** button to find and assign an available **HDRenderPipelineGlobalSettings** asset. If there isn't one available, Unity creates an **HDRenderPipelineGlobalSettings** in the **Default Resources Folder**.

2021-03-30 16:06 UTC, Vic-Cooper commented on com.unity.render-pipelines.high-definition/Documentation~/Render-Pipeline-Wizard.md
> +This tab provides all of the configuration options from the [HDRP tab](#HDRPTab) as well as extra configuration options to help you set your HDRP Project up to support virtual reality. If you can not
Recommended change: 

You can adjust the extra configuration options in the  **Global** scope.

2021-03-31 08:38 UTC, Vic-Cooper approved these changes
Thanks for making the changes! No further suggestions :)

2021-03-31 15:44 UTC, merged