[VFX] Add Graphics Buffer support
Unity-Technologies/Graphics pull request #4109
Opened 2021-04-07 16:16 UTC by PaulDemeulenaere

# **Please read the [Contributing guide](CONTRIBUTING.md) before making a PR.**

* Read the [Graphics repository & Yamato FAQ](http://go/graphics-yamato-faq).

### Checklist for PR maker
- [ ] Have you added a backport label (if needed)? For example, the `need-backport-*` label. After you backport the PR, the label changes to `backported-*`.
- [ ] Have you updated the changelog? Each package has a `CHANGELOG.md` file.
- [ ] Have you updated or added the documentation for your PR? When you add a new feature, change a property name, or change the behavior of a feature, it's best practice to include related documentation changes in the same PR. If you do add documentation, make sure to add the relevant Graphics Docs team member as a reviewer of the PR. If you are not sure which person to add, see the [Docs team contacts sheet](https://docs.google.com/spreadsheets/d/1rgUWWgwLFEHIQ3Rz-LnK6PAKmbM49DZZ9al4hvnztOo/edit#gid=1058860420).
- [ ] Have you added a graphic test for your PR (if needed)? When you add a new feature, or discover a bug that tests don't cover, please add a graphic test.

---
### Purpose of this PR
Why is this PR needed, what hard problem is it solving/fixing?

---
### Testing status
Describe what manual/automated tests were performed for this PR

---
### Comments to reviewers
Notes for the reviewers you have assigned.

2021-04-09 14:27 UTC, landonth commented
Suggestion to rename operator node from "Sample Graphics Buffer" to "Load Graphics Buffer." **Sample** implies texture interpolation which is impossible when reading from Graphics Buffer. **Load** is consistent with existing (discrete, integer indexed, no interpolate) behavior and naming of VFX nodes "Load Texture2D," "Load Texture3D," etc

Aside from consistency with VFX Graph's existing nodes and DirectX/Vulkan/OpenGL terminology, Sampling in computer graphics in general is primarily defined as an operation where "continuous functions (signals) are discretized via sampling" or "The process of mapping a continuous function
to a discrete one is called sampling." Whereas here with GraphicsBuffer, we are simply loading already discretized data --not sampling from any continuous space via a continous function or interpolation as the name strongly implies.

[https://doi.org/10.1007/978-3-642-27851-8_167-1](Subr K. (2015) Sampling Problems in Computer Graphics. In: Luo R. (eds) Encyclopedia of Color Science and Technology. Springer, Berlin, Heidelberg.)
[https://www.cs.rpi.edu/~cutler/classes/advancedgraphics/F05/lectures/20_sampling_aliasing.pdf](Sampling, Aliasing, & Mipmaps - CSCI-6962 Advanced Computer Graphics
Cutler)

2021-04-12 07:32 UTC, VladNeykov commented
Hi, dropping the WIP [test doc](https://docs.google.com/document/d/1lkQj67dt_kI6PpjS78UoPLlw8wbtvCQ5VabFFeG5r5w/edit).

2021-04-12 08:24 UTC, PaulDemeulenaere commented
> Suggestion to rename operator node from "Sample Graphics Buffer" to "Load Graphics Buffer." **Sample** implies texture interpolation or triangle surface interpolation which is not possible when reading custom data from a GraphicsBuffer. **Load** is consistent with existing (discrete, integer indexed, no interpolate) 1:1 data loading behavior and naming of VFX nodes "Load Texture2D," "Load Texture3D," etc. Distinct from nodes with floating point UV coordinate inputs like "Sample Texture2D," etc.
> 
> The only reason I can think of the keep the "Sample" name is if there is planned functionality for software interpolation built-in to the Sample Graphics Buffer node for certain common GraphicsBuffer data layouts. i.e. Triangle, Quad primitives, regular 1D, 2D, and 3D grids. In the same way that the Sample Mesh and Sample Skinned Mesh nodes can optionally sample vertex interpolated data from the triangle mesh surface. Is this the case?
> 
> This is probably well known to you, but I will cite my sources for completeness. Aside from consistency with VFX Graph's existing nodes and DirectX/Vulkan/OpenGL terminology, Sampling in computer graphics is primarily defined as an operation where "continuous functions (signals) are discretized via sampling" or "The process of mapping a continuous function to a discrete one is called sampling." Whereas here with GraphicsBuffer, we are (as far as I can tell) simply loading already discretized data --not sampling from a continuous space via a function or interpolation as the name strongly implies.
> 
> * [Subr K. (2015) Sampling Problems in Computer Graphics. In: Luo R. (eds) Encyclopedia of Color Science and Technology. Springer, Berlin, Heidelberg.](https://doi.org/10.1007/978-3-642-27851-8_167-1)
> * [Sampling, Aliasing, & Mipmaps - CSCI-6962 Advanced Computer Graphics Cutler](https://www.cs.rpi.edu/~cutler/classes/advancedgraphics/F05/lectures/20_sampling_aliasing.pdf)

Thanks for this feedback, adding a screenshot of other available nodes to illustrate :
![image](https://user-images.githubusercontent.com/22494706/114362875-1e336e80-9b78-11eb-88df-2b1d084a5d3f.png)

It has been named "Sample" because as you supposed, it's inspired from the "Sample Mesh" operator.

We could potentially provide two operators LoadGraphicsBuffer (using an unsigned integer) & SampleGraphicsBuffer (using a normalized float). By the way, the "addressing mode" (clamp/wrap/mirror) is missing in this first implementation (It has been pointed in this [document](https://github.com/Unity-Technologies/Graphics/pull/4109#issuecomment-817562938)).
I'm going to raise the naming concern with the team.

Thanks again !

2021-04-17 19:18 UTC, landonth commented
@PaulDemeulenaere Sounds great! Thanks so much for the detailed and thoughtful reply. ✨

2021-05-11 16:51 UTC, PaulDemeulenaere commented on com.unity.visualeffectgraph/Editor/Expressions/VFXExpressionBuffer.cs
> +        //TODOPAUL : Check code convention
Clean this TODOPAUL

2021-05-12 12:02 UTC, VladNeykov approved these changes
Looking good, no outstanding issues [test doc](https://docs.google.com/document/d/1lkQj67dt_kI6PpjS78UoPLlw8wbtvCQ5VabFFeG5r5w/edit) which can be looked at after the cutoff.

2021-05-12 15:32 UTC, PaulDemeulenaere commented on com.unity.visualeffectgraph/Runtime/Types/VFXTypes.cs
> +    [AttributeUsage(AttributeTargets.Struct, AllowMultiple = false)]
Missing doc here ⬇️

2021-05-18 09:58 UTC, JordanL8 requested changes

2021-05-18 09:58 UTC, JordanL8 commented on com.unity.visualeffectgraph/Runtime/Types/VFXTypes.cs
> +        /// <summary>Constructor of VFXType.</summary>
Initializes and returns an instance of VFXType.

2021-05-18 09:58 UTC, JordanL8 commented on com.unity.visualeffectgraph/Runtime/Types/VFXTypes.cs
> +        /// <summary>Usage of VFXType.</summary>
Options that define how the Visual Effect Graph can use a VFXType.

2021-05-18 09:58 UTC, JordanL8 commented on com.unity.visualeffectgraph/Runtime/Types/VFXTypes.cs
> +    /// Attribute to define a VFXType that will be usable in VFX Graph view.
Defines a VFXType that you can use in Node Workspace.

2021-05-18 09:58 UTC, JordanL8 commented on com.unity.visualeffectgraph/Runtime/Types/VFXTypes.cs
> +        /// <param name="usages">Usage of the VFXType.</param>
Flags that set how the Visual Effect Graph can use the VFXType.

2021-05-18 10:05 UTC, JordanL8 approved these changes

2021-05-20 07:35 UTC, PaulDemeulenaere commented
The needed change in C++ landed (see https://ono.unity3d.com/unity/unity/changeset/5676fbb6fbea) , launching Yamato on really last trunk : https://ono.unity3d.com/unity/unity/changeset/281d883a3da809b5684d799dea25486c92813302 (master didn't update the trunk head yet) on d9458b468bb11c271d7e3da350e66d46ba9bb317 ⏳

2021-05-21 06:46 UTC, julienf-unity approved these changes

2021-05-21 16:02 UTC, merged