Hd/update resources assets
Unity-Technologies/Graphics pull request #4180
Opened 2021-04-14 14:08 UTC by RSlysz

### Purpose of this PR
- Fix issue where the ResourceReloader don't reload null value at render pipeline construction anymore in HDRP.
- Prepared work to have a common ancestor for all Resource asset accross all SRP.
  - Currently it is used to have a shared inspector (all 3 assets kind in HDRP but URP can use it too later)
  - Also, it allow to have one unique EnsureAsset in HDRenderPipelineGlobalSettings in order to be sure all resource asset will always be loaded and checked the same way. (code factorization is done in this PR)
- Fix a wrong path in Reload attribute for **volumetricCloudMapGeneratorCS**
- Renamed all resource class for coherency.
- Fixed documentation link on the 3 resource asset that where either not set or set on wrong documentation page.
- Updated documentation that was not totally accurate on the default resource. It was letting think that resources asset were created in the project.

So the hierarchy is now done this way
![image](https://user-images.githubusercontent.com/40034005/114720559-67cab780-9d38-11eb-98ad-9f04dc096cad.png)

---
### Testing status
- Tested that Reload All button appears for all 3 resource asset in HDRP when in devloper mode only
- Tested that Reload All button manage to reload all resource for the 3 asset (just to remember: it nullify everything then call the ResourceReloader)
- Tested that nullifying a resource field, it is not reloaded instantly
- Tested that a null field is reloaded when render pipeline is reconstructed (forced a reconstruction by causing a domain reload)

---
### Comments to reviewers

2021-04-14 15:14 UTC, jenniferd-unity approved these changes
Just a note about the error message but otherwise great job!

2021-04-14 15:14 UTC, jenniferd-unity commented on com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipelineRuntimeResources.cs
> +            [Reload("Editor/Lighting/VolumetricClouds/CloudMapGenerator.compute")]
great catch!

2021-04-15 08:30 UTC, JordanL8 approved these changes

2021-04-15 08:32 UTC, JulienIgnace-Unity approved these changes

2021-04-15 10:53 UTC, TomasKiniulis requested changes
This seems to cause editor to break rendering with this:
`Could not load HDRenderPipelineRuntimeResources.
UnityEngine.StackTraceUtility:ExtractStackTrace () (at C:/buildslave/unity/build/Runtime/Export/Scripting/StackTrace.cs:37)
UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
UnityEngine.Logger:Log (UnityEngine.LogType,object)
UnityEngine.Debug:Assert (bool,string)
UnityEngine.Rendering.HighDefinition.HDRenderPipelineGlobalSettings:EnsureResources<UnityEngine.Rendering.HighDefinition.HDRenderPipelineRuntimeResources>...`

Also Player Resources and Volume profiles get set to None in HDRP settings. Reproduces after project is reopened.

2021-04-15 12:50 UTC, RSlysz commented
Above issue only appears when Runtime resource asset need to be reloaded. This happens on reimporting package like updating to a new version of HDRP.
This because I renamed it and forgot to update the path where we try reloading it. It should be good now.

2021-04-15 13:21 UTC, TomasKiniulis approved these changes
Works well now! Upgraded Spaceship, Amalienborg projects, did not run into any issues. Resources are correctly relinked when changed and editor is reopened.

2021-04-20 22:25 UTC, sebastienlagarde approved these changes

2021-04-20 22:26 UTC, sebastienlagarde commented
@RSlysz the PR cause a lot of GC alloc: https://yamato-artifactviewer.prd.cds.internal.unity3d.com/af6d3fd4-acde-4676-a483-bec17ac0b7fd%2Flogs%2FTestProjects%2FHDRP_Tests%2Ftest-results/TestReportV1.html

2021-04-22 21:59 UTC, merged