[XPipeline][URP]Light Inspector Drawer Skeleton
Unity-Technologies/Graphics pull request #4202
Opened 2021-04-16 09:27 UTC by alex-vazquez

---
### Purpose of this PR

Another step for Light Inspector Unification

[JIRA](https://jira.unity3d.com/browse/XPIPELINE-144)

---
### Testing status
Nothing to be tested, just the skeleton of the new inspector drawers

---
### Comments to reviewers
Adding this first while I wait other PR to be landed

2021-04-16 12:21 UTC, arttu-peltonen requested changes
Looks all right, but Yamato formatting needs fixing.

2021-04-16 12:21 UTC, arttu-peltonen commented on com.unity.render-pipelines.universal/Editor/Lighting/UniversalRenderPipelineLightUI.Drawers.cs
> +        static readonly ExpandedState<Expandable, Light> k_ExpandedState = new ExpandedState<Expandable, Light>(~-1, "URP");
What does this "~-1" mean here?

2021-04-19 05:31 UTC, arttu-peltonen approved these changes

2021-04-19 09:08 UTC, simon-engelbrecht-soerensen approved these changes

2021-04-20 12:50 UTC, merged