Fix RTHandle scale bias [1329977]
Unity-Technologies/Graphics pull request #4320
Opened 2021-04-27 04:06 UTC by skhiat

Fix https://fogbugz.unity3d.com/f/cases/1329977/

Reprostep:
On Camera:
![image](https://user-images.githubusercontent.com/55133890/116183596-793f9680-a71e-11eb-9b07-8f62e3e8ea12.png)

* Add an offset X of viewport rect.
* On SSR Enable 'PBR Accumulation'
* Increase the 'Max Ray Steps'
* On Game view increase the Accumulation factor

Before:
![Unity_KIciohDtbH](https://user-images.githubusercontent.com/55133890/116183542-59a86e00-a71e-11eb-9ce6-1df7bfde69d5.png)

After:
![Unity_09Qjj2PFKA](https://user-images.githubusercontent.com/55133890/116183559-62993f80-a71e-11eb-8727-fa14a41c65c8.png)

2021-04-27 08:24 UTC, JulienIgnace-Unity requested changes
This fix looks weird to me.
_RTHandleScaleHistory.zw / _RTHandleScaleHistory.xy does not really mean anything so I'm not sure how that works.
In theory there should be very little to do here:
- For current frame buffers, since we are using pixel coordinates, no scale should be applied as we render in the proper viewport already.
- For previous frame buffers, they may be a different size so pixel coordinates should be multiplied by _RTHandleScaleHistory.zw if they are history buffers or _RTHandleScale.zw if they are shared buffers.

2021-04-27 09:14 UTC, skhiat commented
> This fix looks weird to me.
> _RTHandleScaleHistory.zw / _RTHandleScaleHistory.xy does not really mean anything so I'm not sure how that works.
> In theory there should be very little to do here:
> 
> * For current frame buffers, since we are using pixel coordinates, no scale should be applied as we render in the proper viewport already.
> * For previous frame buffers, they may be a different size so pixel coordinates should be multiplied by _RTHandleScaleHistory.zw if they are history buffers or _RTHandleScale.zw if they are shared buffers.

[Fixed]

2021-04-27 09:16 UTC, JulienIgnace-Unity approved these changes

2021-04-28 11:06 UTC, iM0ve approved these changes
Looks good. Checking the repro case should be sufficient since it only affects SSR. I

2021-04-29 07:41 UTC, merged