Various fixes for Lens Flare
Unity-Technologies/Graphics pull request #4462
Opened 2021-05-06 09:17 UTC by skhiat

2021-05-11 13:08 UTC, RSlysz requested changes
Seams good.

Though, can you fix allowed range in property for the component?

2021-05-11 13:10 UTC, skhiat commented on com.unity.render-pipelines.core/Runtime/PostProcessing/LensFlareComponentSRP.cs
> +        public float maxAttenuationDistance = 100.0f;
Here it's not the range, but more about the default values.

2021-05-11 13:20 UTC, RSlysz approved these changes

2021-05-11 13:57 UTC, Vic-Cooper approved these changes
My comma needs are satisfied.

2021-05-12 12:31 UTC, sebastienlagarde commented
Added HDRP QA for awareness, sets of small fixes in particular in doc.

2021-05-12 13:18 UTC, TomasKiniulis reviewed
Hey @skhiat! Please add a brief explanation what was tested. Also, what does the "Use the ViewScene parameter 'Flares" change do?

2021-05-12 13:33 UTC, skhiat commented
> Hey @skhiat! Please add a brief explanation what was tested. Also, what does the "Use the ViewScene parameter 'Flares" change do?

The flare checkbox:
![SnRKJux305](https://user-images.githubusercontent.com/55133890/117983498-4fe65380-b337-11eb-8225-c5b8fbd34796.gif)

The other are fixes related the doc I shared with you.

2021-05-12 13:53 UTC, TomasKiniulis approved these changes

2021-05-12 15:04 UTC, merged