[HDRP][Path Tracing] Updated What's new 12 file
Unity-Technologies/Graphics pull request #4551
Opened 2021-05-17 12:43 UTC by eturquin

Mentioned support for AxF and Stacklit materials in "What's new in version 12" file (in addition to Fabric).

2021-05-17 14:29 UTC, sebastienlagarde reviewed
Please also update the feature list: https://docs.unity3d.com/Packages/com.unity.render-pipelines.high-definition@12.0/manual/HDRP-Features.html thanks

2021-05-17 15:35 UTC, eturquin commented
> Please also update the feature list: https://docs.unity3d.com/Packages/com.unity.render-pipelines.high-definition@12.0/manual/HDRP-Features.html thanks

Done; I also added a banner-style picture.

2021-05-18 09:39 UTC, Vic-Cooper requested changes
Suggested some changes.

2021-05-18 09:39 UTC, Vic-Cooper commented on com.unity.render-pipelines.high-definition/Documentation~/HDRP-Features.md
> +Path tracing supports almost all the rasterization engine [materials](#Material) listed above: it can render Lit, Layered Lit, Unlit, Stacklit, Fabric and AxF materials. Note that objects using non-H
Path tracing can render the following rasterization engine [Materials](#Material): 

- Lit
- Layered Lit
- Unlit,
- Stacklit
- Fabric
- AxF 

When path tracing is enabled, objects that use non-HDRP Materials won't appear in the final image.

2021-05-18 09:39 UTC, Vic-Cooper commented on com.unity.render-pipelines.high-definition/Documentation~/whats-new-12.md
HDRP path tracing now supports the following Materials:
- Fabric: Cotton/wool and silk variants.
- AxF: SVBRDF and car paint variants.
- Stacklit.

2021-05-19 15:29 UTC, sebastienlagarde approved these changes

2021-05-19 15:29 UTC, sebastienlagarde commented
As Vic's feedback have been adress, merging

2021-05-19 15:29 UTC, merged