Add Preview for LensFlare {Polygon and Circle}
Unity-Technologies/Graphics pull request #4560
Opened 2021-05-17 18:12 UTC by skhiat

Add Lens Flare preview:
![image](https://user-images.githubusercontent.com/55133890/118536321-de9a0c80-b74b-11eb-8c4d-0d42b2326f1f.png)
![image](https://user-images.githubusercontent.com/55133890/118536369-f83b5400-b74b-11eb-8d8f-34f14e29db51.png)
![image](https://user-images.githubusercontent.com/55133890/118536441-0b4e2400-b74c-11eb-8c02-0ce17ec9c2d1.png)

---
### Testing status
UI show only the thumbnail for LensFlare Circle and Polygon when it's collapsed.

2021-05-18 09:13 UTC, JulienIgnace-Unity approved these changes

2021-05-18 10:07 UTC, iM0ve requested changes
The PR quite simple, but found one case where it does not work. 
In the video, you can see I collapse the yellow circle element. This somehow messes up the ordering and the yellow circle thumbnail is now displayed for the second element. This is incorrect.


https://user-images.githubusercontent.com/36502659/118633307-0041d500-b7da-11eb-83e9-d83bea376985.mp4

2021-05-20 10:27 UTC, SeanPuller commented
Good work, it gives a much better indication of the elements

Bugs
1. Polygon Thumbnail Issues

https://user-images.githubusercontent.com/43151199/118962983-40ce5980-b966-11eb-9c4c-bfbf33df755d.mp4

2. inspector panel drives size and alignment of rendered shape in thumbnail

https://user-images.githubusercontent.com/43151199/118962839-1a102300-b966-11eb-9cc3-54828b9c46ab.mp4

2021-05-27 02:07 UTC, CertifiedRice approved these changes

2021-05-27 12:00 UTC, erikabar requested changes
I am getting shader error when opening a project in URP: 

> Shader error in 'Hidden/Core/LensFlareDataDrivenPreview': Couldn't open include file 'Packages/com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderVariables.hlsl'. at line 26
> 
> Compiling Fragment program
> Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP SHADER_API_DESKTOP UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_LIGHTMAP_RGBM_ENCODING
> Disabled keywords: FLARE_CIRCLE FLARE_POLYGON FLARE_INVERSE_SDF UNITY_NO_DXT5nm UNITY_FRAMEBUFFER_FETCH_AVAILABLE UNITY_ENABLE_NATIVE_SHADOW_LOOKUPS UNITY_METAL_SHADOWS_USE_POINT_FILTERING UNITY_NO_SCREENSPACE_SHADOWS UNITY_PBS_USE_BRDF2 UNITY_PBS_USE_BRDF3 UNITY_NO_FULL_STANDARD_SHADER UNITY_HARDWARE_TIER1 UNITY_HARDWARE_TIER2 UNITY_HARDWARE_TIER3 UNITY_COLORSPACE_GAMMA UNITY_HALF_PRECISION_FRAGMENT_SHADER_REGISTERS UNITY_LIGHTMAP_DLDR_ENCODING UNITY_LIGHTMAP_FULL_HDR UNITY_VIRTUAL_TEXTURING UNITY_PRETRANSFORM_TO_DISPLAY_ORIENTATION UNITY_ASTC_NORMALMAP_ENCODING SHADER_API_GLES30 UNITY_UNIFIED_SHADER_PRECISION_MODEL
>

2021-05-28 10:29 UTC, skhiat commented
> I am getting shader error when opening a project in URP:
> 
> > Shader error in 'Hidden/Core/LensFlareDataDrivenPreview': Couldn't open include file 'Packages/com.unity.render-pipelines.high-definition/Runtime/ShaderLibrary/ShaderVariables.hlsl'. at line 26
> > Compiling Fragment program
> > Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP SHADER_API_DESKTOP UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_LIGHTMAP_RGBM_ENCODING
> > Disabled keywords: FLARE_CIRCLE FLARE_POLYGON FLARE_INVERSE_SDF UNITY_NO_DXT5nm UNITY_FRAMEBUFFER_FETCH_AVAILABLE UNITY_ENABLE_NATIVE_SHADOW_LOOKUPS UNITY_METAL_SHADOWS_USE_POINT_FILTERING UNITY_NO_SCREENSPACE_SHADOWS UNITY_PBS_USE_BRDF2 UNITY_PBS_USE_BRDF3 UNITY_NO_FULL_STANDARD_SHADER UNITY_HARDWARE_TIER1 UNITY_HARDWARE_TIER2 UNITY_HARDWARE_TIER3 UNITY_COLORSPACE_GAMMA UNITY_HALF_PRECISION_FRAGMENT_SHADER_REGISTERS UNITY_LIGHTMAP_DLDR_ENCODING UNITY_LIGHTMAP_FULL_HDR UNITY_VIRTUAL_TEXTURING UNITY_PRETRANSFORM_TO_DISPLAY_ORIENTATION UNITY_ASTC_NORMALMAP_ENCODING SHADER_API_GLES30 UNITY_UNIFIED_SHADER_PRECISION_MODEL
> 
> also this error when creating a Lens Flare asset in URP:
> 
> > UnityException: FindShaderByName is not allowed to be called from a ScriptableObject constructor (or instance field initializer), call it in OnEnable instead. Called from ScriptableObject 'LensFlareDataSRPEditor'.
> > See "Script Serialization" page in the Unity Manual for further details.
> > UnityEngine.ResourcesAPI.FindShaderByName (System.String name) (at /Users/bokken/buildslave/unity/build/Runtime/Export/Resources/Resources.bindings.cs:65)
> > UnityEngine.Shader.Find (System.String name) (at /Users/bokken/buildslave/unity/build/Runtime/Export/Shaders/Shader.bindings.cs:31)
> > UnityEditor.Rendering.LensFlareDataSRPEditor..cctor () (at /Users/erikab/Documents/Github/Graphics/com.unity.render-pipelines.core/Editor/PostProcessing/LensFlareDataSRPEditor.cs:124)
> > Rethrow as TypeInitializationException: The type initializer for 'UnityEditor.Rendering.LensFlareDataSRPEditor' threw an exception.
> > UnityEditor.UIElements.InspectorElement+<>c__DisplayClass59_0.b__0 () (at /Users/bokken/buildslave/unity/build/ModuleOverrides/com.unity.ui/Editor/Inspector/InspectorElement.cs:625)
> > UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&) (at /Users/bokken/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:189)

[Fixed]

2021-05-28 15:45 UTC, RSlysz requested changes

2021-05-28 15:45 UTC, RSlysz commented on com.unity.render-pipelines.core/Editor/PostProcessing/LensFlareResource/TintedTexture.shader
> +Shader "Hidden/Core/TintedTexture"
This file and the meta is not needed anymore. Please remove it :)

2021-06-01 11:42 UTC, iM0ve approved these changes
Updated my review above. All issues fixed or addressed

2021-06-01 12:58 UTC, RSlysz approved these changes

2021-06-01 13:35 UTC, eh-unity approved these changes
Seems ok. Minor comments mostly about code readability for someone who doesn't know the implementation.

2021-06-07 15:54 UTC, RemyUnity commented
Requesting a re-review from @erikabar or URP QA following Soufiane's fix : https://github.com/Unity-Technologies/Graphics/pull/4560#issuecomment-850321365

2021-06-07 17:06 UTC, skhiat commented on com.unity.render-pipelines.core/Editor/PostProcessing/LensFlareDataSRPEditor.cs
> +            float cos0 = flareData0.x;
More cos_theta, sin_theta.

2021-06-09 17:05 UTC, erikabar approved these changes
Tested URP, replicated all tests HDRP QA covered. In addition, tested removing array elements + undoing which resulted in ArgumentOutOfRange exception and the list is broken until you deselect the Lens Flare asset and select it again. This will be addressed in another PR.

2021-06-09 17:09 UTC, merged