[LensFlare] Fix thumbnail stretch and tooltip
Unity-Technologies/Graphics pull request #4622
Opened 2021-05-25 11:27 UTC by skhiat

Fix change tooltip and limit the stretch to have the thumbnail always visible:

Tooltip:
https://docs.google.com/document/d/1AFL10SqfHy_rMv-mR9mccV0P7nxWhxd2-vK_X5ry7yM/edit#bookmark=kix.tnmc5gobg4pr

Stretch:
https://docs.google.com/document/d/1AFL10SqfHy_rMv-mR9mccV0P7nxWhxd2-vK_X5ry7yM/edit#bookmark=kix.tnmc5gobg4pr

Test:
Image thumbnail with large ratio 'Scale': 1x50 and 1x100, 1x1000 should have the same thumbnail

2021-05-25 13:04 UTC, Vic-Cooper requested changes

2021-05-25 13:04 UTC, Vic-Cooper commented on com.unity.render-pipelines.core/CHANGELOG.md
>  - LensFlare (SRP) can be now disabled per element
Add a full stop to the two points above.

2021-05-26 10:17 UTC, iM0ve approved these changes
Minor cosmetic change only affecting lens flare inspector. Should be safe.

2021-05-27 02:01 UTC, CertifiedRice approved these changes

2021-05-31 16:43 UTC, sebastienlagarde approved these changes

2021-05-31 16:44 UTC, sebastienlagarde commented
This PR is clean, stuff have move in other PR, merging.

2021-05-31 16:44 UTC, merged