Add Volumetric Cloud Compatibility with MSAA [Recreated]
Unity-Technologies/Graphics pull request #4635
Opened 2021-05-25 17:19 UTC by johnpars

### Purpose of this PR

Fix case: https://fogbugz.unity3d.com/f/cases/1327436/

Volumetric Clouds will fail in the case of MSAA color target. This is due to the in-place blending operation that occurs on the upscaling + combine pass (which can't be done on an MSAA target). This PR will move that combine to a subsequent pass after the upscaling, and instead do the blending via the hardware on the MSAA target. 

Volumetric clouds now work in both scenarios:

No MSAA:
![image](https://user-images.githubusercontent.com/28882975/116302781-9badd000-a76f-11eb-9f53-e7cb75d1c82b.png)

MSAA:
![image](https://user-images.githubusercontent.com/28882975/116302945-c861e780-a76f-11eb-9249-dc677685f0d9.png)

---
### Testing status
- I locally tested switching the number of MSAA samples on different graphics APIs. 
- I also ensured that the hardware blending operation produces the exact same result as when it is done in the CS pass. 
- [Yamato](https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/HDRP%252Ffix-1327436)

---
### Comments to reviewers
Note: This PR is a recreation of #4345, which got mangled due do a deletion of hd/bugfix. The branch was also pretty far behind master (and volumetric clouds received various updates in the meantime), so I did a fresh branch off from master and cherry picked the work from the original branch.

2021-05-31 13:25 UTC, anisunity requested changes
The structure is fine, some changes are required

2021-05-31 13:25 UTC, anisunity commented on com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/HDRenderPipeline.VolumetricClouds.cs
> +            m_CloudCombinePass = CoreUtils.CreateEngineMaterial(defaultResources.shaders.volumetricCloudsCombinePS);
Missing release

2021-05-31 13:25 UTC, anisunity commented on com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricCloudsCombine.shader
> +                return LOAD_TEXTURE2D_X(_VolumetricCloudsUpscaleTextureRW, input.positionCS.xy);;
extra ;

2021-05-31 13:25 UTC, anisunity commented on com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/VolumetricClouds.compute
> +#pragma multi_compile _ ENABLE_MSAA
Why not simply have USE_INTERMEDIATE_BUFFER as the multi compile and add that extra intermediate define?

2021-05-31 13:25 UTC, anisunity commented on com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/HDRenderPipeline.VolumetricClouds.cs
> +                        TraceVolumetricClouds(ctx.cmd, data.needsTemporaryBuffer, data.cloudCombinePass, data.parameters,
These should be part of the parameters structure

2021-05-31 13:25 UTC, anisunity commented on com.unity.render-pipelines.high-definition/Runtime/Lighting/VolumetricLighting/HDRenderPipeline.VolumetricClouds.cs
> +        static void TraceVolumetricClouds(CommandBuffer cmd, bool needsTemporaryBuffer, Material combineCloudsPass, VolumetricCloudsParameters parameters,
See other comment

2021-06-07 11:59 UTC, anisunity approved these changes
Looks good to me after the changes!

2021-06-07 12:00 UTC, anisunity commented
@johnpars @remi-chapelain we need a new test to cover this!

2021-06-07 12:10 UTC, sebastienlagarde approved these changes

2021-06-07 12:12 UTC, anisunity commented
@sebastienlagarde let's not merge until we have a test

2021-06-07 16:13 UTC, sebastienlagarde commented
Discussed with John, He will do a separate PR with those test:

A runtime 004 with: volumetric cloud (with planar reflection for cloud), physically based sky, shadow matte, cluster decal (decal on transparent) with decal angle fade + decal with both view bias and depth bias + lens flare when it will be available.
And a runtime 05 with: HDRI sky with distortion layer, SSGI + force forward emissive + area light on hair, fabric, eye, lit + Parallax occlusion mapping with the conservative depth option

2021-06-08 07:43 UTC, sebastienlagarde commented
@jans is adding test in a separate PR.

2021-06-08 07:43 UTC, merged