Fixed a case where camere dimension can be zero
Unity-Technologies/Graphics pull request #4684
Opened 2021-05-27 12:19 UTC by lukaschod

### Purpose of this PR
Fixed a case where camere dimension can be zero. [case 1321168]

### Testing status
Tested with project in bug case.

2021-05-31 09:13 UTC, martint-unity requested changes

2021-05-31 09:13 UTC, martint-unity commented on com.unity.render-pipelines.universal/CHANGELOG.md
> +- Fixed a case where camere dimension can be zero. [case 1321168](https://issuetracker.unity3d.com/issues/urp-attempting-to-get-camera-relative-temporary-rendertexture-is-thrown-when-tweening-the-vie
camera instead of camere

2021-05-31 10:03 UTC, lukaschod commented on com.unity.render-pipelines.universal/CHANGELOG.md
> +- Fixed a case where camere dimension can be zero. [case 1321168](https://issuetracker.unity3d.com/issues/urp-attempting-to-get-camera-relative-temporary-rendertexture-is-thrown-when-tweening-the-vie
fixed

2021-05-31 13:38 UTC, erikabar approved these changes

2021-06-01 09:26 UTC, martint-unity approved these changes
LGTM

2021-06-01 10:00 UTC, merged