Add import dialog to add a new diffusion profile to the global settings
Unity-Technologies/Graphics pull request #4743
Opened 2021-06-01 16:23 UTC by FrancescoC-unity

Addressing https://unity.slack.com/archives/C6Y79CZM0/p1621941147179000 

This PR introduces a dialog on import of a material with a diffusion profile. The  user can then add a diffusion profile automatically to the global settings if there is space for it. 

https://user-images.githubusercontent.com/43168857/120357907-39179900-c306-11eb-83b3-77e6dbe8d7d2.mp4

Added Vic as I am not sure the wording on the dialog box is good enough :-D 

**What did I test**: can see the video above, I also tested that an already added profile doesn't prompt a dialog box and if there is no space in the diffusion profile list similarly no dialog is displayed.

2021-06-01 16:42 UTC, remi-chapelain commented
Dumb question, did you try with a SG material ? Does it works the same ? 
meaning material.HasProperty("_DiffusionProfileAsset") will return true aswell ?

2021-06-01 19:09 UTC, FrancescoC-unity commented
> Dumb question, did you try with a SG material ? Does it works the same ?
> meaning material.HasProperty("_DiffusionProfileAsset") will return true aswell ?

Not a dumb question at all! 
Tried and works just fine

2021-06-02 09:39 UTC, remi-chapelain requested changes
Quickly tested with importing material samples since there's 7 different diff profile there. 

And the only thing that fail is for Eye shader. There's this node that takes 2 diff profile in input that are not included in the batch in material importer. Is there something we can do about this since this is node accesible by everyone in utility SG nodes ? 

![image](https://user-images.githubusercontent.com/57442369/120456882-4b411800-c396-11eb-98d2-3fa4444063a8.png)

Also, since there's an upper limit of diffusion profile that can be added (weirdly 15), when your list is nearly full, when importing new materials with new diff profile, the new one gets added and then when the list is full, the rest are just skipped without info, is there a way to have either some sort of pop up telling you that the list is full, or a warning for each diffusion profile skipped and the reason why, for the users to know that something just failed silently ? :)

2021-06-02 09:43 UTC, FrancescoC-unity commented
> Quickly tested with importing material samples since there's 7 differents diff profile there.
> 
> And the only thing that fails is for Eye shader. There's this node that takes 2 diff profile in input that are not included in the batch in material importer. Is there something we can do about this since this is node accessible by everyone in utility SG nodes ?
> 
> ![image](https://user-images.githubusercontent.com/57442369/120456882-4b411800-c396-11eb-98d2-3fa4444063a8.png)
> 
> Also, since there's an upper limit of diffusion profile that can be added (weirdly 15), when your list is nearly full, when importing new materials with new diff profile, the new one gets added and then when the list is full, the rest are just skipped without info, is there a way to have either some sort of pop up telling you that the list is full, or a warning for each diffusion profile skipped and the reason why, for the users to know that something just failed silently ? :)
> 
> Thanks !

Oh didn't know about the Eye diffusion profiles, I can look into that later on today. 

Regarding the silently fail, I thought about that but then if you load a lot of assets, you'll end up with potentially a lot of dialog stopping the process saying the same thing which sounds annoying.

I guess what I can do is have a single dialog saying "Diffusion profile don't fit anymore, anything imported from now on will not be added to settings" ?

2021-06-02 09:47 UTC, Vic-Cooper requested changes
One small adjustment to the changelog.

2021-06-02 09:47 UTC, Vic-Cooper commented on com.unity.render-pipelines.high-definition/CHANGELOG.md
> +- Added a dialog box on import to add a diffusion profile to the global settings.
Tweaked for clarity: 

Added a dialog box when you import a Material that has a diffusion profile to add the diffusion profile to global settings.

2021-06-02 10:13 UTC, remi-chapelain commented
> I guess what I can do the warning at the end of process in the console.

I am fine with this solution, I agree, it can be hassle when importing huge asset pack !

2021-06-02 15:00 UTC, remi-chapelain approved these changes
Issues have been addressed :), approving ✔️

2021-06-02 16:47 UTC, alelievr approved these changes

2021-06-07 20:09 UTC, sebastienlagarde approved these changes

2021-06-07 20:10 UTC, sebastienlagarde commented
note to self: retarget to master once hd/bugfix is merge

2021-06-07 23:04 UTC, sebastienlagarde commented
for unknow reasins it break test package: https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/HDRP%252Fdiffusion-profile-import-add/.yamato%252F_projectcontext.yml%2523test_all_project_OSX_trunk/7157649/job/artifacts

2021-06-08 07:20 UTC, FrancescoC-unity commented
> for unknow reasins it break test package: https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/HDRP%252Fdiffusion-profile-import-add/.yamato%252F_projectcontext.yml%2523test_all_project_OSX_trunk/7157649/job/artifacts

I'll check!

2021-06-08 10:34 UTC, Vic-Cooper approved these changes
Looks good :)

2021-06-08 12:36 UTC, sebastienlagarde commented
it works, thanks :)

2021-06-08 12:37 UTC, merged