Add tooltips to Rendering Debugger (HDRP & URP)
Unity-Technologies/Graphics pull request #4757
Opened 2021-06-02 13:03 UTC by arttu-peltonen

### Purpose of this PR
Rendering Debugger window was missing tooltips for both HDRP and URP. This PR adds them.

---
### Testing status
Checked that the tooltips are visible in the editor.

2021-06-08 11:53 UTC, erikabar approved these changes

2021-06-08 12:12 UTC, arttu-peltonen commented
This is still waiting on some HDRP tooltips to be written. @Vic-Cooper please let me know when it's ready from your end, and I'll add them too :)

2021-06-08 13:24 UTC, Vic-Cooper requested changes
Suggested some changes to the tooltips :)

2021-06-08 13:24 UTC, Vic-Cooper commented on com.unity.render-pipelines.universal/Runtime/Debug/DebugDisplaySettingsMaterial.cs
> +            public static readonly NameAndTooltip ValidationPreset = new() { name = "Validation Preset", tooltip = "Validate through the use of a predetermined list of preset surfaces and inputs base
I think "preset" negates "predetermined" - all presets are predetermined :D. Suggestion:

"Validate using a list of preset surfaces and inputs based on real-world surfaces."

2021-06-08 15:38 UTC, JulienIgnace-Unity approved these changes

2021-06-15 09:27 UTC, lukaschod approved these changes

2021-06-15 12:14 UTC, ellioman approved these changes

2021-06-16 10:40 UTC, arttu-peltonen commented on com.unity.render-pipelines.universal/Runtime/Debug/DebugDisplaySettingsMaterial.cs
> +            public static readonly NameAndTooltip MetallicMaxValue = new() { name = "Max Value", tooltip = "Any values set above this field will be considered invalid and will appear blue on screen."
Thanks! Fixed this and all others below as requested.

2021-06-16 18:21 UTC, merged