Added local volumetric fog in the HDRP features page
Unity-Technologies/Graphics pull request #4758
Opened 2021-06-02 14:59 UTC by alelievr

### Purpose of this PR
Added the local volumetric fog section in HDRP features.
![image](https://user-images.githubusercontent.com/6877923/120626823-5746db80-c463-11eb-8a56-a4b8625e27a0.png)

Poking @Vic-Cooper to validate / rephrase :)

2021-06-02 17:30 UTC, Vic-Cooper requested changes
Suggested some small changes :)

2021-06-02 17:30 UTC, Vic-Cooper commented on com.unity.render-pipelines.high-definition/Documentation~/HDRP-Features.md
> +In addition to fog, HDRP supports local volumetric fog which helps you control the density of the fog in an area. To allow more fine grained control, it's also possible to use a 3D Mask texture to co
In addition to fog, HDRP also supports local volumetric fog. You can use this to control the density of fog in an area. For more detailed control, you can use a 3D Mask texture to control the color and the density inside the volume itself. For more information see the [Local Volumetric Fog](Local-Volumetric-Fog.md) documentation.

2021-06-02 17:30 UTC, Vic-Cooper commented on com.unity.render-pipelines.high-definition/Documentation~/HDRP-Features.md
> +Light layers In the shadow map dropdown can also be used to control which object receives a shadow from which light. By default both Light Layers and Shadow Map Light Layers are synchronized so the r
I approve this full stop! :D However, I'd also like to review this while we're here: 

You can use Light layers in the shadow map dropdown to control which GameObject receives a shadow from which light. By default, both Light Layers and Shadow Map Light Layers are synchronized so the result is coherent. This means that when a GameObject receives light it also casts shadows. For more information, see [Shadow Light Layer section](Light-Layers.md#ShadowLightLayers).

2021-06-03 10:01 UTC, alelievr commented
Pushed the fix :)

2021-06-03 10:21 UTC, Vic-Cooper approved these changes
Good stuff. Thanks!

2021-06-07 12:31 UTC, sebastienlagarde approved these changes

2021-06-07 12:31 UTC, merged