[DRAFT] WIP SSGI Improvements
Unity-Technologies/Graphics pull request #4886
Opened 2021-06-10 22:11 UTC by anisunity

PR still in wip

2021-06-14 12:22 UTC, anisunity commented on com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/ScreenSpaceGlobalIllumination.compute
> +#pragma enable_d3d11_debug_symbols
Remove this

2021-06-14 16:45 UTC, remi-chapelain commented
Made a simple "inside" scene to test the different fallbacks solutions. The fallback on probe helps a lot eventhough the setup to make it look like what you want in terms of reflection probe placement could be tedious but it's a good solution while probe volume are experimental. 

Also roughly (only compared frame time for now and some variance) compared the cost of fallbacks and before the PR. 
My premature conclusion is that the cost is more or less the same (+/- 0.250ms). And that SSGI costs roughly 2 to 3ms as a whole. 

No SSGI										11.03 ms
SSGI Medium None fallback (Before PR)                        13.62 ms
SSGI Medium None fallback						13.72 ms
SSGI Medium Sky fallback						13.65 ms
SSGI Medium Reflection Probe Fallback			        13.75 ms
SSGI Medium Reflection Probe And Sky Fallback	        13.74 ms
SSGI Medium Probe Volume Fallback				13.48 ms
RTGI Perf mode in medium  		                                14.02 ms                                      
RTGI	Quality									24.13 ms

Ray Traced GI in medium perf mode cost only slightly more (roughly 4ms) and cost a lot in quality mode (12ms). 

https://user-images.githubusercontent.com/57442369/121927700-a6ccb780-cd3f-11eb-986d-43860c521f34.mp4

Here's the different tests images: 

**No SSGI**
![S_Apartment_20210614_1705814_No SSGI](https://user-images.githubusercontent.com/57442369/121927163-09718380-cd3f-11eb-9dd4-d3aeea9c464a.png)

**SSGI Medium - No Fallback**
![S_Apartment_20210614_1659322_SSGI Medium No Fallback](https://user-images.githubusercontent.com/57442369/121927155-08405680-cd3f-11eb-921b-fda07c9e5efb.png)

**SSGI Medium - Probe Volume Fallback**
![S_Apartment_20210614_1733865_SSGI Probe Volume Fallback](https://user-images.githubusercontent.com/57442369/121927169-0a0a1a00-cd3f-11eb-88fa-f3a1c559564c.png)

**SSGI Medium - Reflection Probe Fallback**
![S_Apartment_20210614_1700992_SSGI Medium Reflection Probe Fallback](https://user-images.githubusercontent.com/57442369/121927160-08d8ed00-cd3f-11eb-9b42-ee9311d9f288.png)

**RTGI Quality**
![S_Apartment_20210614_1706548_RTGI](https://user-images.githubusercontent.com/57442369/121927164-09718380-cd3f-11eb-90de-fb1ca92c42ca.png)

**Path Tracer**
![S_Apartment_20210614_1658808_Path Tracer](https://user-images.githubusercontent.com/57442369/121927150-06769300-cd3f-11eb-88e0-db0975787449.png)

2021-06-30 10:59 UTC, anisunity commented on com.unity.render-pipelines.high-definition/Runtime/Lighting/ScreenSpaceLighting/ScreenSpaceGlobalIllumination.compute
> +#pragma enable_d3d11_debug_symbols
done

2021-06-30 11:01 UTC, anisunity commented
Fixed the APV issue reported by @remi-chapelain

2021-07-02 08:25 UTC, sebastienlagarde approved these changes

2021-07-02 09:05 UTC, remi-chapelain commented
We also need to append the documentation about the light probe > reflection probe fallback hierarchy :)

2021-07-02 16:58 UTC, sebastienlagarde commented
there is various 
<html>
<body>
<!--StartFragment-->

Test Name: HDRP_GraphicTestRunner.002-HDMaterialsTest Fixture: HDRP_RuntimeTestsTest Status: FailureTest Execution Time: 00:00:26.192Message: Copy to ClipboardUnhandled log message: '[Error] Kernel 'ValidateHistory' not found'. Use UnityEngine.TestTools.LogAssert.Expect
--


<!--EndFragment-->
</body>
</html>  error in Yamato

2021-07-05 08:05 UTC, anisunity commented
Probably a resource thing, i'll check that

2021-07-05 12:31 UTC, remi-chapelain requested changes
Finished testing. 
Tested on the template and on various projects to see if the position of the reflections probe needed to be different to be able to have a correct results with SSGI. And it's fine in most projects. Probes position can still be adjusted to change SSGI results for artistic reasons but it's a case by case. 

**Comparison between no fallback and the new reflection probe fallback**
https://user-images.githubusercontent.com/57442369/124471533-43153780-dd9d-11eb-8311-19ef81b24cfb.mp4

**Comparison between SSGI and no SSGI**
https://user-images.githubusercontent.com/57442369/124471820-a010ed80-dd9d-11eb-9378-37b45c8cb72f.mp4

Only things I'd like to see changed before fully approving are : 
- Documentation to be updated about the new fallbacks and the hierarchy of it (probe volume first, then reflection probes).
- High quality settings denoiser radius needs to be increased to 0.5 (instead of 0.25). In some cases, you can still see "blobs" of lights with .25 radius which looks worse than medium, especially when you are moving.

2021-07-05 12:38 UTC, anisunity commented
I pushed a fix that should fix all failing tests

2021-07-05 13:02 UTC, remi-chapelain approved these changes
🟢

2021-07-07 08:36 UTC, anisunity commented
Merged master and relaunched the tests

2021-07-09 15:02 UTC, merged