Updated the Physically Based Sky documentation for baked lights
Unity-Technologies/Graphics pull request #4891
Opened 2021-06-14 09:23 UTC by adrien-de-tocqueville

### Purpose of this PR
https://fogbugz.unity3d.com/f/cases/1341731/

Baked lights are ignored by Unity at runtime, added a note in the PBR sky doc to mention that

2021-06-14 15:24 UTC, Vic-Cooper requested changes
Made some suggestions.

2021-06-14 15:24 UTC, Vic-Cooper commented on com.unity.render-pipelines.high-definition/CHANGELOG.md
> +- Updated the Physically Based Sky documentation for baked lights.
Capitalise "Lights".

Updated the Physically Based Sky documentation for baked Lights.

2021-06-17 11:49 UTC, Vic-Cooper approved these changes
Looks good! :)

2021-06-17 17:52 UTC, sebastienlagarde approved these changes

2021-06-17 17:53 UTC, merged