Universal/material tooltips
Unity-Technologies/Graphics pull request #4998
Opened 2021-06-29 12:27 UTC by Jonasmortensen

# **Please read the [Contributing guide](CONTRIBUTING.md) before making a PR.**

* Read the [Graphics repository & Yamato FAQ](http://go/graphics-yamato-faq).

### Checklist for PR maker
- [ ] Have you added a backport label (if needed)? For example, the `need-backport-*` label. After you backport the PR, the label changes to `backported-*`.
- [ ] Have you updated the changelog? Each package has a `CHANGELOG.md` file.
- [ ] Have you updated or added the documentation for your PR? When you add a new feature, change a property name, or change the behavior of a feature, it's best practice to include related documentation changes in the same PR. If you do add documentation, make sure to add the relevant Graphics Docs team member as a reviewer of the PR. If you are not sure which person to add, see the [Docs team contacts sheet](https://docs.google.com/spreadsheets/d/1rgUWWgwLFEHIQ3Rz-LnK6PAKmbM49DZZ9al4hvnztOo/edit#gid=1058860420).
- [ ] Have you added a graphic test for your PR (if needed)? When you add a new feature, or discover a bug that tests don't cover, please add a graphic test.

---
### Purpose of this PR
Why is this PR needed, what hard problem is it solving/fixing?

---
### Testing status
Describe what manual/automated tests were performed for this PR

---
### Comments to reviewers
Notes for the reviewers you have assigned.

2021-06-30 07:48 UTC, erikabar approved these changes
All tooltips look good

2021-06-30 08:53 UTC, ellioman approved these changes

2021-06-30 11:08 UTC, TheoWong-pixel approved these changes

2021-06-30 13:50 UTC, eh-unity approved these changes
LGTM.

2021-07-05 05:33 UTC, alex-vazquez requested changes
Good PR, just change the `new GUIContent` for `EditorGUIUtility.TrTextContent`

2021-07-05 05:33 UTC, alex-vazquez commented on com.unity.render-pipelines.universal/Editor/ShaderGUI/ParticleGUI.cs
>              public static GUIContent VertexStreams = new GUIContent("Vertex Streams",
```suggestion
            public static GUIContent VertexStreams = EditorGUIUtility.TrTextContent("Vertex Streams",
```

2021-07-05 05:33 UTC, alex-vazquez commented on com.unity.render-pipelines.universal/Editor/ShaderGUI/ShadingModels/LitDetailGUI.cs
>              public static readonly GUIContent detailAlbedoMapScaleInfo = new GUIContent("Setting the scaling factor to a value other than 1 results in a less performant shader variant.");
Please change them to  `EditorGUIUtility.TrTextContent`

2021-07-05 05:33 UTC, alex-vazquez commented on com.unity.render-pipelines.universal/Editor/ShaderGUI/ShadingModels/LitGUI.cs
> +                new GUIContent("Specular Map", "Designates a Specular Map and specular color determining the apperance of reflections on this Material's surface.");
Same here, use  EditorGUIUtility.TrTextContent

2021-07-05 05:33 UTC, alex-vazquez commented on com.unity.render-pipelines.universal/Editor/ShaderGUI/ShadingModels/SimpleLitGUI.cs
> +                new GUIContent("Specular Map", "Designates a Specular Map and specular color determining the apperance of reflections on this Material's surface.");
```suggestion
                 EditorGUIUtility.TrTextContent("Specular Map", "Designates a Specular Map and specular color determining the apperance of reflections on this Material's surface.");
```

2021-07-05 12:19 UTC, Jonasmortensen commented on com.unity.render-pipelines.universal/Editor/ShaderGUI/ParticleGUI.cs
>              public static GUIContent VertexStreams = new GUIContent("Vertex Streams",
Changed! thanks

2021-07-06 09:02 UTC, alex-vazquez requested changes

2021-07-06 09:02 UTC, alex-vazquez commented on com.unity.render-pipelines.universal/Editor/ShaderGUI/ParticleGUI.cs
> +                        BaseShaderGUI.TwoFloatSingleLine(EditorGUIUtility.TrTextContent("Surface Fade"),
Can we move this to `Styles`?

2021-07-07 06:51 UTC, Jonasmortensen commented on com.unity.render-pipelines.universal/Editor/ShaderGUI/ParticleGUI.cs
> +                        BaseShaderGUI.TwoFloatSingleLine(EditorGUIUtility.TrTextContent("Surface Fade"),
Done!

2021-07-07 07:01 UTC, alex-vazquez approved these changes
Awesome. Good PR!

2021-07-07 09:00 UTC, oleks-k approved these changes
Approving to unblock development. Will create a ticket to do another pass later.

2021-07-07 10:13 UTC, merged