Universal/quality audit/rp asset UI
Unity-Technologies/Graphics pull request #5014
Opened 2021-06-30 12:57 UTC by Jonasmortensen

This PR adds a collection of UI improvements to the Universal Render Pipeline Asset as part of the Quality Audit

2021-07-05 10:01 UTC, alex-vazquez requested changes

2021-07-05 10:01 UTC, alex-vazquez commented on com.unity.render-pipelines.universal/Editor/UniversalRenderPipelineAssetEditor.cs
> +            //m_PostProcessingSettingsFoldout.value = CoreEditorUtils.DrawHeaderFoldout(Styles.postProcessingSettingsText, m_PostProcessingSettingsFoldout.value);
If this won't be used anymore I would rather remove it.

2021-07-20 13:29 UTC, TheoWong-pixel approved these changes

2021-07-20 13:32 UTC, closed without merging

2021-07-20 13:32 UTC, Jonasmortensen commented
Closed due to it being blocked by an update to the UI framework