Fix depthDescriptor.bindMS condition
Unity-Technologies/Graphics pull request #5039
Opened 2021-07-05 06:45 UTC by robin-demoor

---
### Purpose of this PR
Some Scarlet tests have started failing with the exception: "A non-multisampled texture being bound to a multisampled sampler. Disabling in order to avoid undefined behavior. Please enable the bindMS flag on the texture."

This change fixes the issue.. The BindMS flag was incorrectly disabled on some platforms due to the depthPriming setting.

2021-07-05 07:02 UTC, manuele-bonanno requested changes
this whole line of code was added by the depth priming PR. If you look at the VR only #ifdef above, this is exactly the same code, and used to be VR specific code.

I think we should revert the bindMS setting to what it was before the depth priming PR, which seems to have introduced the issue, so just removing this line completely

Are there any issues with that?

2021-07-05 07:03 UTC, manuele-bonanno commented on com.unity.render-pipelines.universal/Runtime/UniversalRenderer.cs
this is the line of code to remove I mentioned in my comment (which I posted in the wrong place ops :) )

2021-07-05 07:36 UTC, manuele-bonanno approved these changes
LGTM, thanks for the changes!

2021-07-29 12:10 UTC, NicoLeyman commented
@thomas-zeng Any update on this ? This has been causing certain platform tests to fail for a while.
The fix shouldn't have any fallout for XR but should probably get an ok from the XR side.

2021-08-03 20:10 UTC, thomas-zeng approved these changes

2021-08-03 20:21 UTC, thomas-zeng commented
Sorry @NicoLeyman for dropping the ball. I have greenlighted the PR.

2021-08-13 10:24 UTC, ellioman approved these changes

2021-08-18 10:36 UTC, ernestasKupciunas approved these changes
Approving without testing. The issue was triggered in Yamato, and it is fixed now.

2021-08-19 08:35 UTC, ellioman commented
Issues on Yamato were not caused by this PR.

2021-08-19 08:35 UTC, merged