[HDRP] Add mode for custom pass volume to execute on one camera only
Unity-Technologies/Graphics pull request #5090
Opened 2021-07-07 16:57 UTC by alelievr

### Purpose of this PR
Improve the workflow of custom pass volumes when you need to apply the effect on only one camera.

There is a new Mode named "Camera" that allows you to select on which camera the custom pass volume will be executed:
![image](https://user-images.githubusercontent.com/6877923/124798201-61249880-df53-11eb-8d5c-037245158b60.png)

In term of C# API, there is a new field to set the target camera:
```CSharp
CustomPassVolume.targetCamera
```

setting the target camera in code will automatically switch the volume mode to Camera if the camera is not null.

---
### Testing status
- Tested that the new mode executes only with the camera set in the inspector.
- Tested that the volume mask doesn't affect how the volume is executed in camera mode.
- Tested that If the target camera field is set to null, the volume is not executed.

2021-07-08 12:31 UTC, Vic-Cooper commented on com.unity.render-pipelines.high-definition/Documentation~/Custom-Pass-Volume-Workflow.md
> +If the **Mode** of your Custom Pass Volume is set to **Camera**, the volume will only be executed for the target camera in parameter. When the target camera is set, the volume ignores the volume laye
Suggested change: 

When a Custom Pass Volume's **Mode** is set to **Camera**, HDRP only executes the custom pass volume in its **Target Camera**. To make sure HDRP always executes the custom pass volume, it ignores the Camera's volume layer mask when a **Target Camera** is set.

2021-07-08 12:31 UTC, Vic-Cooper requested changes
Suggested one change.

2021-07-08 12:53 UTC, pmavridis approved these changes
That's an awesome feature! Thanks for introducing this. Using this, the compositpr setup code can be simplified a lot.

For consistency, I'm wondering if we can introduce the same feature for the rest of the volume system (not only the custom pass).

2021-07-08 13:01 UTC, Vic-Cooper approved these changes
Looks good!

2021-07-08 13:45 UTC, alelievr commented
> For consistency, I'm wondering if we can introduce the same feature for the rest of the volume system (not only the custom pass).


That's a good idea :) It's probably possible to do something similar, I'll add this to the list of feature improvements

2021-07-09 09:05 UTC, TomasKiniulis requested changes
Love the idea of this! Testing it out there seems to be an issue switching from local/global modes to targetCamera through the API. Custom Pass Volume is correctly updated only when the object is selected. 

https://user-images.githubusercontent.com/50582134/125053580-f76cd180-e0ad-11eb-85ea-23d8bcadfcb6.mp4

2021-07-09 09:55 UTC, TomasKiniulis approved these changes
Checked switching through Global and Local volume to target camera, selected and deselected custom volumes are updated correctly now

2021-07-12 17:25 UTC, sebastienlagarde approved these changes

2021-07-12 17:25 UTC, merged