VFX Multi-selection and automatic attach on selection
Unity-Technologies/Graphics pull request #5099
Opened 2021-07-08 14:05 UTC by julienamsellem

### Purpose of this PR
This PR addresses two different purposes that are connected.
1. When multiple VFX are selected the VFX overlay should apply to all selected
2. When a VFX asset is being edited, automatically attach it to the selection (if compatible).

---
### Testing status
Tech artists have tested as real users so probably not every corner cases.

---
### Comments to reviewers
Notes for the reviewers you have assigned.

2021-07-08 18:10 UTC, VitaSkruibyte commented
Logged some issues that can be looked into already, here's the work in progress [test doc](https://docs.google.com/document/d/1Cw1BICfGJfNiDXQawv9VMZwYr6qXW1GD7sr99VtLTHQ/edit?usp=sharing).

2021-07-28 07:06 UTC, PaulDemeulenaere approved these changes
I don't have any important behavior change to recommend.
I have only coding rules issues (especially the `this.`)

The issue reported by @VitaSkruibyte in [test doc](https://docs.google.com/document/d/1Cw1BICfGJfNiDXQawv9VMZwYr6qXW1GD7sr99VtLTHQ/edit) are probably a simply missing null check somewhere, so I can preapprove 🟢

2021-07-28 07:06 UTC, PaulDemeulenaere commented on com.unity.visualeffectgraph/Editor/Utilities/EventTester/VFXEventTesterWindow.cs
> +                if (name == "OnPlay")
You didn't change this code but these is a global static value for this string : https://docs.unity3d.com/ScriptReference/VFX.VisualEffectAsset.PlayEventName.html
You can replace with :
```
name == VisualEffectAsset.PlayEventName
```

2021-08-12 10:29 UTC, VitaSkruibyte approved these changes
Looks neat 💯! All the raised issues were fixed, couldn't find any other problems after additional pass. Thanks for all the work done on this! 🟢

2021-08-16 08:28 UTC, PaulDemeulenaere approved these changes
LGTM! Thanks!

2021-08-16 08:28 UTC, PaulDemeulenaere commented on com.unity.visualeffectgraph/Editor/GraphView/VFXComponentBoard.cs
> +                case VFXBasicEvent basicEvent when !IsDefaultEvent(name):
Nice, I wasn't aware of this new condition : https://docs.microsoft.com/fr-fr/dotnet/csharp/language-reference/statements/selection-statements

2021-08-23 09:52 UTC, peeweek commented
As stated in the feedback document, currently the object field displays all effects in the scene but can only attach to the instances that are compatible with the currently opened graph, which is confusing as this field's purpose is to find instances from the scene that can be attached to:
- There is no way to figure out which effect is compatible with current graph
- Selecting an incompatible instance in the scene has no feedback

![attach-objectpicker-shows-all](https://user-images.githubusercontent.com/4037271/130426954-aa70c6ef-c80f-4d37-ac98-0c23f4c05c93.gif)

The issue should be addressed or the field removed, if can't be fixed. As the occurrence of this usability issue is extremely high. (It is extremely unlikely that a scene will only use effects from a single graph).

2021-08-23 12:29 UTC, MarieGuff requested changes
Red flag on TA side: in the attach search, the incompatible VFX are displayed the same way as compatible ones. The incompatible ones should be greyed or hidden (using the search filter as Thomas suggested is a good idea). 
Otherwise, at least an error message (feedback) when selecting a incompatible VFX is necessary if nothing else can be done for now!

```
[Thomas finding]
❌[UX] Objectpicker shows all VisualEffect game objects and not only the ones with compatible attachments. 
Selecting an incompatible game object does not have any feedback. This makes the object picker rather useless in 
scenes with hundreds of game objects using dozens of different asset graphs (commonplace in game production)

Note : Using ref:/Assets/Path/To/Asset.vfx in the object picker enables filtering the correct ones.

```

2021-08-30 08:26 UTC, julienamsellem commented
Yamato `General Checks on trunk` is green but `General Checks on 2021.2` is red for unrelated reason

2021-08-30 09:03 UTC, kroatoa approved these changes

2021-08-30 14:45 UTC, merged