EditorWindow for diffusion profiles registration
Unity-Technologies/Graphics pull request #5116
Opened 2021-07-12 16:18 UTC by adrien-de-tocqueville

### Purpose of this PR

Small tweak to the behavior introduced in this PR. Basically it waits until import is finished to show the popup for adding profiles.
That way we don't pause import process in the middle, and choice can be made over which profiles to add with the full list available.

UX is pretty bad, if you have ideas on how to improve it please share

![diffusion_profiles](https://user-images.githubusercontent.com/61282776/125321878-6d3a9c80-e33d-11eb-87d7-ccf5d3e379eb.gif)

---
### Testing status

see the gif above
pretty much only contains UX change compared to francesco's changes so i didn't tested in depth the bahavior

2021-07-13 05:09 UTC, merpheus-dev commented
If you are still seeking any UI suggestions, for the UX of this, rather than showing plain text description, three things can be done. ( I agree that UI is pretty un-descriptive)

- Show a grid layout of texture previews of the diffusion profiles with names attached to their bottom.
- Plain text UI can stay still, but a little button can be added to the same line to show a preview or inspect the diffusion profile upon clicking it.
- Combination of 1st and 2nd option where it shows a grid layout diffusion profile preview+button to inspect the whole thing.

2021-07-13 09:05 UTC, adrien-de-tocqueville commented
@merpheus-dev Thanks for your suggestions :slightly_smiling_face: unfortunately diffusion profile don't have a preview, only a static icon. But still i did your second point for the inspection (see the new screenshot in the description)

2021-07-13 09:52 UTC, merpheus-dev commented
Great! That's a clever solution. Thanks!

2021-07-22 15:49 UTC, sebastienlagarde approved these changes

2021-07-22 15:51 UTC, FrancescoC-unity approved these changes

2021-07-28 16:53 UTC, RemyUnity requested changes
Here is what the window looks like when I try to import a .unitypackage with 15 profiles, none beeing in the global settings : 
![image](https://user-images.githubusercontent.com/32760367/127363984-27f174b1-fe2e-4b50-a57b-f9adb37f88be.png)

Two things bug me : 
- The phrase saying that if a profile is not set in the global settings then HDRP can't use it is a false statement, as I can use the "Diffusion Profile Override" in volumes.
- If would be nice to point to the override in the error box at the bottom so users can learn how to use them to go over that 15 profiles limit.

2021-07-29 09:16 UTC, adrien-de-tocqueville commented
I updated the window to mention the diffusion profile override with a link to the doc
![diffusion_profiles](https://user-images.githubusercontent.com/61282776/125321878-6d3a9c80-e33d-11eb-87d7-ccf5d3e379eb.gif)

I also noticed that when saving a material, it gets reimported and so the window pops up everytime. To workaround that, i made the checkbox accessible directly from the window to easily disable it, and i made the API public so that asset store assets can explicitely require the window to be openned for some assets, which bypasses the checkbox

2021-07-29 10:06 UTC, Vic-Cooper requested changes
Adjusted some of the UI text and the changelog entry.

2021-07-29 10:06 UTC, Vic-Cooper commented on com.unity.render-pipelines.high-definition/Editor/RenderPipeline/Settings/HDGlobalSettingsWindow.Skin.cs
> +            public static readonly GUIContent showMissingDiffusionProfilesContentLabel = EditorGUIUtility.TrTextContent("Missing Diffusion Profiles Window", "When enabled, if a material with missing
Capitalize "Material", also removed passive voice: 

"When enabled, if HDRP imports a Material with missing diffusion profiles, it displays a window where you can add diffusion profiles to the HDRP Global Settings."

2021-07-29 10:06 UTC, Vic-Cooper commented on com.unity.render-pipelines.high-definition/CHANGELOG.md
> +- Fixed diffusion profile upgrade window to by delaying the windows to end of the import process
- Fixed the diffusion profile upgrade window by delaying its appearance until HDRP has finished the import process.

2021-07-29 12:08 UTC, RemyUnity commented
> I updated the window to mention the diffusion profile override with a link to the doc
> 
> I also noticed that when saving a material, it gets reimported and so the window pops up everytime. To workaround that, i made the checkbox accessible directly from the window to easily disable it, and i made the API public so that asset store assets can explicitely require the window to be openned for some assets, which bypasses the checkbox
> 
> ![image](https://user-images.githubusercontent.com/61282776/127465531-78875bbd-4fc8-4095-af10-53b493a89296.png)

I like the checkbox to avoid being harassed by the window, but if for some reason I would like to re-enable it, how would I do it ?
Should it be considered UX wise ?

2021-07-29 14:16 UTC, adrien-de-tocqueville commented
> I like the checkbox to avoid being harassed by the window, but if for some reason I would like to re-enable it, how would I do it ?
Should it be considered UX wise ?

There is an option in the HDRP global settings. It is explained in the tooltip of the checkbox

2021-07-29 14:42 UTC, RemyUnity commented
> > I like the checkbox to avoid being harassed by the window, but if for some reason I would like to re-enable it, how would I do it ?
> > Should it be considered UX wise ?
> 
> There is an option in the HDRP global settings. It is explained in the tooltip of the checkbox

Wouldn't it make sense to have it in the HDRP preferences ? 
![image](https://user-images.githubusercontent.com/32760367/127512417-0d11c2b3-dbf2-4a13-8fe9-2ad6371a13cc.png)

2021-07-29 14:46 UTC, adrien-de-tocqueville commented
I am not sure, I think HDRP preferences not per project. For example the window is disabled in HDRP_Tests but we might want it in other projects.
If I am wrong and the HDRP preferences are per project then I am ok to change, it would make that window a bit more populated, but that would spread the settings even more

2021-07-29 14:54 UTC, RemyUnity commented
It's more that HDRP global settings mostly hold settings for the behavior of the renderer itself, while this window is an editor only thing. Eventually in the HDRP wizard ? UX should give advice here.

2022-04-15 16:39 UTC, closed without merging