Fix doc and rotation curves
Unity-Technologies/Graphics pull request #5136
Opened 2021-07-13 18:44 UTC by skhiat

Fix doc and rotation for curve distribution mission on PR various_fixes_3.

2021-07-13 19:03 UTC, sebastienlagarde approved these changes

2021-07-15 09:20 UTC, Vic-Cooper requested changes
Re-structured the description for clarity.

2021-07-15 09:20 UTC, Vic-Cooper commented on com.unity.render-pipelines.core/Documentation~/Common/lens-flare-data-driven-asset.md
> +| Rotation | The uniform angle of rotation (remap from -180° to 180°) applied to each element distributed along the curve. |
Changed for clarity:

| Rotation | The uniform angle of rotation (in degrees) applied to each element distributed along the curve. </br>This value ranges from -180° to 180°. |

2021-07-15 09:20 UTC, Vic-Cooper commented on com.unity.render-pipelines.high-definition/Documentation~/lens-flare-data-driven-asset.md
> +| Rotation | The uniform angle of rotation (remap from -180° to 180°) applied to each element distributed along the curve. |
Same again: 

| Rotation | The uniform angle of rotation (in degrees) applied to each element distributed along the curve. </br>This value ranges from -180° to 180°. |

2021-07-15 09:20 UTC, Vic-Cooper commented on com.unity.render-pipelines.universal/Documentation~/lens-flare-data-driven-asset.md
> +| Rotation | The uniform angle of rotation (remap from -180° to 180°) applied to each element distributed along the curve. |
And again:

| Rotation | The uniform angle of rotation (in degrees) applied to each element distributed along the curve. </br>This value ranges from -180° to 180°. |

2021-07-19 10:40 UTC, erikabar approved these changes

2021-07-21 12:00 UTC, sebastienlagarde approved these changes

2021-07-21 12:01 UTC, sebastienlagarde commented
Change are minimanl. Doc correctoin done. Merging

2021-07-21 12:02 UTC, merged