Quality audit - Specify the way that Volume Gizmos are being rendered
Unity-Technologies/Graphics pull request #5139
Opened 2021-07-14 09:29 UTC by alex-vazquez

![image](https://user-images.githubusercontent.com/76204843/125598262-1f1b2ccd-51f7-4775-a28f-c011fd4947a8.png)

---
### Purpose of this PR
- Adding user preferences to specify how the Volume Gizmos are being rendered
- Adding a system to extend Core Render Pipeliene Settings Panel

---
### Testing status
- Check gizmos are correctly changed
- Check the preferences are applied, saved and restored

2021-07-19 08:01 UTC, RSlysz reviewed
I need more info to know if this is good or not.

2021-07-19 08:01 UTC, RSlysz commented on com.unity.render-pipelines.high-definition/Editor/RenderPipeline/CustomPass/CustomPassVolumeGizmoDrawer.cs
> +                            c.convex = true;
Same for forcing convex here

2021-07-28 11:19 UTC, alex-vazquez commented on com.unity.render-pipelines.core/Editor/Volume/VolumeGizmoDrawer.cs
> +                        // other m_Colliders...
I think we should expose the capsule gizmo.

2021-07-28 14:59 UTC, alex-vazquez commented on com.unity.render-pipelines.core/Editor/Volume/VolumesPreferences.cs
> +    public class VolumesPreferences : ICoreRenderPipelinePreferencesProvider
For now we will leave it here, as the Gizmo menu is going to be reworked.

2021-07-28 15:01 UTC, alex-vazquez commented on com.unity.render-pipelines.high-definition/Editor/RenderPipeline/CustomPass/CustomPassVolumeGizmoDrawer.cs
> +        static void OnDrawGizmos(CustomPassVolume scr, GizmoType gizmoType)
done something

2021-07-28 15:02 UTC, alex-vazquez commented on com.unity.render-pipelines.high-definition/Editor/RenderPipeline/CustomPass/CustomPassVolumeGizmoDrawer.cs
> +                        // other m_Colliders...
I will wait until Gizmos API is updated.

2021-07-28 15:39 UTC, RSlysz approved these changes
looks better

2021-07-29 09:24 UTC, TheoWong-pixel approved these changes

2021-07-30 07:08 UTC, alex-vazquez commented
QA could you check that Volume Gizmo visibility, and CustomPassVolume(HDRP) is working as is said on the PR description?

2021-07-30 09:07 UTC, alex-vazquez commented
@reallyfancy how do you think we should include this on the documentation. I did a system to be able to add preferences to the CoreRenderPipeline page, so I think users with a custom pipeline will like to know how to do that

2021-07-30 09:25 UTC, phi-lira approved these changes

2021-07-30 09:45 UTC, iM0ve requested changes
**Testing status:** In progress

**What's tested:**


**Issues:**
**1)** On upgrade of a project it is possible the value of Gizmos is null. This will make all the volume gizmos "disappear" in the scene. 

Reproduction: need to delete registry file: Computer\HKEY_CURRENT_USER\Software\Unity Technologies\Unity Editor 5.x\General.VolumeGizmoVisibility

![Unity_6Yubdxa8eF](https://user-images.githubusercontent.com/36502659/127634539-361bc1e8-2d12-4c8e-bd57-da4fa3a24c37.png)



**2)** Regression in terms of UX. It used to be very easy to temporarily disable and enable only the volume display. Now the option to do it is gone

Before:
![Before](https://user-images.githubusercontent.com/36502659/127634942-cf9401a9-d281-415c-8b67-45bb8880f04f.jpg)

After:
![After](https://user-images.githubusercontent.com/36502659/127634974-88072031-543b-4c65-a506-6763d137a01d.jpg)

2021-07-30 14:32 UTC, simon-engelbrecht-soerensen approved these changes
Working great 👍 
Data is saved and updates correctly.

2021-08-02 09:51 UTC, iM0ve approved these changes
I updated the review above. One issue is fixed and the other will be addressed separately
https://fogbugz.unity3d.com/f/cases/1354816/

No other concerns

2021-08-02 13:15 UTC, merged