[HDRP] Add shadergraph nodes to sample custom pass color and depth buffers
Unity-Technologies/Graphics pull request #5169
Opened 2021-07-20 12:41 UTC by alelievr

### Purpose of this PR

Added two new ShaderGraph nodes to sample the custom pass color and depth buffers in HDRP:

![image](https://user-images.githubusercontent.com/6877923/126323443-ec2e3dc4-42a0-42f1-9eca-e2abd40be98a.png)

---
### Testing status

Manually tested all the depth sampling modes (raw, linear01, and linearEye) and custom color buffer on transparent objects (with a custom pass rendering in the before transparent injection point).

Added an automated test for both custom color and depth node:
![image](https://user-images.githubusercontent.com/6877923/126313870-a7dc7565-93e8-449e-abda-bb97d217cc6c.png)

2021-07-20 15:13 UTC, adrien-de-tocqueville approved these changes

2021-07-22 13:57 UTC, Vic-Cooper requested changes
A few small suggestions, generally good :)

2021-07-22 13:57 UTC, Vic-Cooper commented on com.unity.render-pipelines.high-definition/Documentation~/Custom-Pass-Creating.md
> +In Shader Graph, there are two nodes for sampling the custom color and depth buffers. For more information about these nodes, see the Shader Graph documentation: [Custom Color Node](https://docs.unit
Thanks for adding this! Small suggestion: 

You can sample the custom color and depth buffers in Shader Graph using the following nodes: 
- [Custom Color Node](https://docs.unity3d.com/Packages/com.unity.shadergraph@latest?subfolder=/manual/HD-Custom-Color-Node.html)
- [Custom Depth Node](https://docs.unity3d.com/Packages/com.unity.shadergraph@latest?subfolder=/manual/HD-Custom-Depth-Node.html)

2021-07-22 13:57 UTC, Vic-Cooper commented on com.unity.shadergraph/Documentation~/HD-Custom-Depth-Node.md
> +| Linear01 | Linear depth value between 0 and 1 |
| Linear01 | The linear depth value between 0 and 1. |

2021-07-22 13:57 UTC, Vic-Cooper commented on com.unity.shadergraph/Documentation~/HD-Custom-Depth-Node.md
> +| **Output** | Output      |    Vector 4 | None | Output value |
| **Output** | Output      |    Vector 4 | None | The output value of this node. |

2021-07-22 13:57 UTC, Vic-Cooper commented on com.unity.shadergraph/Documentation~/HD-Custom-Depth-Node.md
> +| **UV** | Input | Vector 4 | Screen Position | Sets the normalized screen coordinates to sample. |
| **UV** | Input | Vector 4 | Screen Position | Sets the normalized screen coordinates that this node samples. |

2021-07-22 13:57 UTC, Vic-Cooper commented on com.unity.shadergraph/Documentation~/HD-Custom-Color-Node.md
> +| **Output** | Output      |    Vector 4 | None | The value in the custom pass color buffer at the sampled coordinates |
| **Output** | Output      |    Vector 4 | None | The value the custom pass color buffer contains at the sampled coordinates. |

2021-07-22 13:57 UTC, Vic-Cooper commented on com.unity.shadergraph/Documentation~/HD-Custom-Depth-Node.md
> +| Raw      | Raw depth value                    |
| Raw      | The raw depth value.                    |

2021-07-22 13:57 UTC, Vic-Cooper commented on com.unity.shadergraph/Documentation~/HD-Custom-Depth-Node.md
> +| Eye      | Depth converted to eye space units |
| Eye      | The depth value converted to eye space units. |

2021-07-22 16:45 UTC, sebastienlagarde approved these changes

2021-07-27 13:56 UTC, Vic-Cooper approved these changes
Looks good :)

2021-07-28 10:22 UTC, RemyUnity approved these changes
Except the small issue I found and already corrected with commit f81656e everything seems fine.
I did set up a graph that allows to compare HDRP scene color & depth nodes VS the custom buffer nodes, and couldn't see any difference (when the custom pass is re-rendering the same things as the regular camera).
![image](https://user-images.githubusercontent.com/32760367/127306755-d220c691-4fc1-4119-ba02-9f36964e2f03.png)

2021-07-28 11:04 UTC, sebastienlagarde commented
For Shader GRaph team. The shield is due to documentation which is in shadergraph manual. Not a blocker. Merging.

2021-07-28 12:42 UTC, merged