fixes for distance and light component behavior
Unity-Technologies/Graphics pull request #5171
Opened 2021-07-20 12:52 UTC by pierre-unity

### Purpose of this PR
Following [this discussion on Slack](https://unity.slack.com/archives/C6Y79CZM0/p1626784574040000), I created this PR.

It solves the following issues:

- It removes the automatic addition of a light component, because this light will be unwanted in several cases, notably with Prefab that do not contain a Light component at the root
- When dragging the slider near 0 and beyond, the transform (position) can still be seen changing! Clamping the distance with "Math.Clamp" avoid impacting the transform while dragging the Distance slider and reaching near 0 values.
- The Min distance value is also now set to 0.001m (1mm). Previously, there was a mismatch between the default value (0.0f) and the allowed value in the UI (0.01f). Now, it will be 0.001 by default and it won't let the user use a lower value, as 0 messes up the rotation transform.
- The max distance is also clamped at 1000m, as higher values will start to badly affect the precision (the position starts to shift). 1000m is more than enough for any realistic scenario.

---
### Testing status
None

---
### Comments to reviewers
Fairly safe change, but I'm no coder, so I've no idea if this is following good code practices, especially for the way I name variables and use the clamp function on a slider, so feel free to fix any errors. :)

2021-07-20 13:58 UTC, RSlysz requested changes
Ok. Just the code convention.

2021-07-20 13:58 UTC, RSlysz commented on com.unity.render-pipelines.core/Runtime/Lights/LightAnchor.cs
> +        const float minDistance = 0.001f;
In convension, constant should be prefixed with k_
```suggestion
        const float k_MinDistance = 0.001f;
```

2021-07-20 13:58 UTC, RSlysz commented on com.unity.render-pipelines.core/Runtime/Lights/LightAnchor.cs
> +        float m_Distance = minDistance;
```suggestion
        float m_Distance = k_MinDistance;
```

2021-07-20 13:58 UTC, RSlysz commented on com.unity.render-pipelines.core/Runtime/Lights/LightAnchor.cs
> +            set { m_Distance = Mathf.Clamp(value, minDistance, 1000); }
```suggestion
            set { m_Distance = Mathf.Clamp(value, k_MinDistance, 1000); }
```

2021-07-22 15:54 UTC, pierre-unity reviewed
All changes from Remi accepted.

2021-08-05 13:18 UTC, RSlysz approved these changes

2021-08-09 19:12 UTC, closed without merging