[HDRP] Adding limitations of decal emissive positive contribution to the documentation
Unity-Technologies/Graphics pull request #5237
Opened 2021-07-27 14:01 UTC by remi-chapelain

### Purpose of this PR
Add missing documentation for the positive emissive contribution limitations for decals. (more info on [this forum thread](https://forum.unity.com/threads/why-decals-cant-override-emission-to-a-lesser-value.1147208/))
---
### Testing status
N/A
---
### Comments to reviewers
If you have better wording, feel free to suggest something or commit something else :)

2021-07-28 11:03 UTC, sebastienlagarde approved these changes

2021-07-29 10:21 UTC, Vic-Cooper requested changes
A couple of suggestions for you.

2021-07-29 10:21 UTC, Vic-Cooper commented on com.unity.render-pipelines.high-definition/Documentation~/Decal-Projector.md
> +- Decal Emissive is always an additive positive contribution and can't affect the existing emissive properties of the materials assigned to the objects.
Capitalize "Materials" for standard reasons and, if accurate, change "objects" to "GameObjects":
Materials assigned to GameObjects."

2021-07-29 10:21 UTC, Vic-Cooper commented on com.unity.render-pipelines.high-definition/Documentation~/Decal-Shader.md
Changed the phrasing a bit:

"Emissive decals always give an additive positive contribution. This property does not affect the existing emissive properties of the Materials assigned to a GameObject."

2021-07-29 10:41 UTC, merged