[HDRP] Light anchor fixes
Unity-Technologies/Graphics pull request #5238
Opened 2021-07-27 14:13 UTC by alelievr

### Purpose of this PR

- Fixed min distance of the light anchor not displaying 0 in the inspector
- Fixed Light anchor fields not working in prefabs (except orbit, elevation, and yaw which are not serialized in this component)

---
### Testing status

tested that the light anchor distance works correctly + `distance` and `Up direction` handle correctly prefabs.

https://user-images.githubusercontent.com/6877923/127169303-21f68267-98d7-4d26-b0f0-c5393daba179.mp4

![image](https://user-images.githubusercontent.com/6877923/127168890-f70a7a99-ae13-4007-92fd-0b09bb5f4981.png)

Note that there is an issue with Light Anchor prefabs when the distance is reverted, the transform of the gameobject is not updated using the reverted distance value (I'm not sure if we can fix that looking at how the component works currently)

2021-07-27 15:25 UTC, RSlysz requested changes

2021-07-27 15:25 UTC, RSlysz commented on com.unity.render-pipelines.core/Editor/Lighting/LightAnchorEditor.cs
> +                    manipulator.frameSpace = (LightAnchor.UpDirection)m_FrameSpaceProperty.enumValueIndex;
Check HDEditorUtils.GetEnumValue for details
Never use enumValueIndex to convert to type!
```suggestion
                    manipulator.frameSpace = (LightAnchor.UpDirection)m_FrameSpaceProperty.intValue;
```

2021-07-28 09:42 UTC, alelievr commented on com.unity.render-pipelines.core/Runtime/Lights/LightAnchor.cs
> +        [SerializeField, Min(0)]
No, we don't want the epsilon value to leak on the UI side

2021-07-28 09:49 UTC, RSlysz commented on com.unity.render-pipelines.core/Runtime/Lights/LightAnchor.cs
> +        [SerializeField, Min(0)]
So in Inspector you can put 0 but it is not supported when changing by scripts??
I insist. We must uniformize. If epsilon is not good, then 0 for both.

2021-07-28 11:49 UTC, RSlysz approved these changes

2021-07-28 12:54 UTC, sebastienlagarde approved these changes

2021-08-09 17:27 UTC, skhiat approved these changes

2021-08-30 13:06 UTC, iM0ve commented
**Test status: In Progress**

**Concerns:**
1) The new "light look at" property is great, but the Pivot is used as the anchor point instead of Centre of the object. I assume in some cases this could be an issue? For instance in the video I wanted to focus the light on Adams head, but the Pivot position was at his feet so the light ended up looking towards the ground. At the end of the vid i show where is the centre vs pivot location


https://user-images.githubusercontent.com/36502659/131343620-f61b90f5-ee65-467a-9f20-ba14241ac940.mov

2021-08-31 16:37 UTC, pierre-unity commented
I would suggest we also add an new "Position offset" under "Anchro Position Override" (indented), for all cases where the pivot of the "Anchor Position Override" is not exactly where it should logically be.

For instance, sometimes that pivot of a character is at the heal of the character, but the light should rather orbit the head. So with a Y-offset of roughly 1.6m, the light will be orbiting the right bit of the character.

2021-08-31 16:58 UTC, pierre-unity commented
Another issue, related to very high distances: it creates a "pivot drift", which does not happen with a custom anchor position override btw.

https://user-images.githubusercontent.com/39901544/131544869-da007ebe-45f4-46c7-96c2-9dad421f983e.mp4

2021-08-31 18:10 UTC, pierre-unity commented
Another potential improvement:

Can we get the list of all the bones from a gameobject, and pick it from a list? basically, if I pick an "Anchor Position Override" that has bones, we then display a drop down list of all bones attached to it and let the user pick a given bone transform.

See here how to get the list:
https://forum.unity.com/threads/solved-how-can-i-collect-bone-names-and-transforms.35810/#post-232041

2021-09-01 09:49 UTC, alelievr commented
So we'll move forward and merge the PR as it is now and do further improvement in a second PR (This PR is already too old :) )

2021-09-01 09:58 UTC, iM0ve approved these changes

2021-09-01 16:11 UTC, merged