Update DRS docs and TAAU
Unity-Technologies/Graphics pull request #5273
Opened 2021-08-02 11:38 UTC by FrancescoC-unity

Adding some more info on Dynamic Resolution doc page and adding some info on TAAU there. 

@Vic-Cooper  is about to push something on this branch, so other reviewers maybe wait for them :-) 

Addresses a couple of fogbugz issues too: https://fogbugz.unity3d.com/f/cases/1354326/ and https://fogbugz.unity3d.com/f/cases/1354324/

2021-08-02 12:49 UTC, kecho approved these changes

2021-08-02 15:15 UTC, sebastienlagarde approved these changes

2021-08-16 09:23 UTC, remi-chapelain commented
Added HD QA but waiting for @Vic-Cooper commit to have a look :)

2021-08-17 14:15 UTC, remi-chapelain requested changes
In addition to this, could it be mentioned that only FSR / DLSS and TAAU will still be applied when the resolution is forced at 100% ? And the reason why CAS and Catmulll-Rom won't is because they don't help with aliasing so it doesn't make sense to run those at 100% ! 

Thanks :)

2021-08-23 09:01 UTC, FrancescoC-unity commented
> In addition to this, could it be mentioned that only FSR / DLSS and TAAU will still be applied when the resolution is forced at 100% ? And the reason why CAS and Catmulll-Rom won't is because they don't help with aliasing so it doesn't make sense to run those at 100% !
> 
> Thanks :)

Tbf, FSR and CAS could both run at 100%. FSR is not doing any anti-aliasing, I think we allow it at 100% to have the extra sharpening it provides. 

DLSS and TAAU otoh do need to run 100% to avoid popping. 

Will add stuff later today (setting a reminder for when I finished catching up, feel free to give me a ping if I forget :) )

2021-08-23 09:43 UTC, remi-chapelain commented on com.unity.render-pipelines.high-definition/Documentation~/Dynamic-Resolution.md
> +It is best practice to keep the screen percentage above 50%. However, HDRP supports values up to 5, 100.
Here's, I believe it's oddly phrased. 
I would say something like, "HDRP supports values from 5% up to 100%"

2021-08-23 09:48 UTC, remi-chapelain requested changes
Had a thorough read of the new sections. 
Very useful information, especially parts of the different filters and TAA notes. 👍 

I allowed myself to fix two broken links in the previous commits. 

Before approving, I have 3 little remarks: 
- First one has already been raised in [my previous comment](https://github.com/Unity-Technologies/Graphics/pull/5273#pullrequestreview-731826096). Since it has been [asked on the forums](https://forum.unity.com/threads/using-cas-alongside-taa-just-for-the-sharpening-how-to-use-upscale-filters-at-100.1150967/#post-7425311), I think It would be great to add this on this page too. 
- Second, the doc says that "HDRP supports values up to 5, 100", in HDRP if you put a value above 100 (like 105%), it gets clamped to 100, which makes sense. However, if you put a value lower than 5 (like 2%), it does not get clamped to 5%. I think we should be on par here either on the doc or HDRP. 
- Lastly, having an image to compare filters is a great idea. Even though it's fairly obvious which is which when you know what to look for, I think it's still lacking a legend below or above like A. TAAU / B. Catmull-Rom, especially that they are announced in the wrong order compared to the image and that they unused have letter labels on the image :)
![image](https://user-images.githubusercontent.com/57442369/130427098-361bb159-70bc-466e-aed4-ab43dd11a907.png)

2021-08-24 11:58 UTC, remi-chapelain approved these changes
all good for me ! ✔️ 
Thanks for addressing the small concerns 🥳

2021-08-24 17:14 UTC, merged