Added synonyms to nodes for better searchability
Unity-Technologies/Graphics pull request #5330
Opened 2021-08-10 19:14 UTC by bencloward

This change adds synonyms to a set of nodes.  The synonyms are used for searches so that users don't have to know the exact name of the nodes to find what they are looking for.

# **Please read the [Contributing guide](CONTRIBUTING.md) before making a PR.**

* Read the [Graphics repository & Yamato FAQ](http://go/graphics-yamato-faq).

### Checklist for PR maker
- [ ] Have you added a backport label (if needed)? For example, the `need-backport-*` label. After you backport the PR, the label changes to `backported-*`.
- [ ] Have you updated the changelog? Each package has a `CHANGELOG.md` file.
- [ ] Have you updated or added the documentation for your PR? When you add a new feature, change a property name, or change the behavior of a feature, it's best practice to include related documentation changes in the same PR. If you do add documentation, make sure to add the relevant Graphics Docs team member as a reviewer of the PR. If you are not sure which person to add, see the [Docs team contacts sheet](https://docs.google.com/spreadsheets/d/1rgUWWgwLFEHIQ3Rz-LnK6PAKmbM49DZZ9al4hvnztOo/edit#gid=1058860420).
- [ ] Have you added a graphic test for your PR (if needed)? When you add a new feature, or discover a bug that tests don't cover, please add a graphic test.

---
### Purpose of this PR
Many of the nodes have slightly unexpected names or alternate names to the industry standard - so this allows users to enter search terms with names that are different and still come up with the correct results.  It makes searching more "intelligent"

---
### Testing status
Describe what manual/automated tests were performed for this PR

---
### Comments to reviewers
Notes for the reviewers you have assigned.

2021-08-10 20:27 UTC, jessebarker approved these changes
LGTM.

2021-08-11 22:55 UTC, xiaoxicici approved these changes
Awesome additions! Thanks for implementing these.

2021-08-12 04:14 UTC, GrantLamb-Unity requested changes
1. Synonyms which have the string as existing node names or other synonyms will highlight/select the first option in alphabetical order.
For Example, if you search for Divide, it will highlight Blend over the Divide node. So when a user types Divide and immediately hits enter they will get Blend.

Nodes with synonym name conflicts.
Blend - Divide, Multiply, Negate, Screen, Subtract, overwrite
Negate - Invert
OneMinus - Invert
Saturate - Clamp
Lerp - Blend

2. Searcher doesn't seem to support just numbers, the following do not find the node.
Float - 1
Vector2 - 2
Vector3 - 3
Vector4 - 4

3. Are Sawtooth Wave Node and Triangle Wave Nodes interchangable? They look very similar and are synonyms of each other. Is this intentional? Would it make sense to remove one rely on synonyms in this case? Or do we need to keep them as is so we don't break existing projects?

4. Probably unrelated and probably a searcher bug. When you search for something then attempt to use the up or down arrows a "Events cannot be dispatched more than once." exception will trigger.
![EventsCannotBeDispatched](https://user-images.githubusercontent.com/57373481/129137301-ed9a8210-c49f-4627-a646-bccea766d2a8.gif)

These aren't all required changes, I'd just like some more information before approving.

2021-08-12 14:41 UTC, bencloward commented
Thank you for the thorough testing, Grant!  This is great feedback.
1. I don't think it's a problem to have more than one result come up with a search term as long as each if the results are relevant - so in your list, I wouldn't called those conflicts, I would call them alternate results. Each of them actually does do the thing that the search term describes. If you feel this is a significant issue, I'd be happy to remove them, but I think it's better to give more results than fewer.
2. For the unsupported numbers, our options are to either remove the numbers as synonyms or leave them in and get a task in the back log to get numbers and symbols supported.  I have a whole list of symbols I'd also like to use as search terms as well, but those don't work either.  In this case, I don't think it's hurting anything to have the numbers in there for now and I would definitely like to have them work at some point.
3. Both sawtooth wave and triangle wave are triangular shaped waves - so I think it's fine that both come up for the other's search term.
4. Could you file this as a separate issue? The change I made doesn't cause that issue as far as I know.

2021-08-12 18:47 UTC, bencloward commented
@GrantLamb-Unity I talked with Marc and Sai about item 1 this morning.  Sai just submitted a change to make all search results sort by best match instead of alphabetical.  Going forward, Sai has plans to make node name results always come before synonym results.

2021-08-13 21:15 UTC, GrantLamb-Unity commented
Thanks for all the feedback! Your points makes sense to me and I'm glad we were able to adjust it so it finds the best match instead of the first alpha option.

I went ahead and wrote up the exception bug I found here: https://fogbugz.unity3d.com/f/cases/1358016/

2021-08-13 21:16 UTC, GrantLamb-Unity approved these changes

2021-08-13 22:47 UTC, merged