Fixed the volumetric clouds offset value bing clamped (case 1357318).
Unity-Technologies/Graphics pull request #5336
Opened 2021-08-12 11:36 UTC by anisunity

https://fogbugz.unity3d.com/f/cases/1357318/
https://fogbugz.unity3d.com/f/cases/1354920/
This PR removes the clamping on the shape offsets and adds two new parameters on the volume component to control the vertical speed of the shaping and erosion.
updated the doc

Testing status
Pair tested with @pierre-unity
For shape offset:
- made sure that all integer values return the same result
- made sure that ie behaved correctly while moving the slider
For vertical wind speed:
- made sure that the winds were in the correct orientation
- made sure that the winds affected correctly the clouds
- made sure that negative values worked as expected.

2021-08-12 12:23 UTC, iM0ve approved these changes
The PR is simple enough, I additionally checked that there ware no warnings and undo works.

**Demo:**

https://user-images.githubusercontent.com/36502659/129195940-b2e69072-4058-4f0d-9e06-f1c0ae3c562f.mp4

2021-08-12 12:39 UTC, JulienIgnace-Unity approved these changes

2021-08-12 13:53 UTC, Vic-Cooper requested changes
Small typo in the changelog to fix, otherwise good!

2021-08-12 13:53 UTC, Vic-Cooper commented on com.unity.render-pipelines.high-definition/CHANGELOG.md
> +- Fixed the volumetric clouds offset value bing clamped (case 1357318).
Fixed an issue that clamped the volumetric clouds offset value (case 1357318).

2021-08-12 16:35 UTC, pierre-unity requested changes
Only minor typo in the doc.

Tested the actual feature and working well.

2021-08-12 16:35 UTC, pierre-unity commented on com.unity.render-pipelines.high-definition/Documentation~/Override-Volumetric-Clouds.md
> +| **Global HorizontalWind Speed**  | Sets the global horizontal wind speed in kilometers per hour.<br />This value can be relative to the **Global Wind Speed** defined in the **Visual Environment**.
Typo: "HorizontalWind" should be "Horizontal Wind"

2021-08-13 09:10 UTC, Vic-Cooper approved these changes
lgtm!

2021-08-13 13:20 UTC, anisunity commented
errors in the tests have nothing to do with clouds @JulienIgnace-Unity

2021-08-13 13:22 UTC, pierre-unity approved these changes
All good, working well and typo fixed.

2021-08-16 08:28 UTC, merged