Fix LensFlare occlusion on scene view
Unity-Technologies/Graphics pull request #5353
Opened 2021-08-16 12:46 UTC by skhiat

Fix LensFlare occlusion on scene view

![KchJjvaILm](https://user-images.githubusercontent.com/55133890/129565889-a20cfcf7-8ddf-4cd1-85b8-d0a5c0070cb6.gif)
![GvKmTiSipC](https://user-images.githubusercontent.com/55133890/129565892-1fcd180a-365f-4334-a700-d89be0d63c1c.gif)

2021-08-24 17:54 UTC, sebastienlagarde commented
Hey, what's the status of this PR?

2021-09-23 11:26 UTC, iM0ve reviewed
Hey, thanks for adding the showcase of before/after. Was there something else tested or needs to be tested? Any tips what QA should look at in more detail?

2021-09-23 12:58 UTC, skhiat commented
> Hey, thanks for adding the showcase of before/after. Was there something else tested or needs to be tested? Any tips what QA should look at in more detail?

Updated.

2021-09-23 16:15 UTC, kecho commented on com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/LensFlareMergeOcclusionDataDriven.compute
> +void MainCS(uint3 dispatchThreadId : SV_DispatchThreadID)
@soufianekhiat while this is fine for now, I wanna challenge you:
You have an entire wave (64 threads) that you could exploit, you could dispatch a 8x8 (64 threads) and in the y coordinate load your history into lds.
You can then do a parallel reduction or interlock min on a final value and avoid tapping 8 times the history resource :)

Just fun programming if you are up to it! Please dont consider this as a blocker

2021-09-23 23:50 UTC, skhiat commented on com.unity.render-pipelines.high-definition/Runtime/PostProcessing/Shaders/LensFlareMergeOcclusionDataDriven.compute
> +void MainCS(uint3 dispatchThreadId : SV_DispatchThreadID)
Updated with 3 barriers & LDS

2021-09-24 12:03 UTC, iM0ve approved these changes
Looks good. I reproduced the issue on master and then tested:
* Issue no longer appears with default settings in Scene and Game views
* Modified all TAA settings in an attempt to reintroduce flickering
* Used all Lens flare occlusion settings in an attempt to reintroduce flickering
* Tested with several lights visible on screen
* Tested occlusion that is based on offscreen instead of geometry

https://user-images.githubusercontent.com/36502659/134671045-6a6a759c-1819-4605-a25f-54cd4d184915.mp4


https://user-images.githubusercontent.com/36502659/134671059-2daf45ea-aa69-4edb-8e4c-cf28af5f9211.mp4

2021-09-27 18:19 UTC, kecho requested changes
Requesting some minor updates. Please see comments.

2021-09-27 18:19 UTC, kecho commented on com.unity.render-pipelines.core/Runtime/PostProcessing/LensFlareCommonSRP.cs
> +        /// <param name="_FlareTex">ShaderID for the FlareTex</param>
The parameters dont seam to match the documentation.

2021-09-27 18:19 UTC, kecho commented on com.unity.render-pipelines.core/Runtime/PostProcessing/LensFlareCommonSRP.cs
> +            Vector3 cameraPositionWS,
Missing docs?

2021-09-27 18:19 UTC, kecho commented on com.unity.render-pipelines.core/Runtime/PostProcessing/LensFlareCommonSRP.cs
> +                RTHandles.Release(occlusionRT);
Set to null after Releasing.

2021-09-27 18:19 UTC, kecho commented on com.unity.render-pipelines.core/Runtime/PostProcessing/LensFlareCommonSRP.cs
> +                if (currentIntensity <= 0.0f)
Perf, can we move this earlier in the loop?

2021-09-28 13:39 UTC, kecho approved these changes

2021-09-29 16:53 UTC, merged