Clarified lists and removed unnecessary bold
Unity-Technologies/Graphics pull request #5403
Opened 2021-08-19 10:35 UTC by emilybrown1

Updating the style of Override-Volumetric-Clouds

2021-08-19 14:24 UTC, Vic-Cooper requested changes
Remove Texture/Textures.

2021-08-19 15:19 UTC, Vic-Cooper requested changes
Phrasing!

2021-08-19 15:19 UTC, Vic-Cooper commented on com.unity.render-pipelines.high-definition/Documentation~/Override-Volumetric-Clouds.md
> +| - **Cloud Map Offset**            | The **X** and **Y** UV offset for the cloud map Textures. HDRP uses the **X** and **Y** values to offset the clouds across the sky.<br/>If **Cloud Control** is s
Make the start of this sentence the same as the other change you made: 

"The **X** and **Y** UV offset for one or more cloud map Textures."

Consistency is key! :D

2021-08-24 09:56 UTC, Vic-Cooper approved these changes
Looks good! :)

2021-09-01 10:58 UTC, sebastienlagarde approved these changes

2021-09-01 10:59 UTC, merged