[WIP] Instance indexing in shader
Unity-Technologies/Graphics pull request #5450
Opened 2021-08-26 15:15 UTC by ludovic-theobald

# **[WIP] Instance indexing in shader.**

---
### Overview of the changes 

- Added helper functions to retrieve the particleIndex/instanceIndex/indexInInstance etc.
- Binary search and indirection to find the instance in a vertex shader (requires some additionnal input from the runtime)
- The aligned capacity is set as a compile time constant

---
### Testing status
Tested on particle quads, particle meshes, particle strip. But limited because I didn't emulate multiple instances in a batch.

---
### Comments to reviewer
UpdateStrips.compute (!= VFXUpdate.template with HAS_STRIPS) hasn't been taken into account yet.

2021-08-30 07:14 UTC, julienf-unity reviewed
All the reformatting makes things a bit more difficult to review. Is it legit btw?

2021-08-30 07:14 UTC, julienf-unity commented on com.unity.visualeffectgraph/Editor/Compiler/VFXCodeGenerator.cs
> +            perPassIncludeContent.WriteLine("#include \"Packages/com.unity.visualeffectgraph/Shaders/Common/VFXInstancing.hlsl\""); //Should it go in Global Includes ?
if it does not rely on per pass / SRP defines then yes probably

2021-08-30 07:14 UTC, julienf-unity commented on com.unity.visualeffectgraph/Shaders/Common/VFXInstancing.hlsl
> +    return threadId / nbMax;
That does not sound correct, as as you said nbMax is potentially not fixed per instance

2021-08-30 07:14 UTC, julienf-unity commented on com.unity.visualeffectgraph/Shaders/Common/VFXInstancing.hlsl
> +    return threadId / nbMax;
But my other concern is that instanceIndex must be scalar whenever possible, so basically depends only on scalar inputs (like SV_GroupId), here it depends on per thread input, so will use VGPR.

2021-08-30 07:14 UTC, julienf-unity commented on com.unity.visualeffectgraph/Shaders/VFXOutputUpdate.template
> +	uint index = GetIndexInAttributeBuffer(instanceIndex, indexInInstance);
Maybe having a struc to hold those variable will be clearer?

2021-08-30 07:14 UTC, julienf-unity commented on com.unity.visualeffectgraph/Shaders/VFXParticleHeader.template
> +StructuredBuffer<uint> instanceIndirectionBuffer;
Beware because on other gfx devices it will be undefined behaviour

2021-08-30 13:18 UTC, ludovic-theobald commented
> All the reformatting makes things a bit more difficult to review. Is it legit btw?
Not sure what's the deal with the reformatting, AFAIK they shouldn't be concerned with the formatting hooks.

Following this morning's conversation, I separated the computation of the indices in Compute and in Output, since they rely on different assumptions. 
In the compute shaders, instanceIndex is extracted using SV_GroupID, assuming that the dispatches will be of size multiple of NB_THREADS_PER_GROUP. In vertex shader, instanceIndex will still use a VGPR.

The defines (VFX_USE_INSTANCING and others) are set globally from VFXCodeGenerator.cs, but this is only for testing. The logic of how these defines are set and where is not tackled in this PR.

2021-08-30 14:22 UTC, gabrieldelacruz requested changes
As discussed over the call, still some adjustments are needed to remove redundancy.
It looks good, everything seems to be already there.
Thanks!

2021-08-30 14:22 UTC, gabrieldelacruz commented on com.unity.visualeffectgraph/Shaders/VFXInstancing.hlsl
> +                            #if VFX_INSTANCING_VARIABLE_SIZE
I think you should try to unify this 2 functions, it will be easier to maintain

2021-08-31 08:23 UTC, ludovic-theobald commented on com.unity.visualeffectgraph/Editor/Compiler/VFXCodeGenerator.cs
> +            perPassIncludeContent.WriteLine("#include \"Packages/com.unity.visualeffectgraph/Shaders/Common/VFXInstancing.hlsl\""); //Should it go in Global Includes ?
It has been moved inside of VFXCommon.hlsl.

2021-09-02 12:11 UTC, gabrieldelacruz commented on com.unity.visualeffectgraph/Shaders/VFXInstancing.hlsl
> +                            uint nbInstancesInDispatch,
nbInstancesInDispatch should be a uniform as well or, even better, extracted from the buffer with StructuredBuffer::GetDimensions. No need to pass it as an argument

2021-09-02 12:11 UTC, gabrieldelacruz commented on com.unity.visualeffectgraph/Shaders/VFXInstancing.hlsl
> +                            #if VFX_INSTANCING_VARIABLE_SIZE
This is still not a single function. I understand the difficulty of unifying the instanceIndex obtained from the index and the optimized form that uses the group id, but it is just a matter of taking the specific code to the definitions in VFXParticleCommon.template. In the end, it is still a division, it just takes different values.

2021-09-03 07:48 UTC, gabrieldelacruz approved these changes
Looks good!
There will be more changes to this code, specially regarding nbMax that will depend on the instanceIndex, but it is pointless to keep iterating now until we have a better picture.
Good job, thanks!

2022-02-17 16:31 UTC, closed without merging