[HDRP] Adding information about SSGI and Emissive incompatibility in documentation
Unity-Technologies/Graphics pull request #5468
Opened 2021-08-30 12:25 UTC by remi-chapelain

### Purpose of this PR
This PR is needed because a lot of users are thinking this is a bug. 
Now we can just point to this documentation bit when the question is popping up. 

---
### Comments to reviewers
If someone have a better wording or want to correct things, please do it.

2021-08-31 10:18 UTC, iM0ve approved these changes

2021-08-31 12:20 UTC, sebastienlagarde approved these changes

2021-09-02 13:52 UTC, emilybrown1 requested changes

2021-09-02 13:52 UTC, emilybrown1 commented on com.unity.render-pipelines.high-definition/Documentation~/Override-Screen-Space-GI.md
> +In Deferred rendering mode, Screen Space Global Illumination and Ray-Traced Global Illumination share a buffer with emissive thus overwriting emissive data.
```suggestion
In Deferred rendering mode, Screen Space Global Illumination and Ray-Traced Global Illumination share a buffer with emissive, which overwrites emissive data. 
```

2021-09-02 13:52 UTC, emilybrown1 commented on com.unity.render-pipelines.high-definition/Documentation~/Override-Screen-Space-GI.md
> +* Disabling [Receive SSR/SSGI](snippets/shader-properties/surface-options/receive-ssr.md) flag on the emissive materials.
```suggestion
* Disable [Receive SSR/SSGI](snippets/shader-properties/surface-options/receive-ssr.md) flag on the emissive materials.
```

2021-09-02 13:52 UTC, emilybrown1 commented on com.unity.render-pipelines.high-definition/Documentation~/Override-Screen-Space-GI.md
> +* Using [Force Forward Emissive](snippets/shader-properties/advanced-options/force-forward-emissive.md) on the emissive materials.
```suggestion
* Use [Force Forward Emissive](snippets/shader-properties/advanced-options/force-forward-emissive.md) on the emissive materials.
```

2021-09-02 13:52 UTC, emilybrown1 commented on com.unity.render-pipelines.high-definition/Documentation~/Override-Screen-Space-GI.md
> +* Using Forward rendering.
```suggestion
* Use Forward rendering.
```

2021-09-02 13:52 UTC, emilybrown1 commented on com.unity.render-pipelines.high-definition/Documentation~/Override-Screen-Space-GI.md
> +There is multiple ways to recover the emissive contribution of the scene materials:
```suggestion
There are multiple ways to recover the emissive contribution of the scene materials: 
```

2021-09-02 14:45 UTC, emilybrown1 approved these changes

2021-09-02 15:37 UTC, sebastienlagarde approved these changes

2021-09-02 15:38 UTC, merged