UNI-11984 - Lens Flare docs
Unity-Technologies/Graphics pull request #5640
Opened 2021-09-13 16:02 UTC by JordanL8

### Purpose of this PR
Work for https://unity3d.atlassian.net/browse/UNI-11984. Consisted of changing image names and links to adhere to naming conventions, adding some workflow information for creating a lens flare, and adding missing pages to the toc.

2021-09-15 07:38 UTC, erikabar approved these changes
Reviewed doc changes, looks good.

2021-09-16 16:04 UTC, Vic-Cooper requested changes
Found a teeny tiny typo!

2021-09-16 16:04 UTC, Vic-Cooper commented on com.unity.render-pipelines.high-definition/Documentation~/shared/lens-flare/lens-flare-component.md
> +1. Create or select a GameObject to attach the lens flare too.
"Too" :D Should be "to".

2021-09-16 18:15 UTC, sebastienlagarde approved these changes

2021-09-16 18:15 UTC, sebastienlagarde commented
adressed pr feedback, merging

2021-09-16 18:15 UTC, merged