Srp workflows - Improvements working with Volume Components on a XPipeline Projects
Unity-Technologies/Graphics pull request #5745
Opened 2021-09-21 10:26 UTC by alex-vazquez

---
### Purpose of this PR
https://jira.unity3d.com/browse/XPIPELINE-327
https://jira.unity3d.com/browse/XPIPELINE-328

Warning for Volume Components from another pipeline:
![image](https://user-images.githubusercontent.com/76204843/134154210-fc99bce5-40b4-489d-965d-f298fc302078.png)

Add an option to hide not overrided parameters for a component
![image](https://user-images.githubusercontent.com/76204843/134154339-1625edb4-138f-45b4-a111-61346b07a25f.png)
![image](https://user-images.githubusercontent.com/76204843/134154393-74509d30-1702-4208-86b8-36eb4f6853cb.png)

---
### Testing status
Describe what manual/automated tests were performed for this PR

---
### Comments to reviewers
Notes for the reviewers you have assigned.

2021-09-22 10:06 UTC, RSlysz approved these changes
Looks good but please rename the parameter for better code readability.

2021-09-22 10:06 UTC, RSlysz commented on com.unity.render-pipelines.core/Runtime/Volume/VolumeProfile.cs
> +        void SetIsSupportedOnCurrentPipeline(VolumeComponent component, Type currentPipelineType)
[Readability] Either rename `currentPipelineType` to `renderPipelineType` or make the method find who is the current one.

2021-09-22 10:20 UTC, RSlysz commented on com.unity.render-pipelines.core/Runtime/Volume/VolumeProfile.cs
> +        void SetIsSupportedOnCurrentPipeline(VolumeComponent component, Type currentPipelineType)
Same goes for method name. It should be `SetIsSupportedOnPipeline` if the method don't get who is the current one

2021-09-28 10:23 UTC, TheoWong-pixel approved these changes

2021-09-29 12:29 UTC, arttu-peltonen requested changes
Happened to notice a typo in user-facing text, so jumped in to let you know :)

2021-09-29 12:29 UTC, arttu-peltonen commented on com.unity.render-pipelines.core/Editor/Volume/VolumeComponentListEditor.cs
> +            menu.AddItem(EditorGUIUtility.TrTextContent("Show Only Overrided Parameters"), targetEditor.showOnlyOverridedParameters, () => targetEditor.showOnlyOverridedParameters = !targetEditor.sho
Proper form is "overridden", not "overrided". Replace at least user-facing text, preferably also variable names.

2021-10-19 08:01 UTC, arttu-peltonen requested changes
Sorry to nitpick but "overriden" is still not correct, "overridden" with two d's is correct spelling.

2021-11-19 12:19 UTC, closed without merging