[Universal] Fixed changing camera position in beginCameraRendering won't work for XR
Unity-Technologies/Graphics pull request #5790
Opened 2021-09-23 20:41 UTC by thomas-zeng

---
### Purpose of this PR
- Fixed fogbugz case 1365000

---
### Testing status
- The repro project in fogbugz case is for 2021.2. I have created a new project in 2022.1 with the beginCameraRendering script from the repro case. Tested with new project and verified the issue is fixed.
- Also backported the changes to 2020.2/staging branch locally and tested the repro project against the local branch. Verified the issue is fixed there.

---
### Comments to reviewers
Notes for the reviewers you have assigned.

2021-09-24 08:17 UTC, phi-lira approved these changes
We should add a test to capture this bug.

2021-09-24 14:31 UTC, fabien-unity approved these changes

2021-09-24 17:56 UTC, thomas-zeng commented
Adding XR QA ryan as reviewer

2021-09-30 21:17 UTC, ryanhy-unity commented
This change appears to break color texture sampling in my shader graph shader in my test project.  When I use master URP the render texture samples the color correctly but when I use this code that texture is mostly black.  I'm using the URP E2E test project from https://github.cds.internal.unity3d.com/unity/xr.xrautomatedtests.

2021-09-30 21:18 UTC, ryanhy-unity requested changes
This change seem to break a shader I created with Shader Graph to sample background color.  My depth sampling shader seems a bit off too but I'm not as certain there.  Let me know if you'd like more details, render doc caps or whatnot.

2021-10-04 22:08 UTC, ryanhy-unity commented
Apparently the issues I was seeing while testing this were due to issues in master and not this PR.  I did actually test master during this to make sure that wasn't the case but I think I failed to pull latest master and so missed it.  Here's the bug if you're interested.  https://fogbugz.unity3d.com/f/cases/1370540/

Given that the issue I found was not a regression in this PR and the bug was indeed fixed I think this PR is good.  Approved.

2021-10-04 22:08 UTC, ryanhy-unity approved these changes

2021-10-04 23:12 UTC, merged