Reviewed changes to path tracing documentation
Unity-Technologies/Graphics pull request #5823
Opened 2021-09-28 13:02 UTC by Vic-Cooper

As per the changes made in [#5551](https://github.com/Unity-Technologies/Graphics/pull/5551)

2021-09-28 13:03 UTC, Vic-Cooper commented
@eturquin I changed your initial layout and notes so please check if I preserved your meaning.

2021-09-29 17:26 UTC, eturquin requested changes

2021-09-29 17:26 UTC, eturquin commented on com.unity.render-pipelines.high-definition/Documentation~/Ray-Tracing-Path-Tracing.md
> +Single-sided with no Transmission.
Should be "Single-sided, or no Transmission"

2021-09-29 17:26 UTC, eturquin commented on com.unity.render-pipelines.high-definition/Documentation~/Ray-Tracing-Path-Tracing.md
> +| **Thin**         | A thin box surface type, similar to **Box** with a fixed thickness of 5cm. Select this for thin window-like surfaces. <br/>The behaviour of the **Thin** refraction model does not
| **Thin** | A thin surface type, characterized by infinitesimal thickness. Select this for thin window-like surfaces. <br/>The behaviour of the **Thin** refraction model does not change with path tracing enabled .<br/><br/>Suitable for thin objects like a soap bubble or a glass window. | A double-sided Material that has its **Normal mode** set to **Flip** or **Mirror**. |

2021-09-29 17:26 UTC, eturquin commented on com.unity.render-pipelines.high-definition/Documentation~/Ray-Tracing-Path-Tracing.md
> +| **Sphere**       | A sphere-shaped model that produces a magnifying glass-like effect to refraction. <br/><br/>Suitable for thick objects like a paperweight or a crystal ball. | A double-sided Mate
Box and Sphere are **exactly** the same in path tracing, they correspond to a **thick** mode. It's a bit confusing to have them separate in this table, as if they have different effects.

2021-09-29 17:26 UTC, eturquin commented on com.unity.render-pipelines.high-definition/Documentation~/Ray-Tracing-Path-Tracing.md
> +| **None**         | A thin refractive surface, hardcoded to be fully smooth to simulate alpha blending.<br/>The behaviour of the **None **refraction model does not change with path tracing enabled .
I wouldn't say that this mode is suitable for anything really, it's just here to keep compatibility with raster mode when you switch to path tracing, but other than that **thin** should be prefered in every single situation.

2021-09-29 17:26 UTC, eturquin commented on com.unity.render-pipelines.high-definition/Documentation~/Ray-Tracing-Path-Tracing.md
> +HDRP can perform effects like light refraction and absorption in transmissive objects, or subsurface scattering, more easily when you use path tracing setting than in rasterization . This means they
It's not performing those effects "more easily" (as in, it's not computing them faster, or with less resources), but rather can express them "more naturally" given the different way of representing light transport simulation.

2021-09-30 13:30 UTC, Vic-Cooper commented
Thanks for your feedback @eturquin I'm implementing your suggested changes in a[ google doc](https://docs.google.com/document/d/1dC2syNIT1hGV-Bz64RGClzdZfXbUVhx0sSiKZ9eQYUg/edit) so I can get it reviewed by docs editorial.

2021-09-30 13:32 UTC, eturquin commented on com.unity.render-pipelines.high-definition/Documentation~/Ray-Tracing-Path-Tracing.md
> +HDRP can perform effects like light refraction and absorption in transmissive objects, or subsurface scattering, more easily when you use path tracing setting than in rasterization . This means they
> Thanks for your feedback @eturquin I'm implementing your suggested changes in a[ google doc](https://docs.google.com/document/d/1dC2syNIT1hGV-Bz64RGClzdZfXbUVhx0sSiKZ9eQYUg/edit) so I can get it reviewed by docs editorial.

Sounds good! :)

2021-09-30 13:32 UTC, eturquin commented
> Thanks for your feedback @eturquin I'm implementing your suggested changes in a[ google doc](https://docs.google.com/document/d/1dC2syNIT1hGV-Bz64RGClzdZfXbUVhx0sSiKZ9eQYUg/edit) so I can get it reviewed by docs editorial.

Sounds good! :)

2021-11-22 17:28 UTC, closed without merging