Improved Batch Renderer and BatchRendererGroup Test Projects
Unity-Technologies/Graphics pull request #5842
Opened 2021-09-29 13:19 UTC by cinight

### Checklist for PR maker
- [ ] Have you added a backport label (if needed)? For example, the `need-backport-*` label. After you backport the PR, the label changes to `backported-*`.
- [ ] Have you updated the changelog? Each package has a `CHANGELOG.md` file.
- [ ] Have you updated or added the documentation for your PR? When you add a new feature, change a property name, or change the behavior of a feature, it's best practice to include related documentation changes in the same PR. If you do add documentation, make sure to add the relevant Graphics Docs team member as a reviewer of the PR. If you are not sure which person to add, see the [Docs team contacts sheet](https://docs.google.com/spreadsheets/d/1rgUWWgwLFEHIQ3Rz-LnK6PAKmbM49DZZ9al4hvnztOo/edit#gid=1058860420).
- [ ] Have you added a graphic test for your PR (if needed)? When you add a new feature, or discover a bug that tests don't cover, please add a graphic test.

---
### Purpose of this PR
Why is this PR needed, what hard problem is it solving/fixing?

---
### Testing status
Describe what manual/automated tests were performed for this PR

---
### Comments to reviewers
Notes for the reviewers you have assigned.

2021-09-29 15:53 UTC, vincent-breysse commented on com.unity.render-pipelines.high-definition/Runtime/Material/Lit/LitProperties.hlsl
> +
TODO : Do this for all the other files including those IDs in the PerMaterial cbuffer

2021-10-07 07:42 UTC, sebbbi commented on com.unity.render-pipelines.high-definition/Editor/Material/ShaderGraph/HDTarget.cs
>              { Pragma.InstancingOptions(InstancingOptions.NoLodFade) },
BatchRendererGroup API nowadays supports LOD fade. This line should be removed. Hybrid Renderer doesn't support LOD fade yet, but I would assume that the default value (zero) it feeds to the BRG API is OK. Hybrid Renderer also explicitly doesn't enable the DrawCommand LOD Crossfade bit, meaning that there should be no complications there.

2021-10-07 07:45 UTC, sebbbi approved these changes

2021-10-22 10:19 UTC, JussiKnuuttila approved these changes

2021-10-22 10:20 UTC, joeldevahl approved these changes

2021-10-22 18:08 UTC, cdxntchou requested changes
Love the changes!

Definitely make sure the shadergraph import version is bumped.

2021-10-25 11:20 UTC, ernestasKupciunas approved these changes
Looks good! I ran provided testing scenes using URP on some Android and iOS devices
Testing doc: https://docs.google.com/document/d/12xWskZtDc5aFrKH0BwIFPm3zzEq_t9LMye1K7VXR6Iw/edit

2021-10-25 11:56 UTC, eh-unity approved these changes
I looked at Universal side only, skimmed over the rest. LGTM.

2021-10-27 21:36 UTC, cdxntchou approved these changes
Looks good!

2021-10-28 07:03 UTC, phi-lira approved these changes

2021-10-29 09:03 UTC, TomasKiniulis approved these changes
All good on HDRP side. Approving on behalf HDRP QA. Test status in Test Doc of pr description.

2021-11-04 23:46 UTC, GrantLamb-Unity commented
I ran some tests with the Hybrid Renderer/Shadergraph with the following setup:
`graphics/hrnext` C++ branch (Editor)
`hybrid-renderer-2021` DOTS branch
`graphics/hrnext` Graphics branch (this PR)

I verified that I was able to set up a per instance Material Override and I overrode a Color property of a Material with Shadergraph. I pretty much followed the steps [listed here](https://docs.unity3d.com/Packages/com.unity.rendering.hybrid@0.11/manual/material-overrides-asset.html). I'll be adding these steps and this workflow to our Shadergraph manual test suite in TestRail.~

2021-11-04 23:46 UTC, GrantLamb-Unity approved these changes

2021-11-08 09:37 UTC, sebastienlagarde approved these changes

2021-11-08 09:43 UTC, arnaudcarre approved these changes

2021-11-08 10:19 UTC, merged