Enable iris normal for Eye shader
Unity-Technologies/Graphics pull request #5880
Opened 2021-10-04 09:41 UTC by adrien-de-tocqueville

### Purpose of this PR

Fix https://fogbugz.unity3d.com/f/cases/1367911/

Iris normal was not enabled in the graph options, now it is to match the Eye samples.

Also renamed the properties to have spaces in their names, and moved them to categories

before:
![before](https://user-images.githubusercontent.com/61282776/135828818-89e2209b-4223-4ab3-99da-9aca9154031c.png)
after:
![after](https://user-images.githubusercontent.com/61282776/135829052-c2fca3f8-6b67-4fa5-bc25-ee2c2a2aeb39.png)

---
### Testing status

verified that iris normal now works by default with the eye shadergraph.
verified that shader properties didn't change name in the shader

2021-10-04 10:19 UTC, remi-chapelain requested changes
Great change ! 
But unfortunately, importing the material samples and opening the eye scene does not include the change. I think it's because the sample uses another graph bundled with the sample called [SG_Eye](https://github.com/Unity-Technologies/Graphics/blob/master/com.unity.render-pipelines.high-definition/Samples~/MaterialSamples/Shadergraphs/SG_Eye.shadergraph) (which is indentical execept your latest changes). 

What would be best ? To make the same changes in this graph or try to use the graph you changed in RenderPipelineResources for the samples ?

2021-10-04 10:31 UTC, adrien-de-tocqueville commented
I would say using the HDRP Eye shader n the sample is the best, to avoid issues like the one in the fogbugz appear again.
But maybe it's important for users to have an editable graph in the sample, in which case we should duplicate it. Do you have an idea if it's the case ?

2021-10-05 12:59 UTC, remi-chapelain approved these changes
All good ! ✔️

2021-10-05 13:19 UTC, anisunity commented
@adrien-de-tocqueville think to add me on the review next time you change something related to the eye shader! Thanks

2021-10-05 19:47 UTC, anisunity approved these changes

2021-10-19 13:15 UTC, merged