Added controls for the users to manually feed the ray tracing acceleration structure that should be used for a given camera (case 1370678).
Unity-Technologies/Graphics pull request #5932
Opened 2021-10-06 11:12 UTC by anisunity

https://fogbugz.unity3d.com/f/cases/1370678/
![image](https://user-images.githubusercontent.com/42026998/136192027-d8787fe0-38fe-49a0-881b-cd3785f6c835.png)

Testing status
I need to add a test that creates a ray tracing acceleration structure and feeds it manually to the camera.
Made sure that when the user didn't feed an acceleration structure the ray tracing effects were not executed.
Made sure that everything still worked as expected when in automatic mode.

2021-10-06 15:44 UTC, remi-chapelain requested changes
Fixed a few things:
- Changed the property name to Acceleration Structure Build Mode to avoid confusion with the act of building a player
- Put the new property in additional properties section
- Updated the tooltip and the doc with a little bit more information
- Tested with other RT effects
--- RTGI ✔️ 
--- RTAO ✔️ 
--- SubSurfaceScattering ✔️ 
--- Pathtracer - Some issues 
--- Recursive Rendering - Some issues
--- Ray Traced Shadows - Crash
- Added a new section in documentation with a snippet example on how to properly feed manually built RTAS to the camera
- Added @Vic-Cooper as reviewer for the new added section in documentation

![image](https://user-images.githubusercontent.com/57442369/136232369-817d3fd3-69d6-4c04-ba47-f90b5ba28a98.png)

Now about issues:
- Found a crash when using ray traced shadow in manual mode. ⚔️ 
- Also, layer mask (in RTR, RTGI, RTAO, PAthtracer) does not work anymore, I guess it makes sense but maybe it could be interesting to note it somewhere that it's intrinsically not compatible with lights layer since it's users who feeds the objects. 
- Also, with pathtracer and custom RTAS, you get unexpected results like losing secondary and more bounces for some reasons. 
- Objects in recursive rendering pass not passed in the RTAS are black, so there's no fallback to raster for recursive rendering.

2021-10-13 07:12 UTC, anisunity commented
i'll be checking the crashes today

2021-10-13 12:15 UTC, anisunity commented
The PR https://github.com/Unity-Technologies/Graphics/pull/5988 needs to be merged first before this PR gets merged.

2021-10-20 08:01 UTC, anisunity commented
yes i started updating it

2021-10-20 15:10 UTC, kecho approved these changes

2021-10-20 15:10 UTC, kecho commented on com.unity.render-pipelines.high-definition/Runtime/Lighting/LightLoop/LightLoop.cs
> +                    GetRayTracingState(),
LGTM

2021-10-20 15:59 UTC, remi-chapelain commented on com.unity.render-pipelines.high-definition/Documentation~/Ray-Tracing-Settings.md
> +HDRP provides a utility function that adds objects to the ray tracing acceleration structure.
This was the previous version and needs to be updated

2021-10-21 10:25 UTC, remi-chapelain requested changes
Tested all ray traced effects independently and everything is working as it should, even though it's not what the user would necessarily expect when some object are not included in the RTAS. ✔️ 

To avoid this confusion, I would like the documentation to include the fact that if you are using a ray traced effect on an object (ray traced shadow, RTAO or RTR for example) and this object is not included in the RTAS, because of how the ray tracing pipeline is made, the effect won't fallback to its rasterization counterpart. 
Meaning that instead of raytraced shadow you'll have no shadows, instead of RTR, you won't have SSR, you will have no reflections.. etc. 
An image from the test could help illustrate this result !

2021-10-21 22:31 UTC, anisunity commented
Fixed test, relaunching dxr tests and then merging

2021-10-22 10:45 UTC, merged