Material API what's new
Unity-Technologies/Graphics pull request #6020
Opened 2021-10-14 10:41 UTC by adrien-de-tocqueville

### Purpose of this PR

add section in what's new for #5761 

Also add what's new for main light node #5086

2021-10-18 16:54 UTC, sebastienlagarde approved these changes

2021-11-04 19:06 UTC, sebastienlagarde commented
@adrien-de-tocqueville guess you will need to create a Jira task?

2021-11-08 12:11 UTC, Vic-Cooper requested changes
Added re-write suggestions in comments. Changed the order of information to make the new feature more clear :)

2021-11-08 12:11 UTC, Vic-Cooper commented on com.unity.render-pipelines.high-definition/Documentation~/whats-new-13.md
> +
### New Main Light Direction ShaderGraph node

From HDRP version 13.0,  [ShaderGraph](https://docs.unity3d.com/Packages/com.unity.shadergraph@13.1/manual/index.html) includes a new node called **Main Light Direction** that you can use to control the direction of the main light.
For more information, see [Main Light Direction Node](https://docs.unity3d.com/Packages/com.unity.shadergraph@13.1/manual/Main-Light-Direction-Node.html).

2021-11-08 12:11 UTC, Vic-Cooper commented on com.unity.render-pipelines.high-definition/Documentation~/whats-new-13.md
> +To enable or disable most HDRP shader features on a material, changes need to be done on the keyword state and sometimes on one or more properties. This is done automatically when editing values thou
From this HDRP version, you can use new APIs to run shader validation steps from script at runtime, both in the editor and in standalone builds. You can use this to change the keyword state or one or more properties in order to enable or disable HDRP shader features on a Material.

2021-11-08 14:33 UTC, adrien-de-tocqueville commented
i forgot to add the new node to the table of content for shadergraph doc. So i did it in this PR

2021-11-22 17:36 UTC, sebastienlagarde commented
Feedback adressed, merging

2021-11-22 17:36 UTC, merged