fixed passive voice
Unity-Technologies/Graphics pull request #6092
Opened 2021-10-21 08:58 UTC by emilybrown1

fixed passive voice in Decal doc

2021-11-02 11:57 UTC, Vic-Cooper requested changes

2021-11-04 11:58 UTC, Vic-Cooper requested changes
smol tweak...

2021-11-04 11:58 UTC, Vic-Cooper commented on com.unity.render-pipelines.high-definition/Documentation~/Decal.md
> +### How decals affect performance
I like how you've changed this title, but this section is specifically about Decal Layers. Replace "decals" with "Delal Layers" and we're good :)

2021-11-04 13:19 UTC, Vic-Cooper approved these changes
Great! Done! :D

2021-11-04 19:56 UTC, sebastienlagarde approved these changes

2021-11-04 19:56 UTC, merged