Improved Area Light Support for Hair
Unity-Technologies/Graphics pull request #6157
Opened 2021-10-27 20:05 UTC by johnpars

### Purpose of this PR
This PR adds an improved method for supporting rectangular area lights for hair. 

Due to lack of support for LTC with anisotropic models, we have up until now fallen back to the GGX LTC for hair. This PR tries to improve on this by instead deferring to a "Representative Point" as a stop-gap method for both the Approximate (Kajiya) and Physical (Marschner) based model until further research is given for LTC. 

The result of this work is that we should now be much closer to our references. 

Below is some results for our approximation for Physical.

![image](https://user-images.githubusercontent.com/28882975/139138844-2e320207-e3ad-494b-863b-b264fa5c3ae3.png)

And here is some results for our approximation for Approximate. 
[TODO IMAGE]

---
### Performance

Performance-wise this seems like a slight win over LTC for Marschner model and a pretty significant win for Kajiya. Additionally, I measured the MRP method with and without the brute force solid angle computation and did find a measurable difference, but in both cases these still resulted in lower times than the LTC, so I think this is good justification to stick with the brute force solid angle route. 

Performance metrics were captured from a standalone Windows built with an NVIDIA Quadro RTX 8000, at a 3840x2160 resolution, 8x MSAA. 

| Model | Area Light Method  | Forward Opaque Time Per-Groom (ms) |
| -------------| ------------- | ------------- |
| Marschner (+Multiple Scattering) | MRP, Brute Force Solid Angle | 1.31 |
| Kajiya-Kay | MRP, Brute Force Solid Angle | 0.97  |
| Marschner (+Multiple Scattering) | MRP, Optimized Solid Angle | 1.27 |
| Kajiya-Kay | MRP, Optimized Solid Angle | 0.89 |
| Marschner (GGX) | LTC | 1.57 |
| Kajiya-Kay (GGX) | LTC | 1.43  |

_Test scenario scene. Left Kajiya, right Marschner._ 
![image](https://user-images.githubusercontent.com/28882975/139467949-2ebfe3a8-b4f4-477a-942e-00717e9fc4c6.png)

---
### Testing status

I manually verified the following behaviors:
- Varying area light shapes and orientations are in good agreement with the reference. 
- Cookie support.
- Barn door support. 
- Shadow support. 

Updated the hair area light graphics test to reflect the improved area light support, as well as added more coverage for the marschner model.  Local tests are passing + launched yamato.

![1401_HairGraph_Area_Light](https://user-images.githubusercontent.com/28882975/139143541-5ddec938-14a7-419e-adb5-cfde839c2e92.png)

---
### Comments to reviewers
I ended up finding a reasonable way to approximate Kajiya with this approach. It doesn't exactly use MRP, but instead just treats the area light as a normal analytic light and modulates the roughness automatically based on the solid angle. It required some tuning to make sure we are in good agreement with the reference.

2021-10-29 22:34 UTC, johnpars commented on com.unity.render-pipelines.high-definition/Runtime/Material/Hair/Hair.hlsl
> +            const float cookieMip = cookieMips - 2;
> the mip level should be sensitive to the solid angle. Larger solid angles indicate that the light is closer (relative to its size), so a smaller portion of its surface contributes to shading, and we should pick a larger mip.

I am getting good results with this mip selection approach:
`MipLevel = MipCount - (MipCount * SolidAngle / 2PI)`


For roughness, I tested the reference and it didn't seem worth it to take it into account. 

![SolidAngleMip](https://user-images.githubusercontent.com/28882975/139508253-7fb0ebfa-a1d2-4e21-9a28-bb66866db6d5.gif)

2021-11-01 13:38 UTC, kecho requested changes
Run yamato, and add a comment on the removal of that division by PI :) ensure yamato is green!

2021-11-01 13:38 UTC, kecho commented on com.unity.render-pipelines.high-definition/Runtime/Material/Hair/MultipleScattering/HairMultipleScattering.hlsl
> +    float3 fsBack = db * 2 * Ab * D_LongitudinalScatteringGaussian(thetaH - deltaB, sqrt(sigmaB + sigmaF)) / 1;
Could you ensure this doesn't change tests? i.e. do some yamato runs and update refs if needed.
Also I would add this comment in the code itself as  a comment! that is all :)

2021-11-02 03:04 UTC, johnpars commented
Re-running Yamato. All of these failures seem like instabilities (including the smoke test one, still persisting after I merged master). I also provided QA a test project to validate this PR.

2021-11-02 08:52 UTC, robertcupisz approved these changes

2021-11-02 12:09 UTC, kecho approved these changes

2021-11-02 15:44 UTC, johnpars commented
Looks like we are 'green' test-wise, the failures are known instabilities.

2021-11-04 08:51 UTC, sebastienlagarde commented on com.unity.render-pipelines.high-definition/Runtime/Material/Hair/Hair.hlsl
> +float3 RayPlaneIntersect(in float3 rayOrigin, in float3 rayDirection, in float3 planeOrigin, in float3 planeNormal)
Those set of function either alredy exist or should be moved into our geometry.hlsl common file

2021-11-04 09:16 UTC, sebastienlagarde commented on com.unity.render-pipelines.high-definition/Runtime/Material/Hair/Hair.hlsl
> +#if 0
We can't afford both in the code for perf reasons anyway (vgpr). So totally fine with disabling LTC

2021-11-04 09:16 UTC, sebastienlagarde approved these changes

2021-11-04 09:18 UTC, merged

2021-11-04 09:19 UTC, sebastienlagarde commented
@QA: Merging to 22.1, the coverage by John is already great.

2021-11-05 10:10 UTC, JMargevics reviewed
Tested thoroughly this on Windows platforms and found no visual issues both with strands and hair cards. ✔👍