Backport of #6232: Edited the Depth Priming MVP docs.
Unity-Technologies/Graphics pull request #6233
Opened 2021-11-08 01:07 UTC by oleks-k

Backport of #6232: Edited the Depth Priming MVP docs.

2021-11-08 09:23 UTC, NicoLeyman requested changes
Duplicating my feedback from the master PR since I managed to comment on the wrong PR and with the wrong account:
"The performance improvement depends on the amount of overlapping pixels" should mention that this only applies to the opaque pass. Something like this:
"The performance improvement depends on the amount of overlapping pixels in the opaque pass"

2021-11-25 08:25 UTC, aleksandrasdzikia approved these changes

2021-11-25 13:27 UTC, oleks-k commented
> Duplicating my feedback from the master PR since I managed to comment on the wrong PR and with the wrong account: "The performance improvement depends on the amount of overlapping pixels" should mention that this only applies to the opaque pass. Something like this: "The performance improvement depends on the amount of overlapping pixels in the opaque pass"

Thanks, this is done.

2021-11-26 08:54 UTC, NicoLeyman approved these changes

2021-11-29 13:43 UTC, merged