Update 2DRendererData_overview.md
Unity-Technologies/Graphics pull request #6272
Opened 2021-11-11 05:42 UTC by unity-cchu

### Checklist for PR maker
- [ ] Have you added a backport label (if needed)? For example, the `need-backport-*` label. After you backport the PR, the label changes to `backported-*`.
---
### Purpose of this PR
This adds additional documentation about how to use the _CameraSortingLayerTexture shader variable

2021-11-11 06:21 UTC, Sam-Unity requested changes
Suggest combining previous sentence with new line.

2021-11-11 06:21 UTC, Sam-Unity commented on com.unity.render-pipelines.universal/Documentation~/2DRendererData_overview.md
> +The __2D Renderer Data__ specifies how Unity supplies the shader variable `CameraSortingLayerTexture` for use in custom shaders. You must use this data in the same frame, and on the following layers.
It is recommended that you use this data in the same frame and on the following layers, as using `CameraSortingLayerTexture` before it has been captured may result in unexpected results.

2021-11-18 14:38 UTC, phi-lira approved these changes

2021-12-09 09:10 UTC, Sam-Unity approved these changes
Approving previous edits and final edit.

2021-12-09 09:44 UTC, merged

2022-01-28 12:11 UTC, unity-cchu commented
Backport 2021.2: https://github.com/Unity-Technologies/Graphics/pull/6887