Fix light flare for pbr sky
Unity-Technologies/Graphics pull request #6278
Opened 2021-11-15 11:43 UTC by adrien-de-tocqueville

### Purpose of this PR

fix for https://fogbugz.unity3d.com/f/cases/1379487/

First, slight change to fix from https://github.com/Unity-Technologies/Graphics/pull/6145, it was not handling correclty the case with multiple dircetional lights. Moved the precomputed data to the directional light data struct

Second, updated the template light to have a white flare tint. For some reason it was changed to black, causing the flare to be invisible

---
### Testing status

Tested to change flare size with multiple directinal lights on the pbr sky

---
### Comments to reviewers

The second fix mentionned above is a bit strange, @Unity-Technologies/gfx-qa-hdrp maybe you could investigate a bit to find why the flare color became black in the template, there may be a regression or an update issue ?

2021-11-15 12:41 UTC, FrancescoC-unity approved these changes

2021-11-16 12:35 UTC, iM0ve requested changes
**Testing Status:** In progress

2021-11-16 14:56 UTC, adrien-de-tocqueville commented
You are right, it doesn't have any effect, because there is no flare and the sky is hdri anyway, but in case a user want to try out flare with pbr sky, it is more straightforward this way

I asked pierre and it was an unwanted change so i'll revert to the default flare color which is white

2021-11-17 07:50 UTC, iM0ve approved these changes
All concerns/issues were addressed. Good to go

2021-11-24 18:35 UTC, sebastienlagarde approved these changes

2021-11-25 13:28 UTC, merged