Fixed inconsistent behavior in the volume debug when adding/remoing cameras.
Unity-Technologies/Graphics pull request #6298
Opened 2021-11-16 10:28 UTC by JulienIgnace-Unity

### Purpose of this PR
Fixed inconsistent behavior in the volume debug when adding/remoing cameras.
This was caused by interal indices for the camera enum in the debug panel not being up to date when adding/removing cameras. We now recreate the panel when adding/removing cameras to avoid this issue.

Fixes this issue: https://fogbugz.unity3d.com/f/cases/1379202/

---
### Testing status
Tested with the case repro.
Also tested that deleting the currently selected camera behaved correctly.

2021-11-16 18:26 UTC, alex-vazquez approved these changes
Looks good to me

2021-11-17 11:45 UTC, TomasKiniulis requested changes
~The error does not occur anymore, but there's two other similar issues left.~
~- The Camera dropdown does not get updated unless Camera is set to "None"~
- Removing currently selected Camera or selecting Camera that does not exist anymore throws the following: `IndexOutOfRangeException: Index was outside the bounds of the array.
UnityEditor.Rendering.DebugUIDrawerEnumField.OnGUI (UnityEngine.Rendering.DebugUI+Widget widget, UnityEditor.Rendering.DebugState state) (at C:/GitHub/Graphics2/Graphics/com.unity.render-pipelines.core/Editor/Debugging/DebugUIDrawer.Builtins.cs:331)
UnityEditor.Rendering.DebugWindow.OnWidgetGUI (UnityEngine.Rendering.DebugUI+Widget widget) (at C:/GitHub/Graphics2/Graphics/com.unity.render-pipelines.core/Editor/Debugging/DebugWindow.cs:516)
UnityEditor.Rendering.DebugWindow.TraverseContainerGUI (UnityEngine.Rendering.DebugUI+IContainer container) (at C:/GitHub/Graphics2/Graphics/com.unity.render-pipelines.core/Editor/Debugging/DebugWindow.cs:536)
UnityEditor.Rendering.DebugWindow.OnGUI () (at C:/GitHub/Graphics2/Graphics/com.unity.render-pipelines.core/Editor/Debugging/DebugWindow.cs:455)
UnityEditor.HostView.InvokeOnGUI (UnityEngine.Rect onGUIPosition) (at <f1711974e43141fb9eefce8d2ce06263>:0)`

https://user-images.githubusercontent.com/50582134/142194628-bee77a19-4e01-4b1d-993c-404ebf849142.mp4

2021-11-17 11:49 UTC, TomasKiniulis approved these changes
Agh I just realized I was on the wrong branch. Checking adding removing or changing cameras does work correctly

2021-11-25 14:59 UTC, sebastienlagarde approved these changes

2021-11-25 17:31 UTC, JulienIgnace-Unity commented
This PR will be redone by @alex-vazquez in a proper way compatible with the new code.

2021-11-25 17:31 UTC, closed without merging