[Universal][converter] batch mode support
Unity-Technologies/Graphics pull request #6341
Opened 2021-11-19 10:20 UTC by martint-unity

---
### Purpose of this PR
We need to add batch mode support for our converters. So that our users can run Unity in Batch Mode and still call the converters.

---
### Testing status
Can be tested by creating a script like this
public class TEST_BATCH_MODE : MonoBehaviour
{
    // Start is called before the first frame update
    void Start()
    {
       ConverterUtils.RunInBatchMode( "UnityEditor.Rendering.Universal.Converters.BuiltInToURPConverterContainer",
            new List<string>{"UnityEditor.Rendering.Universal.UniversalRenderPipelineMaterialUpgrader"},
            ConverterUtils.ConverterFilter.Inclusive);
    }
}

2021-11-19 10:22 UTC, pbbastian commented on com.unity.render-pipelines.universal/Editor/Converter/ConverterUtils.cs
> +    public class ConverterUtils
This should be `static`
```suggestion
    public static class ConverterUtils
```

2021-12-01 11:23 UTC, Nzollner approved these changes
LGTM

2021-12-02 12:56 UTC, BoonKiangTan commented
2D functionality verified on branch:

2022.1.0b1.2464
Revision: trunk 4897ee769494
Built: Sat, 27 Nov 2021 21:58:31 GMT
Package branch: universal/converter/batch-mode-support (c0ba4e6)

- Verified converter API for 2D URP upgrading work as intended
![devenv_3B6hl7j3cd](https://user-images.githubusercontent.com/54299249/144425083-5ee687e2-9ae9-4fbe-a711-1d3a1ff13cfb.png)
 - Ran Unity in batchmode with converter API, verified same behaviour as regular Render Pipeline Converter upgrade path
 ![cmd_PPVVqsOtAi](https://user-images.githubusercontent.com/54299249/144425130-17474956-a375-4401-8e9b-d1033dcaa0ff.png)
 - Verified regular sprites, tilemaps, sprite shapes and rigged characters have no visual difference after upgrade
Regular Render Pipeline Converter upgrade path:
![Unity_FyrV7DB6GI](https://user-images.githubusercontent.com/54299249/144425360-6ff0e482-9ad8-49f3-a837-d06dea16dc89.png)
Batchmode Converter API upgrade path:
![Unity_ypi8iNMWNY](https://user-images.githubusercontent.com/54299249/144425441-eb154a3e-22df-4b80-9335-d1d66b8eed7c.png)

Note: Script has to be in "Editor" folder and executed method has to be defined as static

2021-12-02 12:57 UTC, BoonKiangTan approved these changes

2021-12-03 08:57 UTC, pbbastian commented on com.unity.render-pipelines.universal/Editor/Converter/Converters.cs
> +    /// Used for Converting in Batch Mode.
This doesn't actually describe the enum. For referring to the batch mode, use `<seealso>` tag to refer to the actual function.
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/recommended-tags#seealso

2021-12-03 09:04 UTC, pbbastian commented on com.unity.render-pipelines.universal/Editor/Converter/Converters.cs
> +            Debug.Log($"Batch Mode:\nContainer named: {containerName}");
```suggestion
            Debug.Log($"Converter Batch Mode: {containerName}");
```

2021-12-03 09:05 UTC, pbbastian commented on com.unity.render-pipelines.universal/Editor/Converter/Converters.cs
> +        /// The method that will be run when converting assets in batch mode.
This reads kinds of weird. Isn't this a method that the user themselves would be calling?

2021-12-03 09:07 UTC, pbbastian commented on com.unity.render-pipelines.universal/Editor/Converter/Converters.cs
> +            List<Type> converterTypes = new List<Type>();
Reduce reallocations by reserving enough space initially for the maximum amount of items that will end up in the List.
```suggestion
            List<Type> converterTypes = new List<Type>(converterList.Count);
```

2021-12-03 09:16 UTC, pbbastian requested changes
Mostly looks good, I have a few comments

2021-12-03 15:21 UTC, pbbastian commented on com.unity.render-pipelines.universal/Editor/Converter/Converters.cs
> +    /// Enum for filtering the list of converters in batch mode./>
No need to mention that it's an enum. Also you've got an accidental `/>` at the end

2021-12-03 15:23 UTC, pbbastian commented on com.unity.render-pipelines.universal/Editor/Converter/Converters.cs
> +    /// See also <seealso cref="Converters.RunInBatchMode(UnityEditor.Rendering.Universal.ConverterContainerId, List{UnityEditor.Rendering.Universal.ConverterId}, UnityEditor.Rendering.Universal.Conv
`<seealso>` goes after `</summary>`

2021-12-03 15:24 UTC, pbbastian requested changes
A few more changes :D

2021-12-06 11:45 UTC, pbbastian approved these changes

2021-12-08 06:42 UTC, kennytann approved these changes

2021-12-14 22:44 UTC, aleksandrasdzikia approved these changes

2022-01-24 13:49 UTC, phi-lira approved these changes

2022-01-24 13:51 UTC, merged