[HDRP][Path Tracing] Environment (sky) importance sampling
Unity-Technologies/Graphics pull request #6472
Opened 2021-12-03 11:41 UTC by eturquin

Added envionment importance sampling for the path tracer. When changing the global sky settings, CDF and marginal tables are computed (happens once), and the notion of a sky light has been added to the already existing local and distant lights.

Before:
Sky values would only be accessed by material rays that were not intersecting anything. If there were small, bright spots in the envmap, they would result in extremely noisy images.

Now:
Sky is importance-sampled, resulting in much better convergence rate when using environments with hot, bright spots (e.g. a sky with a sun). See examples below.

This has already been tested with all 3 kinds of skies (gradient, physical, HDRI) and with HDRI images from the dedicated HDRP pack.

To be tested further with as many sky settings as possible.

2021-12-03 11:42 UTC, eturquin commented
![without0](https://user-images.githubusercontent.com/16614161/144596900-b9e358ef-59f1-46f3-a3bf-e78a4c049a63.png)
![with0](https://user-images.githubusercontent.com/16614161/144596912-88ba14b7-919c-4838-a23f-d059667654b9.png)

2021-12-03 11:43 UTC, eturquin commented
![without1](https://user-images.githubusercontent.com/16614161/144597019-77ab2ae9-d956-4c82-8e55-95303079c49f.png)
![with1](https://user-images.githubusercontent.com/16614161/144597032-8ff4b7d7-5eab-466e-a322-7c21d862ce26.png)

2021-12-03 11:43 UTC, eturquin commented
![without2](https://user-images.githubusercontent.com/16614161/144597063-afe03cfd-bdc9-4921-ae54-cf50be05a07f.png)
![with2](https://user-images.githubusercontent.com/16614161/144597067-19a17fb0-0822-43bf-b036-5c09a71bf7df.png)

2021-12-03 11:45 UTC, eturquin commented
![without3](https://user-images.githubusercontent.com/16614161/144597249-373a1bac-3d87-4751-8120-69a0ea306b37.png)
![with3](https://user-images.githubusercontent.com/16614161/144597257-b7aeefd4-b3bf-4529-ab5e-76b419ca9311.png)

2021-12-03 18:19 UTC, eturquin commented
As expected, many of the path tracing tests (all on one sample) fail, simply based on the fact that there is an additional light to sample, which in many situations makes the result noisier. One option to alleviate this would be to only activate env importance sampling for HDRIs and maybe physical skies, but not for gradient skies.
Tests 1000 and 5005 results need to be investigated further.

2021-12-06 16:02 UTC, eturquin commented
Reference images on path tracing tests that use HDRIs (the default texture) have been updated, tests should now go through successfully.

2021-12-10 12:46 UTC, iM0ve submitted a review, later dismissed
**Test status:** Completed
The improvement to my test scene is substantial, however found a change that I believe might not be intended. Please verify.

**The improvement:**
My scene uses a Directional light and an HDRI sky which has multiple tube lights captured. The new importance sampling really shines here. Captures are of 256 samples

Before
![Before2](https://user-images.githubusercontent.com/36502659/145574688-896863fb-3ae5-4947-ace7-c8310161717a.png)

After
![After2](https://user-images.githubusercontent.com/36502659/145574718-01ee1e31-8868-439d-a0c3-1f34f92f610e.png)

**The concern:**
On the template however, where HDRI is continuous and does not contain any bright light sources, we see a loss of highlights (the material ball and the ceiling in the 2nd room). Also the picture is maybe a little more grainy.

 For light baking there is a dedicated checkbox to enable and disable importance sampling, maybe having it on all the time can cause negative effects? Captured with 1024 samples and other path tracer settings are default.

Before
![Before3](https://user-images.githubusercontent.com/36502659/145576151-f26e760f-2873-485e-ba86-d2a3ee38a65f.png)

After
![After3](https://user-images.githubusercontent.com/36502659/145576220-a73fa673-ecc3-4e18-837f-5650d3109307.png)


**Whats tested:**
* Path tracer on personal project
* Path tracer on template

2021-12-13 12:53 UTC, iM0ve requested changes
The last commit provided some improvements but also introduced some like unwanted effects.

The template now matches better, bloom is again visible. Some light is still lost (under the material ball and red wall in the back)

Before PR
![BeforeUpdated](https://user-images.githubusercontent.com/36502659/145814883-54363e26-332a-4551-b32c-037b18f1b66b.png)

After last commit
![Round2A3](https://user-images.githubusercontent.com/36502659/145814912-541108b3-e98f-405d-8f81-2c36eda2b615.png)

Here is the more concerning problem. I have changed the HDRI used in the template to [this](https://polyhaven.com/a/photo_studio_01). So it does not contain even lighting, more representing the target of this PR. With latest commit new streaks of light are visible, maybe the cause of selective clamping. **update - after investigation it seems expected result**

Before PR
![Before6](https://user-images.githubusercontent.com/36502659/145815900-65f8a342-7b3f-4bb0-b86d-a25400889961.png)



After last commit
![After6](https://user-images.githubusercontent.com/36502659/145815924-d84e2d3d-ff92-42d8-b65f-685de3d284be.png)

2021-12-13 16:59 UTC, eturquin commented
I added a Path Tracing parameter to control when sky importance sampling is performed. Documentation will be added to this PR if the current controls are deemed satisfactory.
On top of that, intensity clamping has been reverted to the Master branch behaviour, i.e. applied only on indirect lighting: let's see how it performs, and if needed we may revisit it.

2021-12-14 11:26 UTC, iM0ve approved these changes
Final round of tests. So the new commit added a new parameter Sky Importance Sampling, allowing to not only turn the feature on/off for HDRI, but also for other types of skies. In both cases there was a reduction in noise.I additionally tested:

* Importance sampling on Physically based sky. Used nasa provided star map but with super hight exposure so the stars could light up the scene.
* Importance sampling on Gradient sky
* Turning off the feature for all sky types
* Rechecked previous tests to see nothing broke
* Undo functionality

Physical sky importance sampling OFF
![ZEEWKTvoAs](https://user-images.githubusercontent.com/36502659/145989256-00897f29-6179-47be-92c1-eebf7f83125b.png)

Physical sky importance sampling ON
![8xeFoUftA5](https://user-images.githubusercontent.com/36502659/145989324-242c6e01-fc17-4de9-9294-6d5a32e6854a.png)

Gradient sky importance sampling OFF
![Unity_k84kiF1ltS](https://user-images.githubusercontent.com/36502659/145989565-70ea5908-49c6-458c-ad8a-16fa7201b331.png)

Gradient sky importance sampling ON
![Unity_Unk3N1LK19](https://user-images.githubusercontent.com/36502659/145989589-2063a4c8-27b2-4cca-aa0a-fdd49571060d.png)

2021-12-14 16:05 UTC, remi-chapelain approved these changes
Tested a few cases especially with Cloud layer / Volumetric Clouds since adding them to a PBSky or Gradient Sky adds clouds to the skybox directly resulting in high contrast areas.
 
The default HDRI Only is not perfect since there is some cases when we'd like to use importance sampling for uniform / gradient sky for example when there's no lights but the difference is not substantial enough to counteract the added noise when there's lights. 
So it's a good compromise. ✔️ 

Looks good to me :)

2021-12-14 17:37 UTC, sebastienlagarde commented on com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassPathTracing.hlsl
> +    pathIntersection.value = computeDirect ? surfaceData.color * GetInverseCurrentExposureMultiplier() + builtinData.emissiveColor : 0.0;
is it expected? surfaceData.color?

2021-12-14 17:38 UTC, eturquin commented on com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/ShaderPass/ShaderPassPathTracing.hlsl
> +    pathIntersection.value = computeDirect ? surfaceData.color * GetInverseCurrentExposureMultiplier() + builtinData.emissiveColor : 0.0;
Yes

2021-12-14 17:42 UTC, sebastienlagarde approved these changes

2021-12-14 17:44 UTC, merged