Fixed flipped UV for directional light cookie on PBR Sky
Unity-Technologies/Graphics pull request #6505
Opened 2021-12-07 10:15 UTC by adrien-de-tocqueville

### Purpose of this PR

fix https://fogbugz.unity3d.com/f/cases/1382656/
It doesn't look like this was a design choice, so i think it should be fixed

Once again, I am not sure what backport labels to put

---
### Testing status

tested the repro project, with various sun orientation
Now:
![image](https://user-images.githubusercontent.com/61282776/145010143-b51efd4e-5fcc-4517-8f70-69188dbf40cb.png)

2021-12-07 10:34 UTC, RemyUnity commented
Maybe some notes should be added to the upgrade guide about this, as it will alter the rendering of scenes that were using directional light cookies.

2021-12-07 10:40 UTC, iM0ve requested changes
Indeed, please include a short note in the docs section. Other than that good addition.
Upgrade guides example: https://docs.unity3d.com/Packages/com.unity.render-pipelines.high-definition@13.1/manual/Upgrading-from-2021.1-to-2021.2.html

2021-12-07 15:40 UTC, adrien-de-tocqueville commented
waiting on #6516 to add the upgrade guide

2021-12-08 14:41 UTC, sebastienlagarde approved these changes

2021-12-08 14:42 UTC, sebastienlagarde commented
no backport for this one

2021-12-08 15:09 UTC, iM0ve approved these changes
I would write it like this, but I am okay to whatever doc team suggests.

While Physically Based Sky is used, Directional lights can have a surface texture, located in Celestial Body section. The orientation of the texture was incorrect, in HDRP 14 it was fixed by flipping UVs on the x axis. When upgrading a project, suns texture might need to be flipped.

So its clear that it only matters for PB sky from the start of the sentence, at the end what the user is expected to do.

2021-12-08 15:18 UTC, adrien-de-tocqueville commented
yeah it's better, it will be a better starting point for doc, thanks

2021-12-09 18:51 UTC, sebastienlagarde commented
need to solve conflict

2021-12-09 18:51 UTC, sebastienlagarde commented
have you trigger yamato?

2021-12-13 15:22 UTC, merged