[RPW]Strip Subshaders that are not from the current pipeline
Unity-Technologies/Graphics pull request #6780
Opened 2022-01-20 09:58 UTC by alex-vazquez

### Purpose of this PR
On each shader stripper, when we know that the Asset is from the correct pipeline, we are able to check the `RenderPipeline` tag, and make sure that it maps with the one defined on the pipeline.

If the tag is not null, but it is different from the current pipeline, it will strip all it's variants.

---
### Testing status
- Checking a cross pipeline project, that when building for HDRP, all URP shaders are stripped
- Checking with a shadergraph targetting HDRP and URP, when building for HDRP, URP Shaders are stripped.

---
### Comments to reviewers
This PR was originaly created on: [trunk](https://github.cds.internal.unity3d.com/unity/unity/pull/5947), but I've decided to create it on the package side, as we have more control over the current asset, and we have logging + export information.

2022-01-20 10:24 UTC, aleks01010101 approved these changes
LGTM

2022-01-20 16:57 UTC, RSlysz requested changes
The new tag is logged in HDRP but not in Universal. We should have parity if possible to debug more easily.

Also, there is the URP FallbackError shader that got the tag in this PR. What about other shaders? Is it the only one missing a Tag?

2022-01-20 16:57 UTC, RSlysz commented on com.unity.render-pipelines.core/CHANGELOG.md
> +- Method to obtain the `RenderPipeline` tag from a shader given a `ShaderSnippetData`.
```suggestion
- Add method to obtain the `RenderPipeline` tag from a shader given a `ShaderSnippetData`.
```

2022-01-21 08:58 UTC, RSlysz commented on com.unity.render-pipelines.core/Editor/BuildProcessors/ShaderExtensions.cs
> +        public static bool TryGetRenderPipelineTag([NotNull] this Shader shader, ShaderSnippetData snippetData,  out string renderPipelineTag)
```suggestion
        public static bool TryGetRenderPipelineTag([DisallowNull] this Shader shader, ShaderSnippetData snippetData,  out string renderPipelineTag)
```

2022-01-25 09:03 UTC, RSlysz approved these changes

2022-01-25 09:04 UTC, RSlysz reviewed
It is possible to have an automated test on this? Regression would be hard to discover

2022-02-01 10:48 UTC, RSlysz requested changes
Minor potential improvement.
The test part should be improved.

2022-02-01 10:48 UTC, RSlysz commented on com.unity.render-pipelines.high-definition/Editor/BuildProcessors/HDRPPreprocessShaders.cs
> +                shaderStripingWatch.Start();
[Optional] If this start to be used elsewhere too, think about making a MesuringScope

2022-02-01 10:48 UTC, RSlysz commented on com.unity.render-pipelines.high-definition/Tests/Editor/BuildProcessors/HDRPPreprocessShaderTests.cs
> +                }
Why a Try-Catch discarding all error? If there is an error we will have wrong initialization without knowing it

2022-02-01 10:48 UTC, RSlysz commented on com.unity.render-pipelines.high-definition/Tests/Editor/BuildProcessors/HDRPPreprocessShaderTests.cs
> +        public void InitializeBuildPreprocessors()
I am not sure to understand what is set up here. Can you clarify (by comments if needed)

2022-02-01 10:48 UTC, RSlysz commented on com.unity.render-pipelines.high-definition/Tests/Editor/BuildProcessors/HDRPPreprocessShaderTests.cs
> +    public class HDRPPreprocessShadersTests
There is a stripping case (StripHDRPShader_WhenHDRPisNotCurrentPipeline).
For completeness, a non stripping case would be nice: DontStripHDRPShader_WhenHDRPisCurrentPipeline

2022-02-01 10:48 UTC, RSlysz commented on com.unity.render-pipelines.universal/Editor/ShaderPreprocessor.cs
> +        private bool IsShaderProcessed(Shader shader, ShaderSnippetData snippet)
```suggestion
        private bool IsURPCompatibleShader(Shader shader, ShaderSnippetData snippet)
```

2022-02-01 10:48 UTC, RSlysz commented on com.unity.render-pipelines.universal/Editor/ShaderPreprocessor.cs
> +                if (!IsShaderProcessed(shader, snippetData))
```suggestion
                if (!IsURPCompatibleShader(shader, snippetData))
```

2022-02-01 10:48 UTC, RSlysz commented on com.unity.render-pipelines.universal/Tests/Editor/BuildProcessors/PreprocessShaderTests.cs
> +    public class PreprocessShadersTests
sames concerns than the HDRP tests

2022-02-01 10:48 UTC, RSlysz commented on com.unity.render-pipelines.high-definition/Tests/Editor/BuildProcessors/HDRPPreprocessShaderTests.cs
> +        public void StripHDRPShader_WhenHDRPisNotCurrentPipeline()
RenderPipeline is a project global set up. You perhaps should check that you don't use HDRP

2022-02-01 10:48 UTC, RSlysz commented on com.unity.render-pipelines.high-definition/Editor/BuildProcessors/HDRPPreprocessShaders.cs
> +            // TODO: Grab correct configuration/quality asset.
don't forget this todo

2022-03-18 08:55 UTC, alex-vazquez commented
Moved to trunk

2022-03-18 08:55 UTC, closed without merging