Make gate fit Vertical by default
Unity-Technologies/Graphics pull request #6830
Opened 2022-01-25 12:31 UTC by FrancescoC-unity

Fix for https://fogbugz.unity3d.com/f/cases/1387267/ 

As per discussion that happened prior to the bug report, changing the default so now there is no visual pop
Unfortunately to change it we need to move the parameter to HDRP, to avoid changing the behaviour for all of Unity. 

https://user-images.githubusercontent.com/43168857/150977442-c1c4ed18-be66-427d-9530-760710344997.mov

**What did I test** check the video + verified that changes happen as requested by the option.

2022-01-25 13:29 UTC, pmavridis approved these changes
Looks god to me regarding the editor workflow. Scripting behavior will be the same as before, which I think is the best choice at this point.

2022-01-25 15:43 UTC, FrancescoC-unity commented
Messed up changelog :P Will fix up as soon as I can switch branches.

2022-01-25 15:47 UTC, remi-chapelain requested changes
Fix seems right and straightforward. 

Double checked that everything was serialized and saved properly. 

Rejecting because there seems to be a changelog issue for now :)

2022-01-25 16:53 UTC, remi-chapelain approved these changes

2022-02-02 11:26 UTC, sebastienlagarde approved these changes

2022-02-02 11:26 UTC, merged