[HDRP] Update custom pass doc (decals not supported by DrawRenderers custom pass)
Unity-Technologies/Graphics pull request #6858
Opened 2022-01-26 14:50 UTC by alelievr

### Purpose of this PR
Add a note in the custom pass DrawRenderers doc to notify users that decals are not supported on objects rendered by custom passes.

2022-01-26 15:11 UTC, sebastienlagarde approved these changes

2022-01-31 11:20 UTC, Vic-Cooper requested changes

2022-01-31 12:46 UTC, Vic-Cooper approved these changes
Great, thanks :)(

2022-01-31 16:34 UTC, sebastienlagarde approved these changes

2022-01-31 16:34 UTC, merged