VFX Graph gizmo disappear when trying to select it in the scene
Unity-Technologies/Graphics pull request #6864
Opened 2022-01-26 16:53 UTC by julienamsellem

### Purpose of this PR
https://fogbugz.unity3d.com/f/cases/1398351/

This is a regression introduced by this [PR](https://github.com/Unity-Technologies/Graphics/pull/6664).
As soon as the VFX Graph window loses focus the block is unselected and then the gizmo is removed from the scene.

![Unity_GeYumhkSBG](https://user-images.githubusercontent.com/85612173/151208449-97800295-ad75-4d61-b1ed-0eb89499a30e.gif)

---

### Testing status
Tested the original issues about selection from this [PR](https://github.com/Unity-Technologies/Graphics/pull/6664)
Tested operators and blocks gizmos.

2022-01-27 10:45 UTC, MarieGuff approved these changes
No T.A. work needed on this PR (bugfix only)

2022-01-27 11:25 UTC, PaulDemeulenaere commented on com.unity.visualeffectgraph/Editor/GraphView/Views/VFXPaste.cs
> +                var serializableGraph = JsonUtility.FromJson<SerializableGraph>(content);
The formatting is failing on this file 🤔
You can run it manually using:
```
perl $HOME\unity-meta\Tools\Format\format.pl --nobackups --hgroot $(pwd) .
```

2022-01-27 14:17 UTC, PaulDemeulenaere commented on com.unity.visualeffectgraph/Editor/GraphView/Views/VFXPaste.cs
> +                var serializableGraph = JsonUtility.FromJson<SerializableGraph>(content);
resolve at https://github.com/Unity-Technologies/Graphics/pull/6864/commits/a012ffe1d5208836a58fd819354c688f3c49ef00

2022-01-27 14:35 UTC, PaulDemeulenaere approved these changes
Reviewed the code (not tested)
- ```if (newValue != null)``` <= Only a safe null check 🟢 
- Noticed the change between OnLostFocus => UpdateGlobalSelection 🟢 (but can't know without testing)
- Unrelated safety check in `CanPaste` 🟢 : You can fill a fogbugz if you think it's approriate.

2022-01-27 14:39 UTC, julienamsellem commented
> * Unrelated safety check in `CanPaste` 🟢 : You can fill a fogbugz if you think it's approriate.
I just had an exception, nobody reported it, so I thought I could quickly fix it without add too much "administrative" work 🙄

2022-01-27 15:45 UTC, VitaVFX commented
Great and quick catch Julien! And also a great lesson for me 🙇🏻 

Tested:

❓**Connecting to Subgraphs Operators, then gizmos are not shown at all (I guess it is a known limitation according to provided warning message). Leaving for visibility**
![image](https://user-images.githubusercontent.com/66080609/151390741-4d0aa89c-95d5-471a-a3c0-56c6be0f4dbf.png)
![image](https://user-images.githubusercontent.com/66080609/151390769-79ddbcca-da44-4020-9c6a-d4d182f56e62.png)
![image](https://user-images.githubusercontent.com/66080609/151390837-79b7d567-4b67-4299-82c4-e25327f47429.png)

✔️Gizmos of the property 
![Unity_hpowvoqUo2](https://user-images.githubusercontent.com/66080609/151392490-1f892a2e-2c7a-4e8b-ab5e-aa34160ef9d4.gif)

✔️Copy pasting/duplicating/deleting blocks

✔️ Blackboard properties gizmos are editable in Scene View

✔️**Gizmos between multi windows**
![Unity_ShGnvrTHKu](https://user-images.githubusercontent.com/66080609/151389585-f6f6802c-5606-4ee7-801e-96ba56342594.gif)

✔️**Single-multi gizmos selection**
![Unity_DqpuY01Yoq](https://user-images.githubusercontent.com/66080609/151389661-cf0177f8-b7ea-490a-b592-e1124ce6976c.gif)

✔️**Bounds recording, auto, manual settings**
![Unity_9WFyylQD0t](https://user-images.githubusercontent.com/66080609/151389703-db91718e-6a11-4fd0-958a-24f3fd58fb94.gif)

✔️**Show Bounds in Visual Effect Panel in the Scene View**
![Unity_IA9Q5kn37X](https://user-images.githubusercontent.com/66080609/151390293-1509bc95-8989-42de-955f-f2ceed296b74.gif)

2022-01-27 15:45 UTC, VitaVFX approved these changes

2022-01-27 15:49 UTC, julienamsellem commented
Thanks for the big test coverage 👍

2022-01-27 16:31 UTC, VitaVFX commented
Cross-Posting for visibility. Several concerns based on suggestion.

1. Selecting empty space, brings us to the currently active VFX folder
2. Selecting empty space also focuses VFX asset not only shows it in the Inspector

highlighting the asset when clicking the empty space is very confusing. Is there a way only display asset's inspector without selecting the asset itself?

![Unity_U8OYEEytON](https://user-images.githubusercontent.com/66080609/151399253-b7be2da4-6195-4f92-a6d5-efda3fa3135a.gif)
![Unity_Qwpk5x6mL1](https://user-images.githubusercontent.com/66080609/151399260-3254baca-ae4c-46de-9bd1-74d839ebc3fe.gif)
n

2022-01-28 16:32 UTC, julienamsellem commented
Thanks for catching this annoying UX behavior. Sadly there's no way to select the asset in the inspector and avoid the project browser from navigating to the asset. So now when clicking in the void in the VFX Graph the inspector is emptied if a vfx object was previously selected.

2022-02-03 09:16 UTC, VitaVFX commented
<h3> Concerns: </h3>

1. We are no longer brought to the selection of VFX in Project Browser (yay!), but the fix also introduces one off inconsistency. So within this feature we also get a few concerns: 

- One off inconsistency among other windows
- Possible user confusion (might get some bug reports in the future regarding this). 

We probably want to weight what is impact of this implementation.

**[Observe Project's Browser Lock in gif]**
![Unity_tS2cH5oUgL](https://user-images.githubusercontent.com/66080609/152308981-a63edfb8-7ecb-42a9-bb05-99b786068327.gif)

2. Observation/Question. Is clicking into the 'void' supposed to shows Inspector only after when deselecting node/context/block? What about if I select something in Project Browser and then selecting 'void' in VFX Graph (without selecting any block/node/context)?
![Unity_PySAjAbwfA](https://user-images.githubusercontent.com/66080609/152312791-c9ce5cc5-4672-410d-9641-8f7cb1fc9699.gif)

<h3>Passed Tests: </h3>

1. Selecting nodes/blocks/contexts display their information; selecting edges ports, shows info of previous selection
2. When opening external windows and clicking in the void of external asset does not bring us to VFX Asset window (that's goodie!)
3. Locking Inspector works fine. When Clicking blocks/nodes/contexts and locking Inspector their information is kept and vice versa
4. Right-clicking in the void shows information of previous selection
5. Quickly checked if gizmos can still be edited in Scene View by checking Arc Cone's and Bounds gizmos
6. Checked selection multi windows. If selection from contexts/node/block to the void brings any other heavier unwanted behavior.

2022-02-03 09:26 UTC, julienamsellem commented
Thanks @VitaVFX for this new round of testing.
About the concerns you raised, here are my answers:
1/ The "lock" icon blink is the price to pay if we want to keep that behavior (unless someone knows a different way)
2/ If you have something selected in the project browser that is then also selected in the inspector, then clicking in the void of the VFX Graph won't discard this selection. That behavior is done on purpose and can be changed if it makes no sense.

2022-02-03 09:32 UTC, VitaVFX commented
1/ Yes, I hear you and it is understandable. The problem is whether we want/can to pay this price. It would good to reach out to UX people and ask about this one off thingie. (I wish we could do this in a invisible way)

2/ Gotcha!

2022-02-08 09:56 UTC, julienamsellem commented
FYI I found this bug report which was about the question we have about selecting the asset and the project browser changing directory https://fogbugz.unity3d.com/f/cases/1364098/

2022-02-11 11:46 UTC, VitaVFX approved these changes
[#vfx-ux conversation](https://unity.slack.com/archives/C02KRFTMN9W/p1644253336109809)

A sum up of the discussion for other reviewers:

1. This change is temporary, feature will adopt full intentional behavior within transition to GTF.
2. This feature has closest implementation to what GTF offers.
3. UX concerns:
             - Asset selection is associated to clicking into the void space. This change affects other areas.
             - Lock highlight most likely will be unnoticed, but if it will users most likely think that it is a bug.

Test results are above.

2022-02-17 16:52 UTC, PaulDemeulenaere approved these changes
Beside the (maybe) unexpected [using](https://github.com/Unity-Technologies/Graphics/pull/6864#discussion_r809255713) looks good to me.
Be sure it doesn't introduce a new failure in this [job](https://unity-ci.cds.internal.unity3d.com/job/11725955)

2022-02-17 17:22 UTC, MarieGuff commented
**Found issues:** tested on 22.2.0a6.935

- **ABSOLUTE BLOCKER**: VFX's scene view control panel not available, probably replaced by gizo panel? 

![VFX_Bug_GizmoPanel](https://user-images.githubusercontent.com/71330456/154535573-18ee28c0-26df-4757-b21e-5192fdf12fc1.gif)

- Gizmo error for non relevant items isn't necessary (ex: output selection, lifetime note selection...) they are also all displayed for a multiple selection

![image](https://user-images.githubusercontent.com/71330456/154535990-cf3bc988-364a-4289-aaca-4efa032dcdd3.png)

- Velocity gizmo not aligned with the arrow (probably unrelated to PR) 

(Expected: the orientation gizmo follows the arrow's direction)
![VFX_Bug_VelocityGizmo](https://user-images.githubusercontent.com/71330456/154534842-45f16651-d342-4c5b-b8ad-10268b6f20c3.gif)

2022-02-17 17:23 UTC, MarieGuff requested changes
Bugs found, to be checked.

2022-02-17 20:17 UTC, julienamsellem commented on com.unity.visualeffectgraph/Editor/GraphView/Views/VFXView.cs
> +using System.ComponentModel.DataAnnotations;
Not required, thank!

2022-03-03 06:14 UTC, VitaVFX commented
Verified raised issues and ran additional Test Rail pass to ensure UI functionality works as expected. [Test Doc](https://docs.google.com/document/d/1cY2U5A5k_qPKjQYp_Vi5cqHYQtpcf_fpAjRnUmmk_UI/edit#)

2022-03-03 06:16 UTC, VitaVFX commented
@MarieGuff Would you confirm if fixes are suitable? Is there anything else concerning on TA's behalf?

2022-03-03 08:54 UTC, MarieGuff commented
I still have the nodes that don't have a gizmo showing in the gizmo overlay with an error, can we change that @julienamsellem ? (ex: lifetime node don't have a gizmo so should not throw a "gizmo value is indeterminate" alert, same for color, size, orient... etc)

2022-03-03 08:56 UTC, julienamsellem commented
> I still have the nodes that don't have a gizmo showing in the gizmo overlay with an error, can we change that @julienamsellem ? (ex: lifetime node don't have a gizmo so should not throw a "gizmo value is indeterminate" alert, same for color, size, orient... etc)

IIRC this should be addressed by a PR from @PaulDemeulenaere. Let's see with him when he is back :)

2022-03-03 08:57 UTC, MarieGuff commented
Also It seems like I have to double click in the "void" to be able to create a new node with space bar, only one click should be enough

2022-03-03 08:59 UTC, julienamsellem commented
> Also It seems like I have to double click in the "void" to be able to create a new node with space bar, only one click should be enough

This one must be addressed in this PR. I'm on it.

2022-03-03 09:53 UTC, MarieGuff approved these changes
Issues fixed thanks Julien!
TBD once Paul is back: Gizmo errors for non relevant nodes

2022-03-03 10:27 UTC, julienamsellem commented
> Issues fixed thanks Julien! TBD once Paul is back: Gizmo errors for non relevant nodes

To be safe I also added auto-tests. They should catch any regression on focus when clearing the selection (click in the void for exemple)

2022-03-08 09:39 UTC, PaulDemeulenaere commented
> 

Indeed, in this PR : https://ono.unity3d.com/unity/unity/pull-request/140065/_/graphics/vfx/feature/add-space-passthrough
I replaced with another message "gizmoWarningNotAvailable" which indicates "There isn't any gizmo available."

2022-03-08 10:54 UTC, PaulDemeulenaere commented on com.unity.visualeffectgraph/Editor/Types/VFXCircleGizmos.cs
> +                        var result = Handles.Slider(gizmo.GetCombinedHashCode(s_RadiusDirectionsName[i]), sliderPos, dir, handleSize * HandleUtility.GetHandleSize(sliderPos), CustomCubeHandleCap, 0.0
You should check usage of `GUIUtility.hotControl` to verify if we aren't compareing `s_RadiusDirectionsName` & co somewhere else.

2022-03-08 14:52 UTC, julienamsellem commented on com.unity.visualeffectgraph/Editor/Gizmo/VFXGizmo.cs
> +        public int GetCombinedHashCode(int hashCode) => (currentHashCode + hashCode) % int.MaxValue;
Good point, I didn't know this method 👍

2022-03-08 14:54 UTC, julienamsellem commented on com.unity.visualeffectgraph/Editor/Types/VFXCircleGizmos.cs
> +                        var result = Handles.Slider(gizmo.GetCombinedHashCode(s_RadiusDirectionsName[i]), sliderPos, dir, handleSize * HandleUtility.GetHandleSize(sliderPos), CustomCubeHandleCap, 0.0
You were right, there was a small side effect on `hotControl` detection. It's fixed, but I think we should improve a bit later what we're doing with `hotControl`.

2022-07-04 15:16 UTC, closed without merging