[Fogbugz # 1398085] Fixing flicker when toggling hardware DRS
Unity-Technologies/Graphics pull request #6868
Opened 2022-01-27 00:26 UTC by kecho

### Purpose of this PR

Fogbugzes: 
* https://fogbugz.unity3d.com/f/cases/1398085/
* https://fogbugz.unity3d.com/f/cases/1398119/ 

This PR fixes a flicker when enabling/disabling DRS on a camera. This issue only occurs on hardware DRS platforms (dx12, vulkan and console).

Reason:
We were calling UpdateAndUseCamera, which triggered an update. Then after we were calling SetCurrentCameraRequest(). This artifically delayed the ScalableBufferManager sending the new resolution to the runtime.
The fix is quite simple, do all the configuration first, then do a final Update() to flush the settings gathered. 

---
### Testing status
* Tested same thing in these two fogbugz.
* Tested on dx12, selecting hardware drs, and flicking DRS button on the camera. Both on play mode and with editor / multiple game views (all DRS techniques including dlss).
* Hoping qa can test vulkan and test regression on software DRS

2022-01-27 11:37 UTC, remi-chapelain requested changes
Fixed for dx11 / dx12 ✔️ 

Found only one case where it's still an issue. 
- Vulkan renderer
- Only in hardware mode (works fine in software)
- In editor **AND** player
- happens only when a DRS filter is active when setting AllowDynamicResolution to false on the camera (works fine if DLSS is active)

https://user-images.githubusercontent.com/57442369/151351416-0288ec3e-1ded-4838-a3df-cdaba4242ab8.mp4

https://user-images.githubusercontent.com/57442369/151351391-546d81db-4a0f-4cff-8323-96d98a479c77.mp4

2022-01-27 17:08 UTC, kecho commented
> Fixed for dx11 / dx12 ✔️
> 
> Found only one case where it's still an issue.
> 
> * Vulkan renderer
> * Only in hardware mode (works fine in software)
> * In editor **AND** player
> * happens only when a DRS filter is active when setting AllowDynamicResolution to false on the camera (works fine if DLSS is active)
> 
>  DLSS.2022-01-27.12-29-57.mp4 
>  0a817e8a00fe163dc45d291e4d505088.mp4

Ok will investigate this. There is a chance this is a vulkan backend issue, but will definitely check this.

2022-01-27 22:05 UTC, kecho commented
> * AllowDynamicResolution

@remi-chapelain I tried this, I cannot reproduce this locally. Are you %100 sure you have the right branch? I tried with a vulkan renderer, hardware mode, dlss off. Works just fine on my side.

2022-01-28 09:23 UTC, remi-chapelain approved these changes
Sorry for wasting time here, it seems kleber is right because I can't repro anymore ! 
Approving the PR ✔️

2022-01-31 16:37 UTC, sebastienlagarde approved these changes

2022-01-31 16:39 UTC, FrancescoC-unity approved these changes

2022-01-31 16:40 UTC, merged