Fix Async_Compute with SSR build - 1395932
Unity-Technologies/Graphics pull request #6879
Opened 2022-01-27 12:42 UTC by skhiat

Fix when we use the -build- a version with SSR + Async Compute Shader:
![image](https://user-images.githubusercontent.com/55133890/151360477-d95d0257-c47c-48be-9e5d-8809fc17d8b1.png)

Discussion ref:
https://unity.slack.com/archives/CM6VCD9C7/p1616763855031800

This PR should fix this PR:
![image](https://user-images.githubusercontent.com/55133890/151360592-4bf1d386-6de7-4c9c-b508-0235b9d6fe07.png)

To the tester:
Could you validate that the issue is not here any more, I wasn't able to produce a proper build.

2022-01-28 11:16 UTC, TomasKiniulis reviewed
SSR errors are resolved, but Dx12 player build does not run yet. Not sure if related directly to SSR or should be solved with another PR.

The following errors remain:
```
Render Graph Execution error
UnityEngine.StackTraceUtility:ExtractStackTrace () (at C:/buildslave/unity/build/Runtime/Export/Scripting/StackTrace.cs:37)
...
```

```
IndexOutOfRangeException: Index was outside the bounds of the array.
  at UnityEngine.Rendering.DynamicArray`1[T].get_Item (System.Int32 index) [0x00026] in C:\GitHub\Graphics2\Graphics\com.unity.render-pipelines.core\Runtime\Common\DynamicArray.cs:258 
  at UnityEngine.Experimental.Rendering.RenderGraphModule.RenderGraph.UpdateResourceAllocationAndSynchronization () [0x00206] in C:\GitHub\Graphics2\Graphics\com.unity.render-pipelines.core\Runtime\RenderGraph\RenderGraph.cs:1148 
  at UnityEngine.Experimental.Rendering.RenderGraphModule.RenderGraph.CompileRenderGraph () [0x00047] in C:\GitHub\Graphics2\Graphics\com.unity.render-pipelines.core\Runtime\RenderGraph\RenderGraph.cs:1248 
...
```

2022-02-01 19:08 UTC, kecho commented
Is there any reason why we couldnt do 
1) one pass to just clear the textures
2) the async pass using the cleared  prepared textures?
I say this because there is a performance cost, significant, into clearing textures manually. In console the rule is .3ms for a 1080p target. If half res, .15 or .1 ms. 
In Async we would be introducing bandwidth cost, which is no bueno if we have also bandwidth in flight.

Now if you really want to push for a manual clear, we need to measure this at least in ps4. Lmk if you need help profiling this.

2022-02-08 07:21 UTC, tlaedre commented
> Is there any reason why we couldnt do
> 
> 1. one pass to just clear the textures
> 2. the async pass using the cleared  prepared textures?
>    I say this because there is a performance cost, significant, into clearing textures manually. In console the rule is .3ms for a 1080p target. If half res, .15 or .1 ms.
>    In Async we would be introducing bandwidth cost, which is no bueno if we have also bandwidth in flight.
> 
> Now if you really want to push for a manual clear, we need to measure this at least in ps4. Lmk if you need help profiling this.

Wouldn't this require dedicated resources instead of shared rendergraph resources to work @kecho ?

2022-02-16 15:01 UTC, kecho commented
> > Is there any reason why we couldnt do
> > 
> > 1. one pass to just clear the textures
> > 2. the async pass using the cleared  prepared textures?
> >    I say this because there is a performance cost, significant, into clearing textures manually. In console the rule is .3ms for a 1080p target. If half res, .15 or .1 ms.
> >    In Async we would be introducing bandwidth cost, which is no bueno if we have also bandwidth in flight.
> > 
> > Now if you really want to push for a manual clear, we need to measure this at least in ps4. Lmk if you need help profiling this.
> 
> Wouldn't this require dedicated resources instead of shared rendergraph resources to work @kecho ?

Hmm not following? it would still import the textures as required.

2022-02-16 15:28 UTC, kecho requested changes
Id say clean up those #if true and then it can be approved!

2022-02-16 15:28 UTC, kecho commented on com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.LightLoop.cs
> +#if true
I would remove this

2022-02-16 16:39 UTC, skhiat commented on com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.LightLoop.cs
> +#if true
Fixed, tmp code

2022-02-18 08:08 UTC, tlaedre commented
> > > Is there any reason why we couldnt do
> > > 
> > > 1. one pass to just clear the textures
> > > 2. the async pass using the cleared  prepared textures?
> > >    I say this because there is a performance cost, significant, into clearing textures manually. In console the rule is .3ms for a 1080p target. If half res, .15 or .1 ms.
> > >    In Async we would be introducing bandwidth cost, which is no bueno if we have also bandwidth in flight.
> > > 
> > > Now if you really want to push for a manual clear, we need to measure this at least in ps4. Lmk if you need help profiling this.
> > 
> > 
> > Wouldn't this require dedicated resources instead of shared rendergraph resources to work @kecho ?
> 
> Hmm not following? it would still import the textures as required.

But you can't actually _use_ those imported textures outside of the render func, that would defeat the whole purpose of the render graph.

2022-02-18 08:10 UTC, tlaedre commented on com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.LightLoop.cs
> +                    using (var builder = renderGraph.AddRenderPass<RenderSSRPassData>("Clear SSR Buffers", out var passData))
Shouldn't this pass also run async compute?

2022-02-23 08:24 UTC, TomasKiniulis requested changes
>SSR errors are resolved, but Dx12 player build does not run correctly yet. Not sure if related directly to SSR or should be solved with another PR.
 The following errors remain:
Render Graph Execution error
UnityEngine.StackTraceUtility:ExtractStackTrace () (at C:/buildslave/unity/build/Runtime/Export/Scripting/StackTrace.cs:37)
...
IndexOutOfRangeException: Index was outside the bounds of the array.
  at UnityEngine.Rendering.DynamicArray`1[T].get_Item (System.Int32 index) [0x00026] in C:\GitHub\Graphics2\Graphics\com.unity.render-pipelines.core\Runtime\Common\DynamicArray.cs:258 
  at UnityEngine.Experimental.Rendering.RenderGraphModule.RenderGraph.UpdateResourceAllocationAndSynchronization () [0x00206] in C:\GitHub\Graphics2\Graphics\com.unity.render-pipelines.core\Runtime\RenderGraph\RenderGraph.cs:1148 
  at UnityEngine.Experimental.Rendering.RenderGraphModule.RenderGraph.CompileRenderGraph () [0x00047] in C:\GitHub\Graphics2\Graphics\com.unity.render-pipelines.core\Runtime\RenderGraph\RenderGraph.cs:1248 
...

Still hitting the same rendergraph issue.

2022-03-07 03:03 UTC, skhiat commented on com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.LightLoop.cs
> +                                }
data.ssrAccum & data.ssrAccumPrev are different texture

2022-04-22 12:48 UTC, sebastienlagarde commented
replicate here: https://github.cds.internal.unity3d.com/unity/unity/pull/8592

2022-04-22 12:48 UTC, closed without merging