list formatting
Unity-Technologies/Graphics pull request #6934
Opened 2022-02-01 14:52 UTC by emilybrown1

Part of a quality review of HDRP docs.

Fixed the numbered list formatting.

2022-02-03 13:57 UTC, Vic-Cooper requested changes
Some suggestions here - menu paths need clarification.

2022-02-03 13:57 UTC, Vic-Cooper commented on com.unity.render-pipelines.high-definition/Documentation~/Ray-Traced-Global-Illumination.md
> +2. In the Frame Settings for your Cameras, enable **Ray Tracing**.
Consider: Does the user have enough information here to change this setting?

Try it yourself in Unity and see.

2022-02-03 13:57 UTC, Vic-Cooper commented on com.unity.render-pipelines.high-definition/Documentation~/Ray-Traced-Global-Illumination.md
> +3. Select the [Screen Space Global Illumination](Override-Screen-Space-GI.md) override.
Select it where? :) 

Kick up an HDRP project and investigate.

2022-02-04 16:42 UTC, sebastienlagarde approved these changes

2022-02-04 16:43 UTC, merged