note formatting and captions
Unity-Technologies/Graphics pull request #6973
Opened 2022-02-03 10:53 UTC by emilybrown1

Part of a quality review of HDRP docs.

Fixed note formatting and moved image captions.

2022-02-03 14:46 UTC, Vic-Cooper requested changes
small notes.

2022-02-03 14:46 UTC, Vic-Cooper commented on com.unity.render-pipelines.high-definition/Documentation~/Post-Processing-Main.md
> +**Note**: HDRP already enables some post-processing effects in the [HDRP Global Settings](Default-Settings-Window.md), go to Section **Volume Profiles**.
If you mean the Volume profile section in this doc, link to it. 
To do that, use a header link and then a md link with the format [Header title](#header-title).
(I can find an example of a header link if you need one.)

2022-02-03 14:46 UTC, Vic-Cooper commented on com.unity.render-pipelines.high-definition/Documentation~/Post-Processing-Main.md
> +**Note**: HDRP already enables some post-processing effects in the [HDRP Global Settings](Default-Settings-Window.md), go to Section **Volume Profiles**.
Also I'd change the phrasing here to say some things are enabled by default (I know it sounds like passive voice but checkboxes are the exception): 

"Some post-processing effects are enabled by default in the [HDRP Global Settings](Default-Settings-Window.md)..."

2022-02-03 15:02 UTC, Vic-Cooper requested changes
As discussed :) header link etc...

2022-02-04 16:51 UTC, sebastienlagarde approved these changes

2022-02-04 16:51 UTC, merged