Cloud layer improvements
Unity-Technologies/Graphics pull request #6993
Opened 2022-02-04 06:48 UTC by adrien-de-tocqueville

### Purpose of this PR

Based on #6828 but a bit smaller. Most notably, this version doesn't sample the ambient probe.

**Changes:**

- Sun light now always tint cloud color (previoulsy _lighting_ option was sun color + raymarching, now sun color is always on and option is renamed to _raymarching_)
- added _altitude_ option for sun atmospheric attenuation
- removed _exposure_ control (now that sun color is correct it shouldn't be needed)
- renamed _thickness_ to density
- renamed _distortion_ to _wind_ (more consistent with volumetric clouds)

**Lighting Screenshots:**

Open in new tab to view them better. All screenshots use the same number of steps

|   | High Sun | Low Sun |
| ------------- | ------------- | ------------- |
| Branch | ![image](https://user-images.githubusercontent.com/61282776/152484561-cb84d036-ddd9-46f0-a54d-9f3b43acc83e.png) | ![image](https://user-images.githubusercontent.com/61282776/152483180-c472b315-8c17-4c32-8e0a-bf2e8acc6667.png)
| HW | ![image](https://user-images.githubusercontent.com/61282776/152451012-56555923-74eb-400e-8114-4990e2c9acbb.png) | ![image](https://user-images.githubusercontent.com/61282776/152451031-47e07765-2ff9-40b2-b31a-8d5fc5311d1a.png)
| Branch 2 (see note below) | ![image](https://user-images.githubusercontent.com/61282776/152450840-889ab385-2287-49a4-bf5f-c7e4acba513a.png) | ![image](https://user-images.githubusercontent.com/61282776/152450848-e6f43e9b-0bb7-4f03-ab23-7fac7ea401b7.png)

NOTE 1: "Branch 2" is only the first commit on this branch, it doesn't include changes to the raymarching code and therefore it's what you would get on master but including the sun color improvements of this branch.
NOTE 2: i think the HW version looks slightly better than this branch but i'll start with that.

---
### Testing status

See screenshots above, tested with pierre
Updated graphic test
![5010_CloudLayer](https://user-images.githubusercontent.com/61282776/152484445-a2ebfe1a-7547-4d74-b718-4db2c4b85eba.png)

2022-02-07 13:27 UTC, pierre-unity requested changes
With raymarching:
![image](https://user-images.githubusercontent.com/39901544/152795491-4ca06291-1cd2-45d8-9ea5-ad44d3e515f8.png)

Without raymarching:
![image](https://user-images.githubusercontent.com/39901544/152795789-1ec01b74-4340-4eff-b825-434d8e0fa7a8.png)


It's working well so far in my testing. The consistency with the sun light and the volumetric clouds is great. The removal of the "Exposure" control requires the user to play with the "Opacity" instead when NOT using the raymarching. This is somewhat acceptable, as the results are very similar. Up for discussion, if we want to keep it or not.

One problem: we need to indent the checkboxes for the Wind orientation and speed:
![image](https://user-images.githubusercontent.com/39901544/152796378-e43451bd-ada6-481c-9c32-e92e8b1c0ceb.png)

2022-02-07 13:32 UTC, iM0ve requested changes
**Whats tested:**
* Upgrading project
* Using the new properties
* Changing sunlight temperature and filter
* PB sky and HDRI sky
* Mac

**Concerns:**
1) There is a notable improvement when facing the suns direction (first two images), but when looking at the opposite direction clouds now always look gray/rainy and flat. Visually it looks very different to pre-upgrade and not many properties to alter their appearance. Not sure if this is an expected side effect

Sun facing (before)
![Old2](https://user-images.githubusercontent.com/36502659/152796364-40446eac-d0b7-42a8-ad7e-9c1e8c6f8509.png)

Sun facing (after)
![New2](https://user-images.githubusercontent.com/36502659/152796404-614e0faf-5f9e-494b-9910-522049ad8321.png)

Here is the concern, when camera is not facing the sun.

Before
![Old NonBaked](https://user-images.githubusercontent.com/36502659/152797035-9de85bdf-8f24-405b-b536-42d978681431.png)

After
![New](https://user-images.githubusercontent.com/36502659/152797064-e0f238d3-5c89-464a-bb3f-1886af58270b.png)

2) Since exposure option is now removed. If lets say for performance reasons Raymarching cant be used for a project, the clouds get super bright and no way to reduce their intensity anymore.

![exposure](https://user-images.githubusercontent.com/36502659/152797539-202ef54c-393b-4aca-a53c-27b114b9041f.gif)

2022-02-08 11:37 UTC, iM0ve approved these changes
I updated my review. All of the concerns were addressed. Works great, here is a showcase.

![CloudLayer](https://user-images.githubusercontent.com/36502659/152979554-fd87969d-2474-40b1-9b79-5538445817af.gif)

2022-02-16 15:44 UTC, sebastienlagarde commented on com.unity.render-pipelines.high-definition/Runtime/Sky/CloudSystem/CloudLayer/CloudLayerRenderer.cs
> +                cloudLayer.layerA.scrollFactor += cloudLayer.layerA.scrollSpeed.GetValue(hdCamera) * dt * 0.277778f;
could you comment where this magic number is coming from ? .277778f;

2022-02-16 15:45 UTC, sebastienlagarde approved these changes
just a comment to add on the magic number

2022-02-16 17:51 UTC, merged