Add warning when enlighten is enabled on Probe Volumes
Unity-Technologies/Graphics pull request #7028
Opened 2022-02-07 16:34 UTC by FrancescoC-unity

Fix for : https://fogbugz.unity3d.com/f/cases/1398949/ 

![image](https://user-images.githubusercontent.com/43168857/152830751-b0e8fee7-e79e-48cc-8f74-7c21516da089.png)

2022-02-07 16:42 UTC, sebastienlagarde approved these changes

2022-02-07 18:08 UTC, adrien-de-tocqueville approved these changes

2022-02-08 07:48 UTC, TomasKiniulis requested changes
When Enlighten is used and render pipeline is not HDRP in Graphics settings it's the Enlighten warning message showing up over "Probe Volume is not a supported feature by this SRP" error message. Could the order be changed or both messages displayed simultaneously?

Same if in Graphics settings HDRP asset is assigned, but quality settings has Universal pipeline selected - Enlighten warning takes priority instead of "The probe volumes feature is not enabled or not available on current SRP" warning.

https://user-images.githubusercontent.com/50582134/152940284-4c4175da-4429-46c0-8286-b3078b23a120.mp4

2022-02-08 09:31 UTC, JulienIgnace-Unity approved these changes

2022-02-08 10:11 UTC, TomasKiniulis approved these changes
Looks good now, both messages show up in quality and graphics settings

2022-02-09 18:03 UTC, merged