structure overhaul
Unity-Technologies/Graphics pull request #7150
Opened 2022-02-15 16:09 UTC by emilybrown1

Part of a quality review of HDRP docs.

Updated screenshot and clarified all instructions.

2022-02-15 16:12 UTC, emilybrown1 commented
+ono

2022-02-16 16:26 UTC, Vic-Cooper requested changes
Good improvements! There's just one section that bothers me so let's fix this while we're here.

2022-02-16 16:26 UTC, Vic-Cooper commented on com.unity.render-pipelines.high-definition/Documentation~/Upgrading-To-HDRP.md
> +The automatic HDRP Material converter processes convert Built-in Standard and Unlit Materials to HDRP Lit and Unlit Materials respectively. The processes use an overlay function to blend the color ch
This sentence feels like it's got too many words: 

"The automatic HDRP Material converter processes convert..." very wibbly. 

Instead: 

"HDRP uses multiple processes to automatically convert Built-in Standard and Unlit Materials to HDRP Lit and Unlit Materials respectively."

2022-02-16 16:26 UTC, Vic-Cooper commented on com.unity.render-pipelines.high-definition/Documentation~/Upgrading-To-HDRP.md
> +The automatic HDRP Material converter processes convert Built-in Standard and Unlit Materials to HDRP Lit and Unlit Materials respectively. The processes use an overlay function to blend the color ch
Also "These processes..." instead of "The processes" is less ambiguous.

2022-02-16 16:26 UTC, Vic-Cooper commented on com.unity.render-pipelines.high-definition/Documentation~/Upgrading-To-HDRP.md
> +The automatic HDRP Material converter processes convert Built-in Standard and Unlit Materials to HDRP Lit and Unlit Materials respectively. The processes use an overlay function to blend the color ch
Remove the comma before "like Adobe Photoshop".

2022-02-16 16:26 UTC, Vic-Cooper commented on com.unity.render-pipelines.high-definition/Documentation~/Upgrading-To-HDRP.md
> +The automatic HDRP Material converter processes convert Built-in Standard and Unlit Materials to HDRP Lit and Unlit Materials respectively. The processes use an overlay function to blend the color ch
I'd make "To help you convert..." The start of a new paragraph, this is a block at the moment.

2022-02-18 18:02 UTC, sebastienlagarde approved these changes

2022-02-18 18:02 UTC, merged