Vfx/feature/package sample button
Unity-Technologies/Graphics pull request #7199
Opened 2022-02-18 11:09 UTC by MarieGuff

### Samples github link button

Added a link to the github (public)repo of Visual Effect Graph Samples in the package manager. This link forward to the man page of the git repo, because the release page doesn't benefit from the visuals of the samples and the description of the project. 

![image](https://user-images.githubusercontent.com/71330456/154668614-9e272614-6714-46a5-bcab-78d715bca7cb.png)

Added file: com.unity.visualeffectgraph\Editor\SamplesLinkPackageManagerExtension

Copied and modified from: com.unity.terrain-tools\Editor\SamplesLinkPackageManagerExtension

# **Please read the [Contributing guide](CONTRIBUTING.md) before making a PR.**

* Read the [Graphics repository & Yamato FAQ](http://go/graphics-yamato-faq).

### Checklist for PR maker
- [ ] Have you added a backport label (if needed)? For example, the `need-backport-*` label. After you backport the PR, the label changes to `backported-*`. - NOT RELEVANT
- [X] Have you updated the changelog? Each package has a `CHANGELOG.md` file.
- [X] Have you updated or added the documentation for your PR? When you add a new feature, change a property name, or change the behavior of a feature, it's best practice to include related documentation changes in the same PR. If you do add documentation, make sure to add the relevant Graphics Docs team member as a reviewer of the PR. If you are not sure which person to add, see the [Docs team contacts sheet](https://docs.google.com/spreadsheets/d/1rgUWWgwLFEHIQ3Rz-LnK6PAKmbM49DZZ9al4hvnztOo/edit#gid=1058860420).
- [ ] Have you added a graphic test for your PR (if needed)? When you add a new feature, or discover a bug that tests don't cover, please add a graphic test. -NOT RELEVANT

---
### Purpose of this PR
Why is this PR needed, what hard problem is it solving/fixing?

Better access for the user to the VFX Graph samples project

---
### Testing status
Describe what manual/automated tests were performed for this PR

Button works find, not visible on other packages (2022.2.0a6)

---
### Comments to reviewers
Notes for the reviewers you have assigned.

2022-02-18 12:54 UTC, SeanPuller requested changes

2022-02-18 12:54 UTC, SeanPuller commented on com.unity.visualeffectgraph/Editor/SamplesLinkPackageManagerExtension.cs.meta
> +guid: 4ae080a8a6a24a9418d6cfc4f4ad403f
this guid is the same as the guid for the meta file in the terrain tools package. it needs to be updated and pushed, one should be generated by default

2022-02-18 15:12 UTC, VladNeykov commented
Hi, since Vita is out just dropping a few UX-y comments:
- The samples are mainly HDRP, it might be a bit misleading for URP users to have that button without more context.
- **Download** implies that the button will download the samples, but it's just an external link. 
- One button for one link might not scale well. Wonder if a resources doc page on our manual where we can add various link (samples, spaceship demo, learning materials, that Scenario Week vfx samples project, etc.) might not be a better place? Maybe somewhere here on top:
![image](https://user-images.githubusercontent.com/7230872/154709036-aeaeaeb8-96c2-49ec-8de0-fa99587c2cf6.png)
- We already have a link to the samples from within the VFX Graph. No objections for having it in more places, just FYI:
![Unity_jIKWuOekDV](https://user-images.githubusercontent.com/7230872/154709147-ba2fb1e4-289c-42fd-8f9d-7adee735447b.gif)

2022-02-21 08:45 UTC, MarieGuff commented
> Hi, since Vita is out just dropping a few UX-y comments:
> 
> * The samples are mainly HDRP, it might be a bit misleading for URP users to have that button without more context.
> * **Download** implies that the button will download the samples, but it's just an external link.
> * One button for one link might not scale well. Wonder if a resources doc page on our manual where we can add various link (samples, spaceship demo, learning materials, that Scenario Week vfx samples project, etc.) might not be a better place? Maybe somewhere here on top:
>   ![image](https://user-images.githubusercontent.com/7230872/154709036-aeaeaeb8-96c2-49ec-8de0-fa99587c2cf6.png)
> * We already have a link to the samples from within the VFX Graph. No objections for having it in more places, just FYI:
>   ![Unity_jIKWuOekDV](https://user-images.githubusercontent.com/7230872/154709147-ba2fb1e4-289c-42fd-8f9d-7adee735447b.gif)

Thanks I will modify the button name
Unfortunately I haven't found any script/documentation/whatever to add a link somewhere else but i'll see if I find something (maybe doc team can help me with that?)
I will also try to find how to add a tooltip for more context, but otherwise i'll use the "HDRP Samples github page" name for the button 
I will start gathering ressources links and see with mathieu how to present it to make a global ressource page in a next update

2022-02-21 13:21 UTC, SeanPuller approved these changes

2022-02-21 13:58 UTC, MarieGuff commented
Future improvements:

- Combined link for several projects
- Button UI revision

2022-02-21 13:58 UTC, merged