Adding PS5 and GameCore platforms to template QualitySettings
Unity-Technologies/Graphics pull request #7316
Opened 2022-03-16 11:26 UTC by jmekh

### Purpose of this PR

This adds PS5, GameCoreScarlett (Xbox Series) and GameCoreXboxOne to the quality settings so they don't default to Low (for URP) or Highest Quality (for HDRP). This prevents obvious out-of-the-box visual differences from what the user gets in the editor and other platforms.
All was set to the same value for parity between consoles of the same generation and compatibility with consoles of the previous generations.

Fixes [#1401654](https://fogbugz.unity3d.com/f/cases/1401654/), also tracked by Jira task [#PLAT-1238](https://jira.unity3d.com/browse/PLAT-1238).

---
### Testing status
Manual test: opening templates projects and checking the Project Setting > Quality for each platform.

---
### Comments to reviewers

2022-03-23 17:20 UTC, vicky-voin requested changes
Could you please also update the `ValidationExceptions.json` files for both templates? The template version needs to be bumped in those files as well.

2022-03-23 19:30 UTC, vicky-voin approved these changes
Yamato is failing on formatting, but on the templates side everything looks good so I will approve.

2022-03-24 08:54 UTC, jmekh commented
Thanks Vicky :)
Formatting fails because of the following files that I haven't changed:
- com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Utility/HDUtils.cs
- com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/HDRenderPipeline.RenderGraph.cs

2022-03-24 13:38 UTC, vicky-voin commented
@jmekh Ok, as long as someone from the Graphics team approves the PR, we should be good to merge.

2022-03-29 08:55 UTC, alelievr approved these changes

2022-03-29 08:55 UTC, Verasl approved these changes
LGTM

2022-04-07 14:46 UTC, sebastienlagarde approved these changes

2022-04-07 14:47 UTC, merged