Fix aliasing artifact in MultiScaleVolumetricObscurance (AmbientOcclusion)
Unity-Technologies/Graphics pull request #7489
Opened 2022-06-14 23:21 UTC by Scoutydren

# **Please read the [Contributing guide](CONTRIBUTING.md) before making a PR.**

* Read the [Graphics repository & Yamato FAQ](http://go/graphics-yamato-faq).

### Checklist for PR maker
- [ ] Have you added a backport label (if needed)? For example, the `need-backport-*` label. After you backport the PR, the label changes to `backported-*`.
- [ ] Have you updated the changelog? Each package has a `CHANGELOG.md` file.
- [ ] Have you updated or added the documentation for your PR? When you add a new feature, change a property name, or change the behavior of a feature, it's best practice to include related documentation changes in the same PR. If you do add documentation, make sure to add the relevant Graphics Docs team member as a reviewer of the PR. If you are not sure which person to add, see the [Docs team contacts sheet](https://docs.google.com/spreadsheets/d/1rgUWWgwLFEHIQ3Rz-LnK6PAKmbM49DZZ9al4hvnztOo/edit#gid=1058860420).
- [ ] Have you added a graphic test for your PR (if needed)? When you add a new feature, or discover a bug that tests don't cover, please add a graphic test.

---
### Purpose of this PR
Fixes for the [FogBugz case](https://fogbugz.unity3d.com/f/cases/1375337) in Multi Scale Ambient Occlusion where there exists banding and aliasing artifacts when applying the post-processing. This fix adds a configurable parameter Z Bias in the MSVO UI settings and eliminates the banding artifact. 

---
### Testing status
Tested manually against [FogBugz case](https://fogbugz.unity3d.com/f/cases/1375337)  on Windows

---
### Comments to reviewers

2022-06-14 23:47 UTC, mikesfbay requested changes

2022-06-14 23:47 UTC, mikesfbay commented on com.unity.postprocessing/PostProcessing/Shaders/Builtins/MultiScaleVORender.compute
> +    float2 disocclusion1 = DepthSamples[base + offset] * invRange - (frontDepth - zBias);
frontDepth is related to invThickness of sphere samples, which isn't what we want. Z bias should be done on the screen sample in Main() before invThisDepth is calculated. Remember, thisIdx in Main() is the index of the screen sample where the sphere samples are centered around.

2022-06-16 21:58 UTC, ryanhy-unity approved these changes
Verified fix with customer repro project.  Checked Desktop D3D and Vulkan as well as Android.  Did a sanity check on URP PP which didn't exhibit any regresssions.  Finally, ran through the xr automated end to end test and manually checked a few random other PP effects.  Looks good to me.

2022-06-17 00:22 UTC, mikesfbay approved these changes

2022-06-17 00:22 UTC, mikesfbay commented on com.unity.postprocessing/Documentation~/Ambient-Occlusion.md
> +| Z Bias             | Modifies the z-bias to the depth buffer. This eliminates the banding aliasing artifact for MSVO. |
Also plz update the wording in the doc .md file.

2022-09-08 07:47 UTC, sebastienlagarde approved these changes

2022-11-28 17:09 UTC, mrtenda commented
Hi, I see that this change has been approved for about three months, but hasn't been merged in yet. According to LinkedIn, it seems that the original submitter of the PR was an intern at Unity but currently is no longer at Unity.

What are the next steps for this to get merged in?

This is an important fix as it seems to be related to this bug which is affecting multiple teams (including us) from shipping our games: https://issuetracker.unity3d.com/issues/horizontal-line-artifacts-when-using-ambient-occlusion-with-multi-scale-volumetric-obscurance

Thanks!

2022-11-28 21:33 UTC, mikesfbay commented
@sebastienlagarde Can we merge this PR to master soon (for postfx V2)? This fix will help several teams @mrtenda

2022-11-30 16:22 UTC, sebastienlagarde commented
Looks like postprocess test are broken :( . Not related to this PR

2022-11-30 16:22 UTC, merged