Make searcher item names the same as node titles
Unity-Technologies/Graphics pull request #7581
Opened 2022-07-31 21:46 UTC by brett-groshong

### Purpose of this PR

This change makes it so that items in the searcher and node titles match, and are derived from `NodeUIDescriptor.DisplayName`.

---
### Testing status

This change can be tested by doing the following.
* Change a `NodeUIDescriptor.DisplayName`
* Wait for a domain reload
* Summon the searcher
* Notice: the updated display name is in the list
* Create a node from the item with the updated display name
* Notice: the node has the same title, as does the inspector for the node

![2022-07-31 14 34 49](https://user-images.githubusercontent.com/96441566/182046599-74a6faa9-ed12-4c5d-ae46-56ac40f6ba1f.gif)

---
### Comments to reviewers

* Took care of a TODO in `ShaderGraphSearcherDatabaseProvider` so that searcher items with conflicting names aren't added.
* Changed `ShaderGraphSearcherDatabaseProvider` to not use a deprecated constructor for `GraphNodeModelSearcherItem` and instead create them directly (removed interim class).

2022-08-01 15:37 UTC, bencloward approved these changes

2022-08-02 22:42 UTC, Nightmask3 requested changes
some of the node definitions look like they're incorrectly specifying their display names with dupes of other nodes, causing conflicts and for some of these nodes to be left out from the searcher

2022-08-02 22:46 UTC, bencloward commented on com.unity.sg2/Editor/GraphUI/DataModel/Searcher/ShaderGraphSearcherDatabaseProvider.cs
> +                            Debug.LogWarning($"Not adding \"{searcherItemName}\" to the searcher. A searcher item with this name already exists.");
Ouch - my bad.  Brett, you want to fix those as part of this set of changes, or should I change it separately?

2022-08-03 00:25 UTC, Nightmask3 approved these changes
Ben will address these issues in an immediate follow up PR

2022-08-03 13:43 UTC, brett-groshong commented on com.unity.sg2/Editor/GraphUI/DataModel/Searcher/ShaderGraphSearcherDatabaseProvider.cs
> +                            Debug.LogWarning($"Not adding \"{searcherItemName}\" to the searcher. A searcher item with this name already exists.");
It looks like they were fixed in a separate PR. Closing this conversation and merging.

2022-08-03 13:44 UTC, merged