Sg2/update mid dec
Unity-Technologies/Graphics pull request #7774
Opened 2022-12-21 21:52 UTC by brett-groshong

### Purpose of this PR

This change fixes compilation errors due to updates to dependencies and updates dependencies. 

---
### Testing status

Automated test suite will detect regressions.

2023-01-20 19:25 UTC, elizabeth-legros approved these changes

2023-01-20 20:35 UTC, patrickfournier commented
I just pulled sg2/staging and opened your branch. Not sure if this is expected, but I get countless (999+) warnings and 20 errors when opening ShaderGraphPlayground. Also, these 3 files were updated by the Unity API updater:

C:\UnitySrc\Graphics_wt3\com.unity.sg2\Editor\GraphUI\DataModel\SGNodeModel.cs
C:\UnitySrc\Graphics_wt3\com.unity.sg2\Editor\GraphUI\GraphElements\ModelUI\SGNodeView.cs
C:\UnitySrc\Graphics_wt3\com.unity.sg2\Editor\GraphUI\ModelInspectorFactoryExtensions.cs

All changes are related to recent change in GTF renaming ModelSetting to NodeOption. You should commit the updated version of these files.

I also have 11 test failures.

![image](https://user-images.githubusercontent.com/1007824/213800541-82679122-2531-45d2-8f30-05ab328270be.png)

2023-01-23 14:06 UTC, patrickfournier requested changes
- Please commit auto-update files.
- Please fix or disable failing tests

2023-01-23 16:17 UTC, brett-groshong commented
> I just pulled sg2/staging and opened your branch. Not sure if this is expected, but I get countless (999+) warnings and 20 errors when opening ShaderGraphPlayground. Also, these 3 files were updated by the Unity API updater:
> 
> C:\UnitySrc\Graphics_wt3\com.unity.sg2\Editor\GraphUI\DataModel\SGNodeModel.cs C:\UnitySrc\Graphics_wt3\com.unity.sg2\Editor\GraphUI\GraphElements\ModelUI\SGNodeView.cs C:\UnitySrc\Graphics_wt3\com.unity.sg2\Editor\GraphUI\ModelInspectorFactoryExtensions.cs
> 
> All changes are related to recent change in GTF renaming ModelSetting to NodeOption. You should commit the updated version of these files.
> 
> I also have 11 test failures.
> 
> ![image](https://user-images.githubusercontent.com/1007824/213800541-82679122-2531-45d2-8f30-05ab328270be.png)
> 
> EDIT: the 20 errors and 999+ warnings only happen the first time I open the project.

I caused the above errors for @patrickfournier by rebasing onto `sg2/main`. This was cleared up and I'll be sure to add that to the "notes to reviewers" in the future.

2023-01-23 16:49 UTC, patrickfournier approved these changes

2023-01-23 17:56 UTC, merged