Sg2 upcoming staging
Unity-Technologies/Graphics pull request #7813
Opened 2023-02-09 18:02 UTC by iTris666

---
### Purpose of this PR
Small fixes and update to HDRP and UPR 16.0 to be compatible with upcoming sg2/staging that has gtf/staging and therefore trunk merged.

---
### Testing status
Minimal testing done, create an asset, add some nodes.

---
### Comments to reviewers
Notes for the reviewers you have assigned.

2023-02-09 18:18 UTC, SebGrenier requested changes
I think we also need to update `TestGraphView` and `TestEditorWindow` in `com.unity.sg2\Tests\GraphUI` for the new `Create` method.

2023-02-10 16:02 UTC, iTris666 commented
> I think we also need to update `TestGraphView` and `TestEditorWindow` in `com.unity.sg2\Tests\GraphUI` for the new `Create` method.

good catch.

2023-02-10 18:52 UTC, SebGrenier approved these changes

2023-02-13 16:42 UTC, brett-groshong approved these changes

2023-02-13 16:50 UTC, merged