Renaming Nodes based on feedback from Anita and Martin
Unity-Technologies/Graphics pull request #7821
Opened 2023-02-15 21:43 UTC by bencloward

### Purpose of this PR
This set of nodes have been renamed to remove verbs from the title, remove abbreviations, and name the names more clear.

![image](https://user-images.githubusercontent.com/88061215/219174453-f3b77737-4549-49e6-b7cd-34196593b914.png)

---
### Testing status
Functionality of the nodes has not changed at all. All of the effected nodes still appear in the searcher and work correctly in the graph.

---
### Comments to reviewers
In addition to just changing the Display Name for the nodes, I've also renamed the file itself, the class name, and the string name so that all are exactly consistent.  This makes finding the code file much easier when tracking down issues with the node.

2023-02-20 16:56 UTC, marnadeau requested changes
Old names should be searchable and return new name as a result

2023-02-21 17:54 UTC, marnadeau requested changes
The only one I can't find is when I use the old name "Blend Water Normal"
All the other old names work 👍

2023-02-21 19:59 UTC, bencloward commented
Ok, I've fixed "Blend Water Normal"

2023-02-21 21:26 UTC, marnadeau approved these changes

2023-02-21 23:14 UTC, merged