Renamed and Reorganized Constant and Constructor nodes
Unity-Technologies/Graphics pull request #7855
Opened 2023-03-31 22:16 UTC by bencloward

### Purpose of this PR
We are preparing to introduce Martin's new design for slimmed down constant nodes. In Shader Graph 1, our Float, Vector 2, Vector 3, and Vector 4 nodes were serving two purposes. They were both constants AND constructors. I've fixed that now by moving the constructors into a new Math/Constructors category - so the versions with inputs that allow you to construct vectors from individual floats that you wire in are now called Create Vector 2, Create Vector 3, Create Vector 4 - and I also moved the Matrix Construction node to that same category and renamed it to Create Matrix.

So the Math/Constructors look like this:
![image](https://user-images.githubusercontent.com/88061215/229241889-381bd06e-84ee-4cdd-92d6-680afe6cb16e.png)

In the Input/Basic category, I've created new non-constructor versions of the nodes. These are just constants with no input ports. The Input/Basic nodes now look like this:
![image](https://user-images.githubusercontent.com/88061215/229241962-252de623-7e66-4bd5-a179-4378c25f1744.png)

And these are the versions that will soon replaced by Martin's new slimmer design for the constant nodes.
![image](https://user-images.githubusercontent.com/88061215/229242227-183c0b26-dbd9-4716-8998-773dc68bdbb4.png)

For each of these changes, I've also renamed the corresponding node preview file.

2023-04-04 16:59 UTC, tracychen1234 requested changes
Looking good! Just an empty file change that I don't know what it was.

2023-04-04 16:59 UTC, tracychen1234 commented on ShaderGraphPlayground/Assets/~UnityDirMonSyncFile~fb2cfc20dd054d849bf7ec7a09e013c9~
Not sure what it is🤔 Maybe can remove it?

2023-04-04 17:02 UTC, bencloward commented on ShaderGraphPlayground/Assets/~UnityDirMonSyncFile~fb2cfc20dd054d849bf7ec7a09e013c9~
I have no idea what that was.  I deleted it.

2023-04-05 20:43 UTC, marnadeau approved these changes

2023-04-05 21:04 UTC, tracychen1234 approved these changes

2023-04-05 22:11 UTC, merged