Switch input backend to input system exclusive TBD
Unity-Technologies/Graphics pull request #8118
Opened 2024-12-19 08:46 UTC by Pauliusd01

# **Please read the [Contributing guide](CONTRIBUTING.md) before making a PR.**

* Read the [Graphics repository & Yamato FAQ](http://go/graphics-yamato-faq).

### Checklist for PR maker
- [ ] Have you added a backport label (if needed)? For example, the `need-backport-*` label. After you backport the PR, the label changes to `backported-*`.
- [ ] Have you updated the changelog? Each package has a `CHANGELOG.md` file.
- [ ] Have you updated or added the documentation for your PR? When you add a new feature, change a property name, or change the behavior of a feature, it's best practice to include related documentation changes in the same PR. If you do add documentation, make sure to add the relevant Graphics Docs team member as a reviewer of the PR. If you are not sure which person to add, see the [Docs team contacts sheet](https://docs.google.com/spreadsheets/d/1rgUWWgwLFEHIQ3Rz-LnK6PAKmbM49DZZ9al4hvnztOo/edit#gid=1058860420).
- [ ] Have you added a graphic test for your PR (if needed)? When you add a new feature, or discover a bug that tests don't cover, please add a graphic test.

---
### Purpose of this PR
Why is this PR needed, what hard problem is it solving/fixing?

---
### Testing status
Describe what manual/automated tests were performed for this PR

---
### Comments to reviewers
Notes for the reviewers you have assigned.

2024-12-19 11:37 UTC, lyndon-unity approved these changes
Good to see input system version updated and set to Input System only

I see there are input action assets already present in the projects
Was slightly surprised the input system package dependency was missing for hdrp-blank given that there was the input action asset in the project.

Note this is related to task https://jira.unity3d.com/browse/ISX-2217
Which is related to this Epic https://jira.unity3d.com/browse/ISX-2214

2024-12-19 11:41 UTC, lyndon-unity requested changes
On reflection I think its the manifest.json file that also needs changing. Not just the package.json file

2024-12-19 13:30 UTC, lyndon-unity approved these changes
Thanks for the more comprehensive update with changelogs and version updates

2025-01-17 15:21 UTC, lyndon-unity requested changes
Update the input system dependency to 1.12.0 to get the console platform warnings too.

2025-01-17 15:21 UTC, lyndon-unity commented on com.unity.template-hd/Packages/com.unity.template.hd/package.json
> +    "com.unity.inputsystem": "1.11.2",
This should be updated to 1.12.0 now

2025-01-20 12:29 UTC, lyndon-unity approved these changes

2025-01-23 08:31 UTC, Pauliusd01 commented
@sebastien-unity this seems good to go

2025-01-23 16:01 UTC, sebastien-unity commented
@Pauliusd01 Can you give me more context on where my approval is needed? Looking at the files, I'm not finding anything I'm familiar with. Thank you!

2025-01-28 06:50 UTC, closed without merging

2025-01-28 06:51 UTC, Pauliusd01 commented
Done here instead : https://github.com/Unity-Technologies/Graphics/pull/8126 / https://github.com/Unity-Technologies/Graphics/pull/8125